### ISSUE TITLE
batch_max_steps and batch_max_steps_valid in melgan and multiband_melgan

### ISSUE THREAD

**Issue by ZhaoZeqing** [TensorSpeech/TensorflowTTS#103]
I had tried training multiband_melgan in my own dataset and found that **batch_max_steps_valid** is 10 times than **batch_max_steps**, but why?
https://github.com/TensorSpeech/TensorflowTTS/blob/db692cbbee3fcfa257bcaece6298905ef3fe25d9/examples/multiband_melgan/conf/multiband_melgan.v1.yaml#L69-#L70

And I also found that **batch_max_steps** is used to filter some short audios, a little puzzled
https://github.com/TensorSpeech/TensorflowTTS/blob/21a8f3687df27a89ee993e59eaa16ae872a5e529/examples/melgan/train_melgan.py#L520-#L523
https://github.com/TensorSpeech/TensorflowTTS/blob/21a8f3687df27a89ee993e59eaa16ae872a5e529/examples/melgan/audio_mel_dataset.py#L74-#L87

**Comment by dathudeptrai** [comment]
@ZhaoZeqing hi, in training we use batch_max_steps=8192 ->> len mel = (8192//256) = 32 frames. This audio segment is around 0.3-0.5s, but on inference, we want to hear longer audio to check the performance so we use 81920 ~ 4s audio :D. We also remove all short audio <= 32 frames (assumed it's noise audio :D).

**Comment by ZhaoZeqing** [comment]
> @ZhaoZeqing hi, in training we use batch_max_steps=8192 ->> len mel = (8192//256) = 32 frames. This audio segment is around 0.3-0.5s, but on inference, we want to hear longer audio to check the performance so we use 81920 ~ 4s audio :D. We also remove all short audio <= 32 frames (assumed it's noise audio :D).

@dathudeptrai Thanks for your prompt reply! The shortest audio in my valid datasets has 111 frams, when I set **batch_max_steps**->> 32 frams, **batch_max_steps_valid** ->>100 frams, this error occurred:

2020-07-09 14:43:58,812 (train_melgan:221) INFO: (Steps: 5) Start evaluation.
Traceback (most recent call last):
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 1986, in execution_mode
    yield
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 655, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2363, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Paddings must be non-negative: 0 -49800
         [[{{node cond_4/else/_38/Pad}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/multiband_melgan/train_multiband_melgan.py", line 548, in <module>
    main()
  File "examples/multiband_melgan/train_multiband_melgan.py", line 540, in main
    resume=args.resume,
  File "./examples/melgan/train_melgan.py", line 377, in fit
    self.run()
  File "lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 67, in run
    self._train_epoch()
  File "anaconda3/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 93, in _train_epoch
    self._check_eval_interval()
  File "anaconda3/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 135, in _check_eval_interval
    self._eval_epoch()
  File "./examples/melgan/train_melgan.py", line 225, in _eval_epoch
    self.eval_data_loader, 1
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 631, in __next__
    return self.next()
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 670, in next
    return self._next_internal()
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 661, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 1989, in execution_mode
    executor_new.wait()
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Paddings must be non-negative: 0 -49800

**Comment by dathudeptrai** [comment]
@ZhaoZeqing is everything fine with batch_max_step_valid = 81920 ?

**Comment by ZhaoZeqing** [comment]
> @ZhaoZeqing is everything fine with batch_max_step_valid = 81920 ?

Our sample rate is 48k, hop_size=600, when batch_max_step_valid=batch_max_steps=19200, everything is ok, but when batch_max_steps=19200, batch_max_step_valid=192000 or 60000, the error occurred

**Comment by dathudeptrai** [comment]
@ZhaoZeqing check  this https://github.com/TensorSpeech/TensorflowTTS/blob/master/examples/multiband_melgan/train_multiband_melgan.py#L465-L471. Maybe because we forgot pass hop_size parameter into the function so the hop_size is still 256

**Comment by ZhaoZeqing** [comment]
> @ZhaoZeqing check this https://github.com/TensorSpeech/TensorflowTTS/blob/master/examples/multiband_melgan/train_multiband_melgan.py#L465-L471. Maybe because we forgot pass hop_size parameter into the function so the hop_size is still 256

Oh!!! I noticed this problem, but modified in melgan/train_melgan.py by mistake, many thanks!
But after I modified multiband_melgan/train_meltiband_melgan.py, a new error occurred:

Traceback (most recent call last):
  File "examples/multiband_melgan/train_multiband_melgan.py", line 544, in <module> main()
  File "examples/multiband_melgan/train_multiband_melgan.py", line 536, in main resume=args.resume,
  File "./examples/melgan/train_melgan.py", line 377, in fit self.run()
  File "anaconda3/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 67, in run self._train_epoch()
  File "anaconda3/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 89, in _train_epoch self._train_step(batch)
  File "examples/multiband_melgan/train_multiband_melgan.py", line 110, in _train_step y, y_hat = self._one_step_generator(y, mels)
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__ result = self._call(*args, **kwds)
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call  self._initialize(args, kwds, add_initializers_to=initializers)
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize *args, **kwds))
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function graph_function = self._create_graph_function(args, kwargs)
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function capture_by_value=self._capture_by_value),
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func func_outputs = python_func(*func_args, **func_kwargs)
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3299, in bound_method_wrapper  return wrapped_fn(*args, **kwargs)
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    examples/multiband_melgan/train_multiband_melgan.py:139 _one_step_generator  * sub_sc_loss, sub_mag_loss = self.sub_band_stft_loss(y_mb, y_mb_hat)
    anaconda3/lib/python3.7/site-packages/tensorflow_tts/losses/stft.py:142 call  * sc_l, mag_l = f(y, x)
    anaconda3/lib/python3.7/site-packages/tensorflow_tts/losses/stft.py:101 call  * sc_loss = self.spectral_convergenge_loss(y_mag, x_mag)
    anaconda3/lib/python3.7/site-packages/tensorflow_tts/losses/stft.py:36 call  * y_mag, ord="fro", axis=(-2, -1)
   anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:984 binary_op_wrapper return func(x, y, name=name)
    anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py:10103 sub "Sub", x=x, y=y, name=name)
    anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:744 _apply_op_helper attrs=attr_protos, op_def=op_def)
    anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py:595 _create_op_internal compute_device)
    anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:3327 _create_op_internal op_def=op_def)
    anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1817 __init__ control_input_ops, op_def)
    anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1657 _create_c_op raise ValueError(str(e))

    ValueError: Dimensions must be equal, but are 156 and 64 for '{{node tf_multi_resolution_stft/tfstft/tf_spectral_convergence/sub}} = Sub[T=DT_FLOAT](tf_multi_resolution_stft/tfstft/Sqrt_1, tf_multi_resolution_stft/tfstft/Sqrt)' with input shapes: [256,156,193], [256,64,193].

**Comment by dathudeptrai** [comment]
@ZhaoZeqing weird, it should be the same shape. Can you make the fork of this repo and update what you changed then i can debug ?. It seem that len(audio_gts) != len(audio_preds). Thanks

**Comment by ZhaoZeqing** [comment]
> @ZhaoZeqing weird, it should be the same shape. Can you make the fork of this repo and update what you changed then i can debug ?. It seem that len(audio_gts) != len(audio_preds). Thanks

@dathudeptrai I forked this repo and update my code on this branch: https://github.com/ZhaoZeqing/TensorflowTTS/tree/sr_48k  
Many thanks!

**Comment by dathudeptrai** [comment]
@ZhaoZeqing https://github.com/ZhaoZeqing/TensorflowTTS/blob/sr_48k/examples/multiband_melgan/conf/multiband_melgan.v1.yaml#L22 here, the upsamples scales is wrong. we set it to [8, 4, 2] because 8 * 4 * 2 * (n_bands) = 8 * 4 * 2 * 4 = 256 (hop_size). Also in https://github.com/ZhaoZeqing/TensorflowTTS/blob/sr_48k/examples/multiband_melgan/conf/multiband_melgan.v1.yaml#L40 is the same logic as above :D. 4 * 4 * 4 * 4 = 256

**Comment by ZhaoZeqing** [comment]
> @ZhaoZeqing https://github.com/ZhaoZeqing/TensorflowTTS/blob/sr_48k/examples/multiband_melgan/conf/multiband_melgan.v1.yaml#L22 here, the upsamples scales is wrong. we set it to [8, 4, 2] because 8 * 4 * 2 * (n_bands) = 8 * 4 * 2 * 4 = 256 (hop_size). Also in https://github.com/ZhaoZeqing/TensorflowTTS/blob/sr_48k/examples/multiband_melgan/conf/multiband_melgan.v1.yaml#L40 is the same logic as above :D. 4 * 4 * 4 * 4 = 256. BTW, seem 48k is too large, i recommend you sampling it into 24k :))) and use hop_size = 300 :D or sampling it into 22050 hz as ljspeech :'(

@dathudeptrai Thank you very mucn! I will try 24k :)

**Comment by dathudeptrai** [comment]
@ZhaoZeqing maybe you want follow https://github.com/TensorSpeech/TensorflowTTS/pull/105. He finished training mb-melgan for chinese dataset (24k) :))

**Comment by ZhaoZeqing** [comment]
> @ZhaoZeqing maybe you want follow #105. He finished training mb-melgan for chinese dataset (24k) :))

@dathudeptrai Cool~ :D
