### ISSUE TITLE
How can I decode mel-spectrogram from folder ids during training?

### ISSUE THREAD

**Issue by wannaphong** [TensorSpeech/TensorflowTTS#112]
Hello. I training tacotron2 model. I want to create a Decode mel-spectrogram from folder ids while training. I want to use checkpoints for speech synthesis but it's error.
```

# CUDA_VISIBLE_DEVICES=1 python examples/tacotron2/decode_tacotron2.py \
  --rootdir ./dump/valid/ \
  --outdir ./prediction/tacotron2-10000/ \
  --checkpoint ./examples/tacotron2/exp/train.tacotron2.v1/checkpoints/model-10000.h5 \
  --config ./examples/tacotron2/conf/tacotron2.v1.yaml \
  --batch-size 32> > > > >
2020-07-13 10:11:34.343241: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-13 10:11:37.052076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:07:00.0 name: *** computeCapability: 7.0
coreClock: 1.44GHz coreCount: 80 deviceMemorySize: **.**GiB deviceMemoryBandwidth: ***GiB/s
2020-07-13 10:11:37.052406: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-13 10:11:37.054565: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-13 10:11:37.056247: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-13 10:11:37.056624: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-13 10:11:37.058689: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-13 10:11:37.059624: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-13 10:11:37.064253: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-13 10:11:37.075623: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-07-13 10:11:37.075956: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-13 10:11:37.112758: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: *****0000 Hz
2020-07-13 10:11:37.118836: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f43f4000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-13 10:11:37.118870: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-13 10:11:42.957754: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5977cd0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-07-13 10:11:42.957809: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-SXM2-32GB-LS, Compute Capability 7.0
2020-07-13 10:11:42.961911: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:07:00.0 name: Tesla V100-SXM2-32GB-LS computeCapability: 7.0
coreClock: 1.44GHz coreCount: 80 deviceMemorySize: **.**GiB deviceMemoryBandwidth: 772.48GiB/s
2020-07-13 10:11:42.962031: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-13 10:11:42.962063: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-13 10:11:42.962102: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-13 10:11:42.962140: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-13 10:11:42.962177: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-13 10:11:42.962206: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-13 10:11:42.962231: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-13 10:11:42.970215: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-07-13 10:11:42.970315: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-13 10:11:42.975474: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-13 10:11:42.975498: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2020-07-13 10:11:42.975533: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2020-07-13 10:11:42.984781: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 29973 MB memory) -> physical GPU (device: 0, name: ****, pci busid: 0000:07:00.0, compute capability: 7.0)
2020-07-13 10:12:20.131737: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-13 10:12:22.399901: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
[Decoding]: 0it [00:00, ?it/s]2020-07-13 10:13:25.613557: W tensorflow/core/kernels/data/cache_dataset_ops.cc:794] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
[Decoding]: 0it [00:02, ?it/s]
Traceback (most recent call last):
  File "examples/tacotron2/decode_tacotron2.py", line 170, in <module>
    main()
  File "examples/tacotron2/decode_tacotron2.py", line 146, in main
    speaker_ids=tf.zeros(shape=[tf.shape(charactor)[0]], dtype=tf.int32),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3299, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
NameError: in user code:

    /workspace/tts/TensorflowTTS-*/tensorflow_tts/models/tacotron2.py:910 inference  *
        return decoder_output, mel_outputs, stop_token_prediction, alignment_history

    NameError: name 'alignment_history' is not defined
```

**Comment by dathudeptrai** [comment]
@wannaphong i think you are using an old version. see this https://github.com/TensorSpeech/TensorflowTTS/issues/106. I already fixed this error. You can clone master or r0.7 branch to fix this issue.

**Comment by wannaphong** [comment]
> 
> 
> @wannaphong i think you are using an old version. see this #106. I already fixed this error. You can clone master or r0.7 branch to fix this issue.

Thank you. It fixed this error. 👍

**Comment by dathudeptrai** [comment]
@wannaphong hi :)), is there any public dataset for Thai language :)), i also want support Thai haha. i'm come from vietnam :D
