### ISSUE TITLE
MultiGPU ERROR

### ISSUE THREAD

**Issue by unparalleled-ysj** [TensorSpeech/TensorflowTTS#131]
Hello, I tried your latest MultiGPU solution, and encountered the following problem when running

(tts) [root@localhost TensorflowTTS]# CUDA_VISIBLE_DEVICES=0,1,2,3 python examples/tacotron2/train_tacotron2.py --train-dir ljspeech/train/ --dev-dir ljspeech/valid/ --outdir examples/tacotron2/exp/ljspeech/ --config examples/tacotron2/conf/tacotron2.v1.yaml --use-norm 1 --mixed_precision 0 --resume ""
2020-07-22 03:11:03.355395: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-07-22 03:11:04.307465: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-07-22 03:11:12.959020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:04:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-07-22 03:11:12.960075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties: 
pciBusID: 0000:05:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-07-22 03:11:12.961095: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 2 with properties: 
pciBusID: 0000:06:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-07-22 03:11:12.962117: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 3 with properties: 
pciBusID: 0000:07:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-07-22 03:11:12.962171: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-07-22 03:11:12.964217: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-07-22 03:11:12.966252: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-07-22 03:11:12.966544: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-07-22 03:11:12.968827: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-07-22 03:11:12.969929: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-07-22 03:11:12.974549: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-07-22 03:11:12.982032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1, 2, 3
/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow_addons/utils/ensure_tf_install.py:68: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.2.0 and strictly below 2.3.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.3.0-rc2 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  UserWarning,
2020-07-22 03:11:13.504852: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-07-22 03:11:13.519808: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400010000 Hz
2020-07-22 03:11:13.526623: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f09c0cb750 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-22 03:11:13.526688: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-22 03:11:14.022415: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f09ab03580 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-07-22 03:11:14.022495: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-07-22 03:11:14.022518: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-07-22 03:11:14.022536: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (2): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-07-22 03:11:14.022575: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (3): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-07-22 03:11:14.025110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:04:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-07-22 03:11:14.027033: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties: 
pciBusID: 0000:05:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-07-22 03:11:14.028941: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 2 with properties: 
pciBusID: 0000:06:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-07-22 03:11:14.030831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 3 with properties: 
pciBusID: 0000:07:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-07-22 03:11:14.030912: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-07-22 03:11:14.030960: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-07-22 03:11:14.031018: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-07-22 03:11:14.031078: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-07-22 03:11:14.031116: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-07-22 03:11:14.031154: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-07-22 03:11:14.031193: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-07-22 03:11:14.044513: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1, 2, 3
2020-07-22 03:11:14.044576: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-07-22 03:11:15.650284: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-22 03:11:15.650355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 1 2 3 
2020-07-22 03:11:15.650367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N N N N 
2020-07-22 03:11:15.650375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 1:   N N N N 
2020-07-22 03:11:15.650385: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 2:   N N N N 
2020-07-22 03:11:15.650393: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 3:   N N N N 
2020-07-22 03:11:15.655154: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10074 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:04:00.0, compute capability: 7.5)
2020-07-22 03:11:15.657073: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10074 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:05:00.0, compute capability: 7.5)
2020-07-22 03:11:15.658440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 10074 MB memory) -> physical GPU (device: 2, name: GeForce RTX 2080 Ti, pci bus id: 0000:06:00.0, compute capability: 7.5)
2020-07-22 03:11:15.660213: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 10074 MB memory) -> physical GPU (device: 3, name: GeForce RTX 2080 Ti, pci bus id: 0000:07:00.0, compute capability: 7.5)
2020-07-22 03:11:23,015 (train_tacotron2:388) INFO: hop_size = 256
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: format = npy
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: tacotron2_params = {'embedding_hidden_size': 512, 'initializer_range': 0.02, 'embedding_dropout_prob': 0.1, 'n_speakers': 1, 'n_conv_encoder': 5, 'encoder_conv_filters': 512, 'encoder_conv_kernel_sizes': 5, 'encoder_conv_activation': 'relu', 'encoder_conv_dropout_rate': 0.5, 'encoder_lstm_units': 256, 'n_prenet_layers': 2, 'prenet_units': 256, 'prenet_activation': 'relu', 'prenet_dropout_rate': 0.5, 'n_lstm_decoder': 1, 'reduction_factor': 1, 'decoder_lstm_units': 1024, 'attention_dim': 128, 'attention_filters': 32, 'attention_kernel': 31, 'n_mels': 80, 'n_conv_postnet': 5, 'postnet_conv_filters': 512, 'postnet_conv_kernel_sizes': 5, 'postnet_dropout_rate': 0.1, 'attention_type': 'lsa'}
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: batch_size = 16
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: remove_short_samples = True
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: allow_cache = True
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: mel_length_threshold = 32
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: is_shuffle = True
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: use_fixed_shapes = True
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: optimizer_params = {'initial_learning_rate': 0.001, 'end_learning_rate': 1e-05, 'decay_steps': 150000, 'warmup_proportion': 0.02, 'weight_decay': 0.001}
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: train_max_steps = 200000
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: save_interval_steps = 2000
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: eval_interval_steps = 500
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: log_interval_steps = 200
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: start_schedule_teacher_forcing = 200001
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: start_ratio_value = 0.5
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: schedule_decay_steps = 50000
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: end_ratio_value = 0.0
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: num_save_intermediate_results = 1
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: train_dir = ljspeech/train/
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: dev_dir = ljspeech/valid/
2020-07-22 03:11:23,016 (train_tacotron2:388) INFO: use_norm = True
2020-07-22 03:11:23,017 (train_tacotron2:388) INFO: outdir = examples/tacotron2/exp/ljspeech/
2020-07-22 03:11:23,017 (train_tacotron2:388) INFO: config = examples/tacotron2/conf/tacotron2.v1.yaml
2020-07-22 03:11:23,017 (train_tacotron2:388) INFO: resume = 
2020-07-22 03:11:23,017 (train_tacotron2:388) INFO: verbose = 1
2020-07-22 03:11:23,017 (train_tacotron2:388) INFO: mixed_precision = False
2020-07-22 03:11:23,017 (train_tacotron2:388) INFO: version = 0.6.1
2020-07-22 03:11:23,017 (train_tacotron2:388) INFO: max_mel_length = 870
2020-07-22 03:11:23,017 (train_tacotron2:388) INFO: max_char_length = 188
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2020-07-22 03:11:23,580 (cross_device_ops:443) INFO: Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2020-07-22 03:11:23,583 (cross_device_ops:443) INFO: Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2020-07-22 03:11:23,585 (cross_device_ops:443) INFO: Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2020-07-22 03:11:23,587 (cross_device_ops:443) INFO: Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2020-07-22 03:11:23,589 (cross_device_ops:443) INFO: Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2020-07-22 03:11:23,591 (cross_device_ops:443) INFO: Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2020-07-22 03:11:23,593 (cross_device_ops:443) INFO: Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2020-07-22 03:11:23,595 (cross_device_ops:443) INFO: Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2020-07-22 03:11:23,597 (cross_device_ops:443) INFO: Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2020-07-22 03:11:23,599 (cross_device_ops:443) INFO: Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
Traceback (most recent call last):
  File "examples/tacotron2/train_tacotron2.py", line 471, in <module>
    main()
  File "examples/tacotron2/train_tacotron2.py", line 424, in main
    tacotron2._build()
  File "/work/ysj/TensorflowTTS/tensorflow_tts/models/tacotron2.py", line 757, in _build
    training=True,
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3735, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /work/ysj/TensorflowTTS/tensorflow_tts/models/tacotron2.py:784 call  *
        encoder_hidden_states = self.encoder(
    /work/ysj/TensorflowTTS/tensorflow_tts/models/tacotron2.py:221 call  *
        conv_outputs = self.convbn(input_embeddings, training=training)
    /work/ysj/TensorflowTTS/tensorflow_tts/models/tacotron2.py:193 call  *
        outputs = conv(outputs, training=training)
    /work/ysj/TensorflowTTS/tensorflow_tts/models/tacotron2.py:96 call  *
        outputs = self.norm(outputs, training=training)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:985 __call__  **
        outputs = call_fn(inputs, *args, **kwargs)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/keras/layers/normalization.py:853 call
        self.add_update(mean_update)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:507 new_func
        return func(*args, **kwargs)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:1750 add_update
        update()
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/keras/layers/normalization.py:829 mean_update
        return tf_utils.smart_cond(training, true_branch, false_branch)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/keras/utils/tf_utils.py:65 smart_cond
        pred, true_fn=true_fn, false_fn=false_fn, name=name)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/framework/smart_cond.py:54 smart_cond
        return true_fn()
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/keras/layers/normalization.py:827 <lambda>
        true_branch = lambda: _do_update(self.moving_mean, new_mean)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/keras/layers/normalization.py:824 _do_update
        input_batch_size)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/keras/layers/normalization.py:482 _assign_moving_average
        with ops.colocate_with(variable):
    /root/anaconda3/envs/tts/lib/python3.7/contextlib.py:112 __enter__
        return next(self.gen)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:4278 _colocate_with_for_gradient
        with self.colocate_with(op, ignore_existing):
    /root/anaconda3/envs/tts/lib/python3.7/contextlib.py:112 __enter__
        return next(self.gen)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:4327 colocate_with
        op = _op_to_colocate_with(op, self)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:6786 _op_to_colocate_with
        if hasattr(v, "handle") and isinstance(v.handle, Tensor):
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/distribute/values.py:571 handle
        raise ValueError("`handle` is not available outside the replica context"

    ValueError: `handle` is not available outside the replica context or a `tf.distribute.Strategy.update()` call.

(tts) [root@localhost TensorflowTTS]#

**Comment by dathudeptrai** [comment]
@unparalleled-ysj what is ur version of TF, can u install tf2.3.0rc2 ?

**Comment by unparalleled-ysj** [comment]
> @unparalleled-ysj what is ur version of TF, can u install tf2.3.0rc2 ?

Already version 2.3.0-rc2

(tts) [root@localhost TensorflowTTS]# python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2020-07-22 03:54:43.795747: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
>>> tf.__version__
'2.3.0-rc2'
>>>

**Comment by unparalleled-ysj** [comment]
and I use singleGPU to train, got this error

[train]:   0%|                                                                                                                                                                                     | 0/200000 [00:00<?, ?it/s]2020-07-22 03:58:20.486024: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 2738 of 12445
2020-07-22 03:58:30.484992: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 5464 of 12445
2020-07-22 03:58:40.486986: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 8508 of 12445
2020-07-22 03:58:50.487614: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 11285 of 12445
2020-07-22 03:58:54.959235: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:221] Shuffle buffer filled.
Traceback (most recent call last):
  File "examples/tacotron2/train_tacotron2.py", line 471, in <module>
    main()
  File "examples/tacotron2/train_tacotron2.py", line 463, in main
    resume=args.resume,
  File "/work/ysj/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py", line 852, in fit
    self.run()
  File "/work/ysj/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py", line 101, in run
    self._train_epoch()
  File "/work/ysj/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py", line 123, in _train_epoch
    self._train_step(batch)
  File "examples/tacotron2/train_tacotron2.py", line 109, in _train_step
    self.one_step_forward(batch)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /work/ysj/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py:674 _one_step_forward  *
        per_replica_losses = self._strategy.run(
    /work/ysj/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py:683 _one_step_forward_per_replica  *
        outputs = self._model(**batch, training=True)
    /work/ysj/TensorflowTTS/tensorflow_tts/models/tacotron2.py:796 call  *
        self.decoder.sampler.setup_target(targets=mel_gts, mel_lengths=mel_lengths)
    /work/ysj/TensorflowTTS/tensorflow_tts/models/tacotron2.py:247 setup_target  *
        self.targets = targets[
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:1024 _slice_helper
        name=name)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:1196 strided_slice
        shrink_axis_mask=shrink_axis_mask)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py:10352 strided_slice
        shrink_axis_mask=shrink_axis_mask, name=name)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:744 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py:593 _create_op_internal
        compute_device)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:3485 _create_op_internal
        op_def=op_def)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1975 __init__
        control_input_ops, op_def)
    /root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1815 _create_c_op
        raise ValueError(str(e))

    ValueError: Index out of range using input dim 1; input has only 1 dims for '{{node strided_slice_3}} = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=5, ellipsis_mask=0, end_mask=7, new_axis_mask=0, shrink_axis_mask=0](mel_gts, strided_slice_3/stack, strided_slice_3/stack_1, strided_slice_3/stack_2)' with input shapes: [8], [3], [3], [3] and with computed input tensors: input[3] = <1 1 1>.

[train]:   0%|                                                                                                                                                                                     | 0/200000 [00:46<?, ?it/s]
(tts) [root@localhost TensorflowTTS]#

**Comment by dathudeptrai** [comment]
@unparalleled-ysj let me test it again :D

**Comment by dathudeptrai** [comment]
@unparalleled-ysj can you replace: https://github.com/TensorSpeech/TensorflowTTS/blob/master/tensorflow_tts/models/tacotron2.py#L86 to 
```
tf.keras.layers.experimental.SyncBatchNormalization
```

**Comment by mapledxf** [comment]
I got same error after replacing with `tf.keras.layers.experimental.SyncBatchNormalization`.
Multi GPU: 
ValueError: `handle` is not available outside the replica context or a `tf.distribute.Strategy.update()` call.

Single GPU:
ValueError: Index out of range using input dim 1; input has only 1 dims for '{{node strided_slice_3}} = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=5, ellipsis_mask=0, end_mask=7, new_axis_mask=0, shrink_axis_mask=0](mel_gts, strided_slice_3/stack, strided_slice_3/stack_1, strided_slice_3/stack_2)' with input shapes: [32], [3], [3], [3] and with computed input tensors: input[3] = <1 1 1>.

**Comment by mapledxf** [comment]
@dathudeptrai 
I also got warning like this:
```
/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_addons/utils/ensure_tf_install.py:68: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.2.0 and strictly below 2.3.0 (nightly versions are not supported).
 The versions of TensorFlow you are currently using is 2.3.0-rc2 and is not supported.
```

**Comment by dathudeptrai** [comment]
I just commit https://github.com/TensorSpeech/TensorflowTTS/commit/7ae6e4e1f71a4363461dcecc018a3c4eff7ba409. Let try again :)).

**Comment by mapledxf** [comment]
@dathudeptrai 
Training with single GPU seems OK now. But I still got the same error with multi-GPU.

**Comment by unparalleled-ysj** [comment]
@dathudeptrai @mapledxf Me too

**Comment by dathudeptrai** [comment]
@mapledxf @unparalleled-ysj is that ok :)).

**Comment by unparalleled-ysj** [comment]
@dathudeptrai When using multi-GPU training, how to set the batch size of each GPU? the batch_size parameter in conf/tacotron2.v1.yaml means the total batch size of all gpu?

**Comment by dathudeptrai** [comment]
@unparalleled-ysj no, that is batch_size for each GPU, the global_batch_size will automatically multiple to n_gpus

**Comment by unparalleled-ysj** [comment]
@dathudeptrai  got it , thank you for your reply
