### ISSUE TITLE
Error when training Tacotron2

### ISSUE THREAD

**Issue by alexbernier** [TensorSpeech/TensorflowTTS#132]
Hi,
When I try to trian a Tacotron2 moel, I get the erreor below:
/home/abernier/.local/lib/python3.6/site-packages/tensorflow_addons/utils/ensure_tf_install.py:68: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.2.0 and strictly below 2.3.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.3.0-rc2 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  UserWarning,
[...]
2020-07-22 08:25:22.748694: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:221] Shuffle buffer filled.
Traceback (most recent call last):
  File "./examples/tacotron2/train_tacotron2.py", line 471, in <module>
    main()
  File "./examples/tacotron2/train_tacotron2.py", line 463, in main
    resume=args.resume,
  File "/data/repositories-ubuntu1/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py", line 852, in fit
    self.run()
  File "/data/repositories-ubuntu1/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py", line 101, in run
    self._train_epoch()
  File "/data/repositories-ubuntu1/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py", line 123, in _train_epoch
    self._train_step(batch)
  File "./examples/tacotron2/train_tacotron2.py", line 109, in _train_step
    self.one_step_forward(batch)
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /data/repositories-ubuntu1/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py:674 _one_step_forward  *
        per_replica_losses = self._strategy.run(
    /data/repositories-ubuntu1/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py:683 _one_step_forward_per_replica  *
        outputs = self._model(**batch, training=True)
    /data/repositories-ubuntu1/TensorflowTTS/tensorflow_tts/models/tacotron2.py:796 call  *
        self.decoder.sampler.setup_target(targets=mel_gts, mel_lengths=mel_lengths)
    /data/repositories-ubuntu1/TensorflowTTS/tensorflow_tts/models/tacotron2.py:247 setup_target  *
        self.targets = targets[
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py:1024 _slice_helper
        name=name)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py:1196 strided_slice
        shrink_axis_mask=shrink_axis_mask)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py:10352 strided_slice
        shrink_axis_mask=shrink_axis_mask, name=name)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:744 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py:593 _create_op_internal
        compute_device)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:3485 _create_op_internal
        op_def=op_def)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1975 __init__
        control_input_ops, op_def)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1815 _create_c_op
        raise ValueError(str(e))

    ValueError: Index out of range using input dim 1; input has only 1 dims for '{{node strided_slice_3}} = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=5, ellipsis_mask=0, end_mask=7, new_axis_mask=0, shrink_axis_mask=0](mel_gts, strided_slice_3/stack, strided_slice_3/stack_1, strided_slice_3/stack_2)' with input shapes: [32], [3], [3], [3] and with computed input tensors: input[3] = <1 1 1>.

Any idea?

**Comment by dathudeptrai** [comment]
@alexbernier i think i just fixed it on https://github.com/TensorSpeech/TensorflowTTS/commit/7ae6e4e1f71a4363461dcecc018a3c4eff7ba409

**Comment by alexbernier** [comment]
@dathudeptrai Thanks, it actually fixes the issue with 1 GPu. When trying with 2 GPU, I get the following new error:

Traceback (most recent call last):
  File "./examples/tacotron2/train_tacotron2.py", line 471, in <module>
    main()
  File "./examples/tacotron2/train_tacotron2.py", line 424, in main
    tacotron2._build()
  File "/data/repositories-ubuntu1/TensorflowTTS/tensorflow_tts/models/tacotron2.py", line 757, in _build
    training=True,
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3735, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /data/repositories-ubuntu1/TensorflowTTS/tensorflow_tts/models/tacotron2.py:784 call  *
        encoder_hidden_states = self.encoder(
    /data/repositories-ubuntu1/TensorflowTTS/tensorflow_tts/models/tacotron2.py:221 call  *
        conv_outputs = self.convbn(input_embeddings, training=training)
    /data/repositories-ubuntu1/TensorflowTTS/tensorflow_tts/models/tacotron2.py:193 call  *
        outputs = conv(outputs, training=training)
    /data/repositories-ubuntu1/TensorflowTTS/tensorflow_tts/models/tacotron2.py:96 call  *
        outputs = self.norm(outputs, training=training)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py:985 __call__  **
        outputs = call_fn(inputs, *args, **kwargs)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py:853 call
        self.add_update(mean_update)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py:507 new_func
        return func(*args, **kwargs)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py:1750 add_update
        update()
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py:829 mean_update
        return tf_utils.smart_cond(training, true_branch, false_branch)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/keras/utils/tf_utils.py:65 smart_cond
        pred, true_fn=true_fn, false_fn=false_fn, name=name)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/framework/smart_cond.py:54 smart_cond
        return true_fn()
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py:827 <lambda>
        true_branch = lambda: _do_update(self.moving_mean, new_mean)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py:824 _do_update
        input_batch_size)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py:482 _assign_moving_average
        with ops.colocate_with(variable):
    /usr/lib/python3.6/contextlib.py:81 __enter__
        return next(self.gen)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:4278 _colocate_with_for_gradient
        with self.colocate_with(op, ignore_existing):
    /usr/lib/python3.6/contextlib.py:81 __enter__
        return next(self.gen)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:4327 colocate_with
        op = _op_to_colocate_with(op, self)
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:6786 _op_to_colocate_with
        if hasattr(v, "handle") and isinstance(v.handle, Tensor):
    /home/abernier/.local/lib/python3.6/site-packages/tensorflow/python/distribute/values.py:571 handle
        raise ValueError("`handle` is not available outside the replica context"

    ValueError: `handle` is not available outside the replica context or a `tf.distribute.Strategy.update()` call.
