### ISSUE TITLE
There is some wrong in inference

### ISSUE THREAD

**Issue by learnerkun** [TensorSpeech/TensorFlowTTS#142]
this is the first  log:
Traceback (most recent call last):
  File "examples/fastspeech2/decode_fastspeech2.py", line 169, in <module>
    main()
  File "examples/fastspeech2/decode_fastspeech2.py", line 142, in main
    energy_ratios=tf.ones(shape=[tf.shape(char_ids)[0]], dtype=tf.float32),
  File "/usr/local/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 650, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/usr/local/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/usr/local/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/usr/local/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  indices[3,2048] = 2049 is not in [0, 2049)
	 [[node decoder/position_embeddings/embedding_lookup (defined at ./tensorflow_tts/models/fastspeech.py:463) ]]
  (1) Invalid argument:  indices[3,2048] = 2049 is not in [0, 2049)
	 [[node decoder/position_embeddings/embedding_lookup (defined at ./tensorflow_tts/models/fastspeech.py:463) ]]
	 [[decoder/position_embeddings/embedding_lookup/_120]]
0 successful operations.
0 derived errors ignored. [Op:__inference_inference_6274]

this is the second log:
    main()
  File "examples/fastspeech2/decode_fastspeech2.py", line 142, in main
    energy_ratios=tf.ones(shape=[tf.shape(char_ids)[0]], dtype=tf.float32),
  File "/usr/local/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 650, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/usr/local/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/usr/local/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/usr/local/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  indices[2,5025] = 5026 is not in [0, 2049)
	 [[node decoder/position_embeddings/embedding_lookup (defined at ./tensorflow_tts/models/fastspeech.py:463) ]]
  (1) Invalid argument:  indices[2,5025] = 5026 is not in [0, 2049)
	 [[node decoder/position_embeddings/embedding_lookup (defined at ./tensorflow_tts/models/fastspeech.py:463) ]]
	 [[decoder/position_embeddings/embedding_lookup/_120]]
0 successful operations.
0 derived errors ignored. [Op:__inference_inference_6274]

the inference data is only ids.

**Comment by dathudeptrai** [comment]
@learnerkun the bug shows that ur input length > 2048, the positional embedding in the model config is set to 2048.

**Comment by learnerkun** [comment]
I  have checked my inputs,its lengths are no more than 2048,the max  length is 786.And I tried to print the tensor,but I did not get the information for my input.How could I solve this bug?

**Comment by marzieh-razavi** [comment]
Hello, I am having the same issue. @learnerkun did you find any solution for this bug?

**Comment by dathudeptrai** [comment]
@marzieh-razavi give me a log.

**Comment by marzieh-razavi** [comment]
Here is the log:
Traceback (most recent call last):
  File "synthesize_new.py", line 62, in <module>
    energy_ratios = tf.constant([1.0], dtype=tf.float32)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 650, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  indices[0,2106] = 2107 is not in [0, 2049)
	 [[node decoder/position_embeddings/embedding_lookup (defined at /app/TensorflowTTS/tensorflow_tts/models/fastspeech.py:473) ]]
  (1) Invalid argument:  indices[0,2106] = 2107 is not in [0, 2049)
	 [[node decoder/position_embeddings/embedding_lookup (defined at /app/TensorflowTTS/tensorflow_tts/models/fastspeech.py:473) ]]
	 [[decoder/position_embeddings/embedding_lookup/_128]]
0 successful operations.
0 derived errors ignored. [Op:__inference__inference_9245]

Errors may have originated from an input operation.
Input Source operations connected to node decoder/position_embeddings/embedding_lookup:
 mul_3 (defined at /app/TensorflowTTS/tensorflow_tts/models/fastspeech2.py:274)	
 decoder/position_embeddings/embedding_lookup/8118 (defined at /usr/lib/python3.6/contextlib.py:81)

Input Source operations connected to node decoder/position_embeddings/embedding_lookup:
 mul_3 (defined at /app/TensorflowTTS/tensorflow_tts/models/fastspeech2.py:274)	
 decoder/position_embeddings/embedding_lookup/8118 (defined at /usr/lib/python3.6/contextlib.py:81)

Function call stack:
_inference -> _inference

and the length of my input is way below 2048.

**Comment by dathudeptrai** [comment]
@marzieh-razavi can you check the value of each element in your input ?

**Comment by marzieh-razavi** [comment]
Yes, here is the id of each element in the input (the inputs are phonemes), and the number of phonemes in the sentence is 285.
[134, 70, 120, 116, 145, 141, 104, 78, 130, 116, 78, 117, 108, 120, 82, 97, 131, 98, 143, 73, 131, 131, 116, 94, 115, 136, 117, 108, 120, 148, 106, 82, 116, 137, 90, 86, 106, 94, 117, 129, 145, 141, 148, 116, 137, 90, 145, 141, 105, 109, 143, 118, 113, 145, 78, 130, 104, 123, 119, 119, 74, 118, 88, 97, 148, 104, 78, 130, 130, 112, 133, 130, 113, 143, 108, 120, 145, 78, 130, 145, 141, 146, 97, 129, 130, 123, 104, 87, 117, 148, 109, 146, 145, 78, 130, 116, 66, 130, 88, 113, 94, 118, 90, 74, 88, 73, 117, 145, 141, 94, 118, 104, 86, 143, 148, 74, 143, 133, 144, 94, 119, 133, 112, 133, 94, 119, 148, 91, 94, 130, 109, 146, 70, 119, 73, 143, 102, 117, 73, 88, 73, 117, 131, 117, 66, 133, 66, 119, 144, 94, 119, 146, 90, 112, 119, 86, 119, 108, 119, 91, 73, 118, 78, 130, 119, 108, 120, 148, 144, 109, 117, 91, 70, 133, 144, 98, 116, 148, 86, 106, 70, 143, 70, 119, 73, 143, 102, 117, 73, 88, 73, 117, 73, 129, 127, 119, 133, 118, 73, 119, 133, 148, 66, 119, 104, 130, 86, 90, 112, 144, 74, 119, 108, 119, 91, 73, 71, 104, 133, 97, 119, 141, 119, 148, 144, 137, 90, 91, 70, 133, 104, 109, 133, 145, 78, 130, 131, 116, 94, 115, 136, 117, 148, 91, 94, 130, 109, 146, 70, 119, 73, 143, 102, 117, 73, 88, 73, 117, 131, 117, 66, 133, 66, 119, 144, 94, 119, 146, 90, 112, 133, 94, 119, 108, 119, 91, 73, 118, 78, 130, 119, 108, 120, 148, 149]

**Comment by dathudeptrai** [comment]
@marzieh-razavi can you inference by the `_inference` function and print the shape of `length_regulator_outputs` in here (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/models/fastspeech.py#L817)

**Comment by marzieh-razavi** [comment]
the shape of length_regulator_outputs is (1,10,384)

**Comment by dathudeptrai** [comment]
> the shape of length_regulator_outputs is (1,10,384)

1, 10, 384 is the shape of dummy input in `_build()` function. I need you pass ur input in above comment and print a shape again :D

**Comment by marzieh-razavi** [comment]
Sorry, I had put the print in the wrong place, the shape is (1, 2188, 384).

**Comment by dathudeptrai** [comment]
> Sorry, I had put the print in the wrong place, the shape is (1, 2188, 384). so I guess this is causing the issue.

yes :)), 2048 is maximum, you can adjust it in the config file :))). replace 2048 to 10000 for example :D.

**Comment by dathudeptrai** [comment]
the root of this problem is already know, i will close.

**Comment by avraamya** [comment]
i have same issue, i want to use large text with fastspeech, where exactly i need to make change in order to make in work? i try to change some paremater in configs files, but it not working for me. which file and which paremeter exactly i need to change?

mels, audios = do_synthesis(input_text, fastspeech, mb_melgan, "FASTSPEECH", "MB-MELGAN")

but i got error:

InvalidArgumentError:  indices[0,2048] = 2049 is not in [0, 2049)
	 [[node decoder/position_embeddings/Gather
 (defined at /usr/local/lib/python3.7/dist-packages/tensorflow_tts/models/fastspeech.py:76)
]] [Op:__inference__inference_63215]

Errors may have originated from an input operation.
Input Source operations connected to node decoder/position_embeddings/Gather:
In[0] decoder/position_embeddings/Gather/resource:	
In[1] mul_1 (defined at /usr/local/lib/python3.7/dist-packages/tensorflow_tts/models/fastspeech.py:872)
