### ISSUE TITLE
TensorflowTTS fastspeech training error.

### ISSUE THREAD

**Issue by mataym** [TensorSpeech/TensorFlowTTS#151]
After preprocessing, I ran the model training script, but the following error occurred:

2020-07-26 21:24:27,175 (train_fastspeech:340) INFO: hop_size = 256
2020-07-26 21:24:27,176 (train_fastspeech:340) INFO: format = npy
2020-07-26 21:24:27,176 (train_fastspeech:340) INFO: fastspeech_params = {'n_speakers': 1, 'encoder_hidden_size': 384, 'encoder_num_hidden_layers': 4, 'encoder_num_attention_heads': 2, 'encoder_attention_head_size': 192, 'encoder_intermediate_size': 1024, 'encoder_intermediate_kernel_size': 3, 'encoder_hidden_act': 'mish', 'decoder_hidden_size': 384, 'decoder_num_hidden_layers': 4, 'decoder_num_attention_heads': 2, 'decoder_attention_head_size': 192, 'decoder_intermediate_size': 1024, 'decoder_intermediate_kernel_size': 3, 'decoder_hidden_act': 'mish', 'num_duration_conv_layers': 2, 'duration_predictor_filters': 256, 'duration_predictor_kernel_sizes': 3, 'num_mels': 80, 'hidden_dropout_prob': 0.1, 'attention_probs_dropout_prob': 0.1, 'duration_predictor_dropout_probs': 0.1, 'max_position_embeddings': 2048, 'initializer_range': 0.02, 'output_attentions': False, 'output_hidden_states': False}
2020-07-26 21:24:27,176 (train_fastspeech:340) INFO: batch_size = 16
2020-07-26 21:24:27,176 (train_fastspeech:340) INFO: remove_short_samples = True
2020-07-26 21:24:27,176 (train_fastspeech:340) INFO: allow_cache = True
2020-07-26 21:24:27,176 (train_fastspeech:340) INFO: mel_length_threshold = 32
2020-07-26 21:24:27,176 (train_fastspeech:340) INFO: is_shuffle = True
2020-07-26 21:24:27,176 (train_fastspeech:340) INFO: optimizer_params = {'initial_learning_rate': 0.001, 'end_learning_rate': 5e-05, 'decay_steps': 150000, 'warmup_proportion': 0.02, 'weight_decay': 0.001}
2020-07-26 21:24:27,176 (train_fastspeech:340) INFO: train_max_steps = 200000
2020-07-26 21:24:27,176 (train_fastspeech:340) INFO: save_interval_steps = 5000
2020-07-26 21:24:27,176 (train_fastspeech:340) INFO: eval_interval_steps = 500
2020-07-26 21:24:27,176 (train_fastspeech:340) INFO: log_interval_steps = 200
2020-07-26 21:24:27,176 (train_fastspeech:340) INFO: num_save_intermediate_results = 1
2020-07-26 21:24:27,177 (train_fastspeech:340) INFO: train_dir = dump/train/
2020-07-26 21:24:27,177 (train_fastspeech:340) INFO: dev_dir = dump/valid/
2020-07-26 21:24:27,177 (train_fastspeech:340) INFO: use_norm = True
2020-07-26 21:24:27,177 (train_fastspeech:340) INFO: outdir = examples/fastspeech/exp/train.fastspeech.v1/
2020-07-26 21:24:27,177 (train_fastspeech:340) INFO: config = examples/fastspeech/conf/fastspeech.v1.yaml
2020-07-26 21:24:27,177 (train_fastspeech:340) INFO: resume = 
2020-07-26 21:24:27,177 (train_fastspeech:340) INFO: verbose = 1
2020-07-26 21:24:27,177 (train_fastspeech:340) INFO: mixed_precision = False
2020-07-26 21:24:27,177 (train_fastspeech:340) INFO: version = 0.6.1
2020-07-26 21:24:31,370 (fastspeech_dataset:74) WARNING: Some files are filtered by mel length threshold (4635 -> 4634).
Traceback (most recent call last):
  File "examples/fastspeech/train_fastspeech.py", line 439, in <module>
    main()
  File "examples/fastspeech/train_fastspeech.py", line 368, in main
    return_utt_id=False
  File "./examples/fastspeech/fastspeech_dataset.py", line 79, in __init__
    duration_files = [duration_files[idx] for idx in idxs]
  File "./examples/fastspeech/fastspeech_dataset.py", line 79, in <listcomp>
    duration_files = [duration_files[idx] for idx in idxs]
IndexError: list index out of range

How should this mistake be solved? Thank you for your advice！

**Comment by ZDisket** [comment]
Did you extract durations?

**Comment by mataym** [comment]
> Did you extract durations?

no, i just do preprocessing, and then ran the training script.  Is it necessary to extract the duration before training?

**Comment by ZDisket** [comment]
@mataym For FastSpeech and FastSpeech2 yes, it's necessary. You can either train a Tacotron 2 model first and use that or Montreal Forced Aligner.

**Comment by mataym** [comment]
> Did you extract durations?
how do i extract durations? can u give me some instructions or give me a link ? thank advanced!

**Comment by ZDisket** [comment]
@mataym See https://github.com/ZDisket/TensorflowTTS/tree/master/examples/fastspeech2/mfa

**Comment by mataym** [comment]
> Did you extract durations?

i have already created teh durations folder with MFA, but occurred following erro!
tensorflow-tts-preprocess --rootdir tensorflow_tts/datasets/ --outdir ./dump/ --conf preprocess/ljspeech_preprocess.yaml
(tensorflowtts) [speechlab@localhost TensorflowTTS]$ tensorflow-tts-preprocess --rootdir tensorflow_tts/datasets/ --outdir ./dump/ --conf preprocess/ljspeech_preprocess.yaml
Traceback (most recent call last):
  File "/home/speechlab/anaconda3/envs/tensorflowtts/bin/tensorflow-tts-preprocess", line 8, in <module>
    sys.exit(main())
  File "/home/speechlab/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow_tts/bin/preprocess.py", line 174, in main
    utt_ids = processor.get_one_sample(idx)["utt_id"]
  File "/home/speechlab/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow_tts/processor/ljspeech.py", line 149, in get_one_sample
    text_ids = np.asarray(self.text_to_sequence(text), np.int32)
  File "/home/speechlab/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow_tts/processor/ljspeech.py", line 175, in text_to_sequence
    _clean_text(m.group(1), self.cleaner_names)
  File "/home/speechlab/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow_tts/processor/ljspeech.py", line 184, in _clean_text
    cleaner = getattr(cleaners, name)
AttributeError: module 'tensorflow_tts.utils.cleaners' has no attribute 't'

i defined the cleaner is 'transliteration_cleaners', if i define cleaner='transliteration_cleaners', the error is :+1: AttributeError: module 'tensorflow_tts.utils.cleaners' has no attribute 'e'
How can I solve this problem?

**Comment by dathudeptrai** [comment]
@mataym replace _clean_text(m.group(1), self.cleaner_names) -> _clean_text(m.group(1), [self.cleaner_names])

**Comment by mataym** [comment]
> @mataym replace _clean_text(m.group(1), self.cleaner_names) -> _clean_text(m.group(1), [self.cleaner_names]). Or try to pull newest code.

thank you so much ,it works. and when i train the model , another error is occurred as following:
2020-08-10 14:21:29.439049: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
Traceback (most recent call last):
  File "examples/fastspeech2/train_fastspeech2.py", line 38, in <module>
    from examples.fastspeech.train_fastspeech import FastSpeechTrainer
  File "./examples/fastspeech/train_fastspeech.py", line 39, in <module>
    from tensorflow_tts.utils import (calculate_2d_loss, calculate_3d_loss,
ImportError: cannot import name 'calculate_2d_loss' from 'tensorflow_tts.utils' (/home/speechlab/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow_tts/utils/__init__.py)
i already pulled the new source code, and the TensoflowTTS==0.7. what is the problem with is?thanks a lot

**Comment by dathudeptrai** [comment]
@mataym calculate_2d_loss is on tensorflow_tts.utils here (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/utils/__init__.py#L11). I think there is something wrong, can you git pull then:
```
pip install -e .
```

**Comment by mataym** [comment]
> @mataym For MFA see https://github.com/ZDisket/TensorflowTTS/tree/master/examples/fastspeech2/mfa
> For durations from Tacotron 2 model see https://github.com/dathudeptrai/TensorflowTTS/tree/master/examples/tacotron2#step-4-extract-duration-from-alignments-for-fastspeech
> By the way, you should train FastSpeech2.

hello, when i ran the MFA aligner script there is an error occurred as follows:
[test@localhost TensorflowTTS]$ ./montreal-forced-aligner/bin/mfa_align .datasets/wavs ./montreal-forced-aligner/pretrained_models/mylatin-lexican.txt ./montreal-forced-aligner/pretrained_models/my_g2p_model.zip ./TextGrids -j 8
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 2158.0
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 224, in <module>
  File "aligner/command_line/align.py", line 181, in validate_args
  File "aligner/command_line/align.py", line 120, in align_corpus
  File "aligner/models.py", line 148, in validate
  File "aligner/models.py", line 108, in meta
KeyError: 'features'
[29649] Failed to execute script align
how can i solve this problem? thanks

**Comment by dathudeptrai** [comment]
@mataym we just commit the PR multi-speaker with MFA in (https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/fastspeech2_multispeaker) and (https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/mfa_extraction), pls refer the instruction and modify to work in ur case.

**Comment by dathudeptrai** [comment]
close because inactivity, fell free to re-open or create new issue.
