### ISSUE TITLE
Tactron2 training error

### ISSUE THREAD

**Issue by mataym** [TensorSpeech/TensorFlowTTS#152]
when i tried to run tacotron2 in tensorflowtts with training script , the error occurred  as follows:
CUDA_VISIBLE_DEVICES=1 python examples/tacotron2/train_tacotron2.py \
>   --train-dir ./dump/train/ \
>   --dev-dir ./dump/valid/ \
>   --outdir ./examples/tacotron2/exp/train.tacotron2.v1/ \
>   --config ./examples/tacotron2/conf/tacotron2.v1.yaml \
>   --use-norm 1 \
>   --mixed_precision 0 \
>   --resume ""
2020-07-26 23:44:19,431 (tacotron_dataset:106) WARNING: Some files are filtered by mel length threshold (4635 -> 4634).
2020-07-26 23:44:19,527 (train_tacotron2:519) INFO: hop_size = 256
2020-07-26 23:44:19,541 (train_tacotron2:519) INFO: format = npy
2020-07-26 23:44:19,541 (train_tacotron2:519) INFO: tacotron2_params = {'embedding_hidden_size': 512, 'initializer_range': 0.02, 'embedding_dropout_prob': 0.1, 'n_speakers': 1, 'n_conv_encoder': 5, 'encoder_conv_filters': 512, 'encoder_conv_kernel_sizes': 5, 'encoder_conv_activation': 'relu', 'encoder_conv_dropout_rate': 0.5, 'encoder_lstm_units': 256, 'n_prenet_layers': 2, 'prenet_units': 256, 'prenet_activation': 'relu', 'prenet_dropout_rate': 0.5, 'n_lstm_decoder': 1, 'reduction_factor': 1, 'decoder_lstm_units': 1024, 'attention_dim': 128, 'attention_filters': 32, 'attention_kernel': 31, 'n_mels': 80, 'n_conv_postnet': 5, 'postnet_conv_filters': 512, 'postnet_conv_kernel_sizes': 5, 'postnet_dropout_rate': 0.1, 'attention_type': 'lsa'}
2020-07-26 23:44:19,541 (train_tacotron2:519) INFO: batch_size = 8
2020-07-26 23:44:19,541 (train_tacotron2:519) INFO: remove_short_samples = True
2020-07-26 23:44:19,541 (train_tacotron2:519) INFO: allow_cache = True
2020-07-26 23:44:19,541 (train_tacotron2:519) INFO: mel_length_threshold = 32
2020-07-26 23:44:19,541 (train_tacotron2:519) INFO: is_shuffle = True
2020-07-26 23:44:19,541 (train_tacotron2:519) INFO: use_fixed_shapes = True
2020-07-26 23:44:19,541 (train_tacotron2:519) INFO: optimizer_params = {'initial_learning_rate': 0.001, 'end_learning_rate': 1e-05, 'decay_steps': 150000, 'warmup_proportion': 0.02, 'weight_decay': 0.001}
2020-07-26 23:44:19,541 (train_tacotron2:519) INFO: train_max_steps = 200000
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: save_interval_steps = 5000
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: eval_interval_steps = 500
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: log_interval_steps = 100
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: start_schedule_teacher_forcing = 200001
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: start_ratio_value = 0.5
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: schedule_decay_steps = 50000
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: end_ratio_value = 0.0
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: num_save_intermediate_results = 1
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: train_dir = ./dump/train/
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: dev_dir = ./dump/valid/
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: use_norm = True
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: outdir = ./examples/tacotron2/exp/train.tacotron2.v1/
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: config = ./examples/tacotron2/conf/tacotron2.v1.yaml
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: resume = 
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: verbose = 1
2020-07-26 23:44:19,542 (train_tacotron2:519) INFO: mixed_precision = False
2020-07-26 23:44:19,543 (train_tacotron2:519) INFO: version = 0.6.1
2020-07-26 23:44:19,543 (train_tacotron2:519) INFO: max_mel_length = 4993
2020-07-26 23:44:19,543 (train_tacotron2:519) INFO: max_char_length = 1046
2020-07-26 23:44:19.552734: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-26 23:44:22.851045: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:31:00.0 name: Tesla V100-PCIE-16GB computeCapability: 7.0
coreClock: 1.38GHz coreCount: 80 deviceMemorySize: 15.75GiB deviceMemoryBandwidth: 836.37GiB/s
2020-07-26 23:44:22.852237: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-26 23:44:22.856415: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-26 23:44:22.862528: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-26 23:44:22.865479: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-26 23:44:22.869715: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-26 23:44:22.876695: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-26 23:44:22.893111: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-26 23:44:22.906151: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-07-26 23:44:22.907967: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-26 23:44:22.949301: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2399950000 Hz
2020-07-26 23:44:22.951750: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55af3bd98fa0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-26 23:44:22.951823: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-26 23:44:23.752781: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55af3be03160 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-07-26 23:44:23.752844: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-PCIE-16GB, Compute Capability 7.0
2020-07-26 23:44:23.755583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:31:00.0 name: Tesla V100-PCIE-16GB computeCapability: 7.0
coreClock: 1.38GHz coreCount: 80 deviceMemorySize: 15.75GiB deviceMemoryBandwidth: 836.37GiB/s
2020-07-26 23:44:23.755703: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-26 23:44:23.755748: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-26 23:44:23.755789: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-26 23:44:23.755828: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-26 23:44:23.755867: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-26 23:44:23.755909: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-26 23:44:23.755952: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-26 23:44:23.760967: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-07-26 23:44:23.761050: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-26 23:44:23.764953: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-26 23:44:23.765015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-07-26 23:44:23.765047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-07-26 23:44:23.780519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14864 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-16GB, pci bus id: 0000:31:00.0, compute capability: 7.0)
2020-07-26 23:45:12.398414: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-26 23:45:13.265096: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
Model: "tacotron2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
encoder (TFTacotronEncoder)  multiple                  8218624   
_________________________________________________________________
decoder_cell (TFTacotronDeco multiple                  18246402  
_________________________________________________________________
post_net (TFTacotronPostnet) multiple                  5460480   
_________________________________________________________________
residual_projection (Dense)  multiple                  41040     
=================================================================
Total params: 31,966,546
Trainable params: 31,956,306
Non-trainable params: 10,240
_________________________________________________________________
[train]:   0%|                                                                                          | 0/200000 [00:00<?, ?it/s]2020-07-26 23:45:30.303066: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:184] Filling up shuffle buffer (this may take a while): 1380 of 4634
2020-07-26 23:45:40.302328: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:184] Filling up shuffle buffer (this may take a while): 2579 of 4634
2020-07-26 23:45:50.312557: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:184] Filling up shuffle buffer (this may take a while): 3811 of 4634
2020-07-26 23:45:56.814676: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:233] Shuffle buffer filled.
2020-07-26 23:46:21.850923: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:563] function_optimizer failed: Invalid argument: Node 'tacotron2/StatefulPartitionedCall/encoder/bilstm/forward_lstm/StatefulPartitionedCall_Func/tacotron2/StatefulPartitionedCall/output/_325': Connecting to invalid output 29 of source node tacotron2/StatefulPartitionedCall/encoder/bilstm/forward_lstm/StatefulPartitionedCall which has 29 outputs.
2020-07-26 23:46:23.085845: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:563] shape_optimizer failed: Out of range: src_output = 29, but num_outputs is only 29
2020-07-26 23:46:23.849460: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:563] layout failed: Out of range: src_output = 29, but num_outputs is only 29
Traceback (most recent call last):
  File "examples/tacotron2/train_tacotron2.py", line 594, in <module>
    main()
  File "examples/tacotron2/train_tacotron2.py", line 586, in main
    resume=args.resume,
  File "examples/tacotron2/train_tacotron2.py", line 392, in fit
    self.run()
  File "/home/speechlab/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 67, in run
    self._train_epoch()
  File "/home/speechlab/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 89, in _train_epoch
    self._train_step(batch)
  File "examples/tacotron2/train_tacotron2.py", line 117, in _train_step
    charactor, char_length, mel, mel_length, guided_attention
  File "/home/speechlab/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/speechlab/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 644, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/speechlab/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/speechlab/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/home/speechlab/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/speechlab/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/home/speechlab/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [8,2000,80] vs. [8,4993,80]
	 [[node mean_absolute_error/sub (defined at examples/tacotron2/train_tacotron2.py:157) ]] [Op:__inference__one_step_tacotron2_164180]

Errors may have originated from an input operation.
Input Source operations connected to node mean_absolute_error/sub:
 mel (defined at examples/tacotron2/train_tacotron2.py:117)	
 tacotron2/StatefulPartitionedCall (defined at examples/tacotron2/train_tacotron2.py:142)

Function call stack:
_one_step_tacotron2

[train]:   0%|                                                                                          | 0/200000 [01:32<?, ?it/s]

how do i solve this problem? can you give me some instruction please? thanks!

**Comment by dathudeptrai** [comment]
@mataym hi, tacotron-2 model support maximum decoder step is 2000 (https://github.com/TensorSpeech/TensorflowTTS/blob/master/tensorflow_tts/models/tacotron2.py#L767). But in ur samples, there is a sample has length = 4993 (this is very very long sentence). You can solve that by change 2000 to 5000 in the tacotron-2 model but i bet with you that the training will OOM :v.

**Comment by mataym** [comment]
> @mataym hi, tacotron-2 model support maximum decoder step is 2000 (https://github.com/TensorSpeech/TensorflowTTS/blob/master/tensorflow_tts/models/tacotron2.py#L767). But in ur samples, there is a sample has length = 4993 (this is very very long sentence). You can solve that by change 2000 to 5000 in the tacotron-2 model but i bet with you that the training will OOM :v.

Thank you, as you said, I set maximum-iterations to 5000, and I deleted all audio files longer than 25 seconds, but as you said, there was still OOM occurred. How should I deal with this problem? Please give me some advice, thank you!

**Comment by dathudeptrai** [comment]
@mataym the maximum mel length of training data should be < 1000. I suggest you move all mel file > 1000 frame to valid directory.

**Comment by dathudeptrai** [comment]
close because inactivity, fell free to re-open or create new issue.

**Comment by GavinStein1** [comment]
Hi there, this issue is occuring for me. I was wondering how I can check our sample lengths to find what our max is in our dataset?

**Comment by dathudeptrai** [comment]
> Hi there, this issue is occuring for me. I was wondering how I can check our sample lengths to find what our max is in our dataset?

just load all mel-spectrogram and check its length.
