### ISSUE TITLE
Problems with MFA

### ISSUE THREAD

**Issue by adfost** [TensorSpeech/TensorFlowTTS#156]
After running mfa and preprocessing as shown, I try to train FastSpeech, and I get the following error

Traceback (most recent call last):
  File "examples/fastspeech/train_fastspeech.py", line 379, in <module>
    main()
  File "examples/fastspeech/train_fastspeech.py", line 371, in main
    resume=args.resume,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 852, in fit
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 101, in run
    self._train_epoch()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 123, in _train_epoch
    self._train_step(batch)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 666, in _train_step
    self.one_step_forward(batch)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Incompatible shapes: [51] vs. [47]
	 [[{{node tf_fast_speech/length_regulator/while/body/_1/tf_fast_speech/length_regulator/while/Repeat/BroadcastTo}}]]
	 [[tf_fast_speech/length_regulator/while/LoopCond/_50/_134]]
  (1) Invalid argument:  Incompatible shapes: [51] vs. [47]
	 [[{{node tf_fast_speech/length_regulator/while/body/_1/tf_fast_speech/length_regulator/while/Repeat/BroadcastTo}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference__one_step_forward_24493]

Function call stack:
_one_step_forward -> _one_step_forward

**Comment by dathudeptrai** [comment]
@adfost can you check if all sum(duration) == len(Mel) ?

**Comment by adfost** [comment]
Where should I put this step?

**Comment by dathudeptrai** [comment]
you just need load each (duration, mel) pair  then calculate sum to check if sum(duration) = len(Mel)

**Comment by adfost** [comment]
Still not sure how to do it. But I think one or two files were truncated or ignored is that the cause?

**Comment by ZDisket** [comment]
@adfost Using my guide? Did you run postmfa.py too? That should've corrected the mismatches.

**Comment by adfost** [comment]
Yeah I ran postmfa.py

**Comment by adfost** [comment]
I might have made a mistake trying to get through this. I'll run it again to check.

**Comment by adfost** [comment]
Apparently the command ./montreal-forced-aligner/bin/mfa_align ./datasets/wavs ./montreal-forced-aligner/pretrained_models/librispeech-lexicon.txt ./montreal-forced-aligner/pretrained_models/english.zip ./TextGrids -j 8 isn't filling the TextGrids file

**Comment by adfost** [comment]
@dathudeptrai I tried comparing the lengths of the mel to the sum of the durations. I couldn't find an issue there. I guess it's something else. Any other ideas?

**Comment by dathudeptrai** [comment]
@adfost You should also check if all duration value is positive :))

**Comment by adfost** [comment]
@dathudeptrai  not that either, other suggestions?

**Comment by adfost** [comment]
@dathudeptrai Could I send you the data and you could try to run it? Maybe I have some other problem that is difficult to debug

**Comment by dathudeptrai** [comment]
@adfost I mean all element in each duration file must be positive :D. The sum can be positive but for each element , I'm not sure.

**Comment by adfost** [comment]
@dathudeptrai I took the absolute value and printed if there was any difference nothing was printed.

**Comment by adfost** [comment]
Can I send you the data and you take a look?

**Comment by ZDisket** [comment]
@adfost Send it to me too; I wanna know why my MFA implementation does that. Ideally upload to Google Drive.

**Comment by adfost** [comment]
@ZDisket @dathudeptrai what are your email accounts?

**Comment by ZDisket** [comment]
@adfost As for me, send it to daragor9021@gmail.com

**Comment by adfost** [comment]
@ZDisket  I shared it with you

**Comment by manmay-nakhashi** [comment]
@ZDisket @dathudeptrai i am also facing some issue with duration while extracting for non-english language with MFA 
using @ZDisket code 
```
Traceback (most recent call last):
  File "examples/fastspeech/train_fastspeech.py", line 504, in <module>
    main()
  File "examples/fastspeech/train_fastspeech.py", line 496, in main
    resume=args.resume,
  File "examples/fastspeech/train_fastspeech.py", line 304, in fit
    self.run()
  File "/mnt/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py", line 67, in run
    self._train_epoch()
  File "/mnt/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py", line 89, in _train_epoch
    self._train_step(batch)
  File "examples/fastspeech/train_fastspeech.py", line 103, in _train_step
    self._one_step_fastspeech(charactor, duration, mel)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 644, in _call
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Incompatible shapes: [16,143] vs. [16,141]
         [[node mean_squared_error/SquaredDifference (defined at examples/fastspeech/train_fastspeech.py:128) ]]
         [[tf_fast_speech/mul/_144]]
  (1) Invalid argument:  Incompatible shapes: [16,143] vs. [16,141]
         [[node mean_squared_error/SquaredDifference (defined at examples/fastspeech/train_fastspeech.py:128) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference__one_step_fastspeech_22193]

Errors may have originated from an input operation.
Input Source operations connected to node mean_squared_error/SquaredDifference:
 tf_fast_speech/duration_predictor/Squeeze (defined at /mnt/TensorflowTTS/tensorflow_tts/models/fastspeech.py:568)
 Log (defined at examples/fastspeech/train_fastspeech.py:127)

Input Source operations connected to node mean_squared_error/SquaredDifference:
 tf_fast_speech/duration_predictor/Squeeze (defined at /mnt/TensorflowTTS/tensorflow_tts/models/fastspeech.py:568)
 Log (defined at examples/fastspeech/train_fastspeech.py:127)

Function call stack:
_one_step_fastspeech -> _one_step_fastspeech

[train]:   0%|                                                                                
```

**Comment by dathudeptrai** [comment]
@manmay-nakhashi pls pull the newest code

**Comment by manmay-nakhashi** [comment]
@dathudeptrai ok

**Comment by manmay-nakhashi** [comment]
@dathudeptrai problem is still there
```
Traceback (most recent call last):
  File "examples/fastspeech/train_fastspeech.py", line 372, in <module>
    main()
  File "examples/fastspeech/train_fastspeech.py", line 364, in main
    resume=args.resume,
  File "/mnt/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py", line 852, in fit
    self.run()
  File "/mnt/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py", line 101, in run
    self._train_epoch()
  File "/mnt/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py", line 123, in _train_epoch
    self._train_step(batch)
  File "/mnt/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py", line 666, in _train_step
    self.one_step_forward(batch)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 644, in _call
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [16,143] vs. [16,134]
         [[node mean_squared_error/SquaredDifference (defined at examples/fastspeech/train_fastspeech.py:100) ]] [Op:__inference__one_step_forward_22556]

Errors may have originated from an input operation.
Input Source operations connected to node mean_squared_error/SquaredDifference:
 Log (defined at examples/fastspeech/train_fastspeech.py:97)
 tf_fast_speech/duration_predictor/Squeeze (defined at /mnt/TensorflowTTS/tensorflow_tts/models/fastspeech.py:581)

```

**Comment by dathudeptrai** [comment]
@manmay-nakhashi can you change the line at (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/fastspeech/train_fastspeech.py#L100) to:

```
duration_loss = calculate_2d_loss(log_duration, duration_outputs, self.mse)
```

It should solve ur problem but need to train to check the performance. BTW, you should trian fastspeech2 rather than fastspeech.

**Comment by manmay-nakhashi** [comment]
@dathudeptrai sure i'll give it a try on both the things

**Comment by manmay-nakhashi** [comment]
@dathudeptrai thanks it  solved this error with above change , what is the root cause of this problem i didn't understand can you tell me ?

**Comment by dathudeptrai** [comment]
@manmay-nakhashi are u training with multiple gpu ?

**Comment by manmay-nakhashi** [comment]
@dathudeptrai no, i am running with single gpu
