### ISSUE TITLE
ERROR when i train the fastspeech2

### ISSUE THREAD

**Issue by yanglu1994** [TensorSpeech/TensorFlowTTS#157]
when I run train_fastspeech2 , something is wrong.and I print the shape of [charactor, duration, f0, energy, mel]

> charactor shape is [16, 192]
duration shape is [16, 47]
f0 shape is [16, 47]
energy shape is [16, 47]
mel shape is [16, 1193, 80]

>/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2020-07-27 11:43:48.332178: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1873] Converted 1165/11843 nodes to float16 precision using 121 cast(s) to float16 (excluding Const and Variable casts)
Traceback (most recent call last):
  File "train_fastspeech2.py", line 525, in <module>
    main()
  File "train_fastspeech2.py", line 517, in main
    resume=args.resume,
  File "../fastspeech/train_fastspeech.py", line 303, in fit
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 67, in run
    self._train_epoch()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 89, in _train_epoch
    self._train_step(batch)
  File "train_fastspeech2.py", line 86, in _train_step
    self._one_step_fastspeech2(charactor, duration, f0, energy, mel)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 644, in _call
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Incompatible shapes: [16,47,384] vs. [16,192,384]
	 [[node tf_fast_speech2/add_1 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_tts/models/fastspeech2.py:177) ]]
	 [[tf_fast_speech2/mul/_154]]
  (1) Invalid argument:  Incompatible shapes: [16,47,384] vs. [16,192,384]
	 [[node tf_fast_speech2/add_1 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_tts/models/fastspeech2.py:177) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference__one_step_fastspeech2_96439]
Errors may have originated from an input operation.
Input Source operations connected to node tf_fast_speech2/add_1:
 tf_fast_speech2/encoder/layer_._3/mul (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_tts/models/fastspeech.py:380)
Input Source operations connected to node tf_fast_speech2/add_1:
 tf_fast_speech2/encoder/layer_._3/mul (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_tts/models/fastspeech.py:380)
Function call stack:
_one_step_fastspeech2 -> _one_step_fastspeech2

**Comment by dathudeptrai** [comment]
@yanglu1994 the bug tell that there is a sample that its sum(durations) != len(its Mel). Pls loop over all dataset and check.

**Comment by adfost** [comment]
I tried a similar fix, found no sample where sum(durations) != len(mel), but I have a similar problem.

**Comment by dathudeptrai** [comment]
@adfost @yanglu1994 sum(durations) == len(mel) and all element of duration must be positive.

**Comment by dathudeptrai** [comment]
close because inactivity, fell free to re-open or create new issue.

**Comment by cykao** [comment]
Sorry, I have checked sum(durations) == len(mel) and all elements of duration are positive, but still cannot fix it when I run train_fastspeech2. please let me know if there is a solution for this problem. The track issues are below and thank you in advance.


Traceback (most recent call last):
  File "examples/fastspeech2/train_fastspeech2.py", line 414, in <module>
    main()
  File "examples/fastspeech2/train_fastspeech2.py", line 406, in main
    resume=args.resume,
  File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 852, in fit
    self.run()
  File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 101, in run
    self._train_epoch()
  File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 123, in _train_epoch
    self._train_step(batch)
  File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 666, in _train_step
    self.one_step_forward(batch)
  File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 787, in __call__
    result = self._call(*args, **kwds)
  File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 847, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2929, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1920, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 561, in call
    ctx=ctx)
  File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [16,164,384] vs. [16,163,384]
         [[node gradient_tape/tf_fast_speech2/add_1/BroadcastGradientArgs (defined at /home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py:698) ]] [Op:__inference__one_step_forward_118968]

Function call stack:
_one_step_forward

[train]:   0%|

**Comment by dathudeptrai** [comment]
> Sorry, I have checked sum(durations) == len(mel) and all elements of duration are positive, but still cannot fix it when I run train_fastspeech2. please let me know if there is a solution for this problem. The track issues are below and thank you in advance.
> 
> Traceback (most recent call last):
> File "examples/fastspeech2/train_fastspeech2.py", line 414, in 
> main()
> File "examples/fastspeech2/train_fastspeech2.py", line 406, in main
> resume=args.resume,
> File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 852, in fit
> self.run()
> File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 101, in run
> self._train_epoch()
> File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 123, in _train_epoch
> self._train_step(batch)
> File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 666, in _train_step
> self.one_step_forward(batch)
> File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 787, in **call**
> result = self._call(*args, **kwds)
> File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 847, in _call
> return self._stateless_fn(*args, **kwds)
> File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2929, in **call**
> filtered_flat_args, captured_inputs=graph_function.captured_inputs) # pylint: disable=protected-access
> File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1920, in _call_flat
> ctx, args, cancellation_manager=cancellation_manager))
> File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 561, in call
> ctx=ctx)
> File "/home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
> inputs, attrs, num_outputs)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [16,164,384] vs. [16,163,384]
> [[node gradient_tape/tf_fast_speech2/add_1/BroadcastGradientArgs (defined at /home/miruware/anaconda3/envs/kao_tf2/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py:698) ]] [Op:__inference__one_step_forward_118968]
> 
> Function call stack:
> _one_step_forward

pls create new issue, ur bug is because len(durations) != len(charactor), pls check it.
