### ISSUE TITLE
Error when training TensorflowTTS 

### ISSUE THREAD

**Issue by adfost** [TensorSpeech/TensorFlowTTS#161]
I got my dataset preprocessed using MFA. However, when I try to train FastSpeech I get this:

Traceback (most recent call last):
  File "examples/fastspeech/train_fastspeech.py", line 379, in <module>
    main()
  File "examples/fastspeech/train_fastspeech.py", line 371, in main
    resume=args.resume,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 852, in fit
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 101, in run
    self._train_epoch()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 123, in _train_epoch
    self._train_step(batch)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 666, in _train_step
    self.one_step_forward(batch)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Incompatible shapes: [166] vs. [159]
	 [[{{node tf_fast_speech/length_regulator/while/body/_1/tf_fast_speech/length_regulator/while/Repeat/BroadcastTo}}]]
	 [[tf_fast_speech/length_regulator/while/loop_body_control/_75/_137]]
  (1) Invalid argument:  Incompatible shapes: [166] vs. [159]
	 [[{{node tf_fast_speech/length_regulator/while/body/_1/tf_fast_speech/length_regulator/while/Repeat/BroadcastTo}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference__one_step_forward_24493]

Function call stack:
_one_step_forward -> _one_step_forward

**Comment by dathudeptrai** [comment]
@adfost all the problems about the mismatch between mel_predict and mel_gts should come from durations where sum(durations) != len(meals) or there is a duration file that its element is a negative value.

**Comment by adfost** [comment]
Any other possible sources of this error? I haven't found the error as either of these.

**Comment by dathudeptrai** [comment]
@adfost no, i can't find other possible reasons. Everything bug about mismatch length comes from durations.

**Comment by AnitaLiu98** [comment]
Have you solved this problem?

**Comment by hccho2** [comment]
When running only on cpu, I got this error.

**Comment by wxyhv** [comment]
Have you solved this problem?
