### ISSUE TITLE
Resample audio dataset

### ISSUE THREAD

**Issue by mapledxf** [TensorSpeech/TensorflowTTS#165]
How can I train on a resampled LJSpeech dataset?

I have convert all audios' sample rate to 24000 by using sox, and changed sampling_rate to 24000 in the config file.

Then I run
```
tensorflow-tts-preprocess --dataset ljspeech --n_cpus 16 --rootdir /data/LJSpeech-1.1 --outdir ./dump/ --conf preprocess/ljspeech_preprocess.yaml
```

I got the following error:

Traceback (most recent call last):
  File "/home/xfding/miniconda3/envs/tf2/bin/tensorflow-tts-preprocess", line 8, in <module>
    sys.exit(preprocess())
  File "/home/xfding/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_tts/bin/preprocess.py", line 320, in preprocess
    scaler_f0.partial_fit(f0[f0 != 0].reshape(-1, 1))
  File "/home/xfding/miniconda3/envs/tf2/lib/python3.6/site-packages/sklearn/preprocessing/_data.py", line 698, in partial_fit
    force_all_finite='allow-nan')
  File "/home/xfding/miniconda3/envs/tf2/lib/python3.6/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/xfding/miniconda3/envs/tf2/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/xfding/miniconda3/envs/tf2/lib/python3.6/site-packages/sklearn/utils/validation.py", line 654, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required by StandardScaler.

**Comment by dathudeptrai** [comment]
@mapledxf the bug tell that there is an array with 0 samples. Pls check the f0 return here https://github.com/TensorSpeech/TensorflowTTS/blob/master/tensorflow_tts/bin/preprocess.py#L407.

**Comment by mapledxf** [comment]
@dathudeptrai  yeah. there is a audio's f0 is all 0s after remove_outlier. How is that happen?

**Comment by dathudeptrai** [comment]
@mapledxf maybe you need to print and check by yourself in this case. remove_outlier can't make audio's F0 is all 0s.

**Comment by mapledxf** [comment]
alright, i will try to figure it out. thx for help

**Comment by Zak-SA** [comment]
I am having the same issue, any suggestions how to solve it?
Thanks

**Comment by dathudeptrai** [comment]
@Zak-SA https://github.com/TensorSpeech/TensorFlowTTS/issues/170

**Comment by Zak-SA** [comment]
Thanks
