### ISSUE TITLE
android demo无法运行

### ISSUE THREAD

**Issue by jiayue198509** [TensorSpeech/TensorFlowTTS#166]
andorid demo运行如下error，与不支持OP，是否有解决方案。
Failed to run on the given Interpreter: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
    Node number 456 (FlexRandomUniform) failed to prepare

**Comment by dathudeptrai** [comment]
@jiayue198509 i think you need install tflite nightly to make sure it work. If you install tflite before, you need delete tflite-nightly version in ur cache dir then re-run the app :)). @mapledxf can you help him.

**Comment by mapledxf** [comment]
@jiayue198509 did u make any change on the android code?

**Comment by mapledxf** [comment]
确认一下 的gradle里是不是用的 nightly版本

**Comment by jiayue198509** [comment]
clean后这个异常已经没有了，但是提示如下error:
   Process: com.tensorspeech.tensorflowtts, PID: 23124
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/comparisons.cc:53 input1->type != input2->type (INT64 != FLOAT32)
    Node number 457 (GREATER_EQUAL) failed to prepare.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:158)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:347)
        at com.tensorspeech.tensorflowtts.module.FastSpeech2.getMelSpectrogram(FastSpeech2.java:72)
        at com.tensorspeech.tensorflowtts.MainActivity.lambda$null$0$MainActivity(MainActivity.java:53)
        at com.tensorspeech.tensorflowtts.-$$Lambda$MainActivity$nkDK465A1eATUz9NHP2nNUaxJjg.run(Unknown Source:4)

**Comment by jiayue198509** [comment]
demo代码没有任何修改

**Comment by jiayue198509** [comment]
> @jiayue198509 did u make any change on the android code?
demo代码没有任何修改

**Comment by mapledxf** [comment]
应该是你的inputtext有问题

**Comment by mapledxf** [comment]
you can checkout my new PR which will fix some bugs and support long sentance.

**Comment by jiayue198509** [comment]
> you can checkout my new PR which will fix some bugs and support long sentance.

已经更新到最新的代码，还是上面的error，log看像是输入类型有问题。或者您有编译好的可运行的apk，能否提供一下。十分感谢！
java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/comparisons.cc:53 input1->type != input2->type (INT64 != FLOAT32)
Node number 457 (GREATER_EQUAL) failed to prepare.

    at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
    at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:158)
    at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:347)
    at com.tensorspeech.tensorflowtts.module.FastSpeech2.getMelSpectrogram(FastSpeech2.java:72)
    at com.tensorspeech.tensorflowtts.MainActivity.lambda$null$0$MainActivity(MainActivity.java:53)

**Comment by jiayue198509** [comment]
已经解决，lib问题，感谢！

**Comment by mapledxf** [comment]
@jiayue198509 Could u plz close this issue?

**Comment by Zhangyabing8** [comment]
@jiayue198509 ，可以分享下解决如何解决lib问题的么？ 谢谢！
我也遇到了同样的问题

**Comment by mapledxf** [comment]
把Android里tflite的版本号 改成2.3.0试试
