### ISSUE TITLE
Inference error - Fastspeech2 + MB MelGAN

### ISSUE THREAD

**Issue by kau1992** [TensorSpeech/TensorFlowTTS#238]
I got below error when run End-to-End Examples (inference).

Traceback (most recent call last):
  File "inference.py", line 15, in <module>
    pretrained_path="./examples/fastspeech2/exp/train.fastspeech2.v1/checkpoints/model-200000.h5"
  File "/home/t3610n2/TensorFlowTTS/tensorflow_tts/inference/auto_model.py", line 69, in from_pretrained
    model.load_weights(pretrained_path)
  File "/home/t3610n2/.local/share/virtualenvs/t3610n2-dfv-LYjt/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2211, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/home/t3610n2/.local/share/virtualenvs/t3610n2-dfv-LYjt/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 708, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/t3610n2/.local/share/virtualenvs/t3610n2-dfv-LYjt/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/t3610n2/.local/share/virtualenvs/t3610n2-dfv-LYjt/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3576, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype(x)))
  File "/home/t3610n2/.local/share/virtualenvs/t3610n2-dfv-LYjt/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 858, in assign
    self._shape.assert_is_compatible_with(value_tensor.shape)
  File "/home/t3610n2/.local/share/virtualenvs/t3610n2-dfv-LYjt/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1134, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (153, 384) and (149, 384) are incompatible

Fastspeech-2  200K steps   +  MB MelGAN  1200K steps

Thanks in advance

**Comment by dathudeptrai** [comment]
@kau1992 can you check ur "dataset" paramter in config ?. See the code here (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/configs/fastspeech.py#L89-L98). Seem there is a mismatch between training config and inference :)). 149 is len(ljspeech_symbols)
