### ISSUE TITLE
Error when transfering fastspeech2

### ISSUE THREAD

**Issue by poria-cat** [TensorSpeech/TensorFlowTTS#240]
Thank you for providing such a shocking framework, my work can be reduced a lot. 😊
I got duration data with tacotron pretrained model, when I transfering fastspeech2 with new data, I get it:
```
WARNING: Skipping loading of weights for layer duration_predictor due to mismatch in shape ((3, 384, 256) vs (3, 256, 256)).
Traceback (most recent call last):
  File "examples/fastspeech2/train_fastspeech2.py", line 419, in <module>
    main()
  File "examples/fastspeech2/train_fastspeech2.py", line 371, in main
    fastspeech.load_weights(args.pretrained, by_name=True, skip_mismatch=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 2209, in load_weights
    f, self.layers, skip_mismatch=skip_mismatch)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 759, in load_weights_from_hdf5_group_by_name
    layer, weight_values, original_keras_version, original_backend)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 403, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "<__array_function__ internals>", line 6, in transpose
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 651, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array
```

**Comment by dathudeptrai** [comment]
@poria-cat training from scratch is still ok ?

**Comment by poria-cat** [comment]
> @poria-cat training from scratch is still ok ?

Yes, I can training from scatch 🙊

**Comment by tekinek** [comment]
@poria-cat   
>> `to mismatch in shape ((3, 384, 256) vs (3, 256, 256)).`

These numbers remind me below, but not sure if they are relevant.

[fastspeech2.v1.yaml](https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/fastspeech2/conf/fastspeech2.v1.yaml):
 decoder_hidden_size: 384

[fastspeech2.v2.yaml](https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/fastspeech2/conf/fastspeech2.v2.yaml):
 decoder_hidden_size: 256

So, are you fine-tuning under fastspeech2.v2.yaml with a pretrained model that was trained under fastspeech2.v2.yaml?

**Comment by poria-cat** [comment]
> @poria-cat
> 
> > > `to mismatch in shape ((3, 384, 256) vs (3, 256, 256)).`
> 
> These numbers remind me below, but not sure if they are relevant.
> 
> [fastspeech2.v1.yaml](https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/fastspeech2/conf/fastspeech2.v1.yaml):
> decoder_hidden_size: 384
> 
> [fastspeech2.v2.yaml](https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/fastspeech2/conf/fastspeech2.v2.yaml):
> decoder_hidden_size: 256
> 
> So, are you fine-tuning under fastspeech2.v2.yaml with a pretrained model that was trained under fastspeech2.v1.yaml?

so cool😋! The reason for the problem is really that I used the v1 configuration file, thank you very much! I can close this issue✅
