### ISSUE TITLE
data loading error

### ISSUE THREAD

**Issue by unparalleled-ysj** [TensorSpeech/TensorFlowTTS#242]
Hi, when I update lasted When I pulled the latest code (two hours ago), a data loading error occurred during training fastspeech2

[train]:   0%|                                                                                                                                                                                     | 0/200000 [00:00<?, ?it/s]2020-09-01 17:49:00.134586: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1345] No whitelist ops found, nothing to do
2020-09-01 17:49:00.152257: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1345] No whitelist ops found, nothing to do
Traceback (most recent call last):
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 2102, in execution_mode
    yield
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 758, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2610, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference__load_data_100}} {{function_node __inference__load_data_100}} 0-th value returned by pyfunc_5 is int64, but expects int32
         [[{{node PyFunc_2}}]]
         [[StatefulPartitionedCall]]
         [[MultiDeviceIteratorGetNextFromShard]]
         [[RemoteCall]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/fastspeech2/train_fastspeech2.py", line 413, in <module>
    main()
  File "examples/fastspeech2/train_fastspeech2.py", line 405, in main
    resume=args.resume,
  File "/work/ysj/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py", line 852, in fit
    self.run()
  File "/work/ysj/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py", line 101, in run
    self._train_epoch()
  File "/work/ysj/TensorflowTTS/tensorflow_tts/trainers/base_trainer.py", line 121, in _train_epoch
    for train_steps_per_epoch, batch in enumerate(self.train_data_loader, 1):
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/distribute/input_lib.py", line 649, in __next__
    return self.get_next()
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/distribute/input_lib.py", line 694, in get_next
    self._iterators[i].get_next_as_list_static_shapes(new_name))
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/distribute/input_lib.py", line 1474, in get_next_as_list_static_shapes
    return self._iterator.get_next()
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py", line 581, in get_next
    result.append(self._device_iterators[i].get_next())
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 825, in get_next
    return self._next_internal()
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 764, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/root/anaconda3/envs/tts/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 2105, in execution_mode
    executor_new.wait()
  File "/root/anaconda3/envs/tts/lib/python3.7/site-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference__load_data_100}} {{function_node __inference__load_data_100}} 0-th value returned by pyfunc_5 is int64, but expects int32
         [[{{node PyFunc_2}}]]
         [[StatefulPartitionedCall]]
         [[MultiDeviceIteratorGetNextFromShard]]
         [[RemoteCall]]
2020-09-01 17:49:00.619271: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]
[train]:   0%|                                                                                                                                                                                     | 0/200000 [00:00<?, ?it/s]
(tts) [root@localhost TensorflowTTS]#

**Comment by dathudeptrai** [comment]
i think the bug come from (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/fastspeech2/fastspeech2_dataset.py#L160-L161). That mean there are some samples that duration/ids file has dtype = int64 rather than int32. I think you should iterate ur dataset and run the code above to check what sample cause this error.

**Comment by unparalleled-ysj** [comment]
@dathudeptrai Okay, but when using the original data loading method, the model can be trained correctly

**Comment by dathudeptrai** [comment]
@unparalleled-ysj did you use MFA to extract durations ?, this commit may help (https://github.com/TensorSpeech/TensorFlowTTS/commit/3fe53a21fa2e209da5743ad6794731081fb39175)

**Comment by unparalleled-ysj** [comment]
@dathudeptrai yes, I am use MFA to extract durations, this commit solve my problem , thanks again

**Comment by unparalleled-ysj** [comment]
@dathudeptrai The voice generated by the model trained with the latest code in the inference process has noise at the end, which seems to be the inaccurate removal of the padding value.

![1](https://user-images.githubusercontent.com/39238619/92061803-c656ad00-edc9-11ea-86cc-4514a1a47dfe.png)
<img width="619" alt="截屏2020-09-03 上午9 44 15" src="https://user-images.githubusercontent.com/39238619/92061956-1a619180-edca-11ea-967f-bf826af29b6a.png">

and do you have any suggestions on the problem of disorder when synthesizing speech longer than 10s?

**Comment by unparalleled-ysj** [comment]
@dathudeptrai sorry, is my duration file padding error, btw there is not need sum(duration) == len(mel) now? and any suggestions on the problem of disorder when synthesizing speech longer than 10s is appreciated

**Comment by dathudeptrai** [comment]
> @dathudeptrai sorry, is my duration file padding error, btw there is not need sum(duration) == len(mel) now? and any suggestions on the problem of disorder when synthesizing speech longer than 10s is appreciated

that is based on ur mel length in training set. As you see, ljspeech is fine, i think the dataset need some samples that its length is around 14-15s so the model can be synthesize long sentences. You can create long sample by concat on short samples or mix other datasets and training together :).

**Comment by unparalleled-ysj** [comment]
okay, thanks
