### ISSUE TITLE
Errow while preprocessing ljspeech

### ISSUE THREAD

**Issue by luis-vera** [TensorSpeech/TensorFlowTTS#286]
Hi. While I preprocessing ljspeech dataset I found this error in Runtime:

2020-09-30 21:19:38,814 (preprocess:364) INFO: Selected 'ljspeech' processor.
2020-09-30 21:19:38,967 (preprocess:403) INFO: Training items: 12444
2020-09-30 21:19:38,968 (preprocess:404) INFO: Validation items: 655
[Preprocessing train]:   0%|                                          | 0/12444 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\tensorflow-tts-preprocess.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\tensorflow_tts\bin\preprocess.py", line 437, in preprocess
    for result, mel, energy, f0, features in train_map:
  File "c:\python38\lib\multiprocessing\pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "c:\python38\lib\multiprocessing\pool.py", line 865, in next
    raise value
RuntimeError: Error opening 'ljspeech\\wavs\\LJ047-0222.wav': System error.

Do you know why this error appears?

Thanks a lot.
Luis

**Comment by dathudeptrai** [comment]
@luis-vera did you resolve ur problem ?, seem it's not related to the code but related to ur permission in ur server :D .

**Comment by luis-vera** [comment]
I couldn't resolved it. 

My question is why the problem happens with a especific file from a dataset. If I quit that file the error persists but in another file.  I was worked in my local PC. 

I tried the same code in Google Colab and I found the same error. After, I changed the dataset to libriTTS and I found the same error but in the first file.

RuntimeError: Error opening 'LibriTTS\\speaker1/libri1.wav': System error.

Therefore I think the problem is not in the environment nor in the used dataset but I don't know where.

Thanks a lot if you could help me.

**Comment by luis-vera** [comment]
Hi. I did another tries I could resolve the problem. Thanks
