### ISSUE TITLE
Not found any mels files in dump/train/.

### ISSUE THREAD

**Issue by Nistrian** [TensorSpeech/TensorFlowTTS#287]
Hello! I am trying to run fastspeech2 using a Russian dataset. I am getting the following error:

`СUDA_VISIBLE_DEVICES=0 python examples/fastspeech2/train_fastspeech2.py   --train-dir ../dump/train/   --dev-dir ../dump/valid/   --outdir fastspeech2/exp/train.fastspeech2.v1/   --config ./examples/fastspeech2/conf/fastspeech2.v1.yaml   --use-norm 1   --f0-stat ../dump/stats_f0.npy   --energy-stat ../dump/stats_energy.npy   --mixed_precision 1   --resume ""`

2020-10-01 17:19:47.962013: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-10-01 17:19:48.957044: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-10-01 17:19:50.234488: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-01 17:19:50.235036: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:41:00.0 name: GeForce RTX 2080 computeCapability: 7.5
coreClock: 1.71GHz coreCount: 46 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.23GiB/s
2020-10-01 17:19:50.235060: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-10-01 17:19:50.237073: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-10-01 17:19:50.237996: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-10-01 17:19:50.238193: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-10-01 17:19:50.239872: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-10-01 17:19:50.240259: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-10-01 17:19:50.240343: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-10-01 17:19:50.240437: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-01 17:19:50.240894: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-01 17:19:50.241267: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-10-01 17:19:51,851 (train_fastspeech2:300) INFO: hop_size = 256
2020-10-01 17:19:51,851 (train_fastspeech2:300) INFO: format = npy
2020-10-01 17:19:51,851 (train_fastspeech2:300) INFO: model_type = fastspeech2
2020-10-01 17:19:51,851 (train_fastspeech2:300) INFO: fastspeech2_params = {'n_speakers': 1, 'encoder_hidden_size': 384, 'encoder_num_hidden_layers': 4, 'encoder_num_attention_heads': 2, 'encoder_attention_head_size': 192, 'encoder_intermediate_size': 1024, 'encoder_intermediate_kernel_size': 3, 'encoder_hidden_act': 'mish', 'decoder_hidden_size': 384, 'decoder_num_hidden_layers': 4, 'decoder_num_attention_heads': 2, 'decoder_attention_head_size': 192, 'decoder_intermediate_size': 1024, 'decoder_intermediate_kernel_size': 3, 'decoder_hidden_act': 'mish', 'variant_prediction_num_conv_layers': 2, 'variant_predictor_filter': 256, 'variant_predictor_kernel_size': 3, 'variant_predictor_dropout_rate': 0.5, 'num_mels': 80, 'hidden_dropout_prob': 0.2, 'attention_probs_dropout_prob': 0.1, 'max_position_embeddings': 2048, 'initializer_range': 0.02, 'output_attentions': False, 'output_hidden_states': False}
2020-10-01 17:19:51,851 (train_fastspeech2:300) INFO: batch_size = 16
2020-10-01 17:19:51,851 (train_fastspeech2:300) INFO: remove_short_samples = True
2020-10-01 17:19:51,851 (train_fastspeech2:300) INFO: allow_cache = True
2020-10-01 17:19:51,851 (train_fastspeech2:300) INFO: mel_length_threshold = 32
2020-10-01 17:19:51,851 (train_fastspeech2:300) INFO: is_shuffle = True
2020-10-01 17:19:51,851 (train_fastspeech2:300) INFO: optimizer_params = {'initial_learning_rate': 0.001, 'end_learning_rate': 5e-05, 'decay_steps': 150000, 'warmup_proportion': 0.02, 'weight_decay': 0.001}
2020-10-01 17:19:51,851 (train_fastspeech2:300) INFO: train_max_steps = 200000
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: save_interval_steps = 5000
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: eval_interval_steps = 500
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: log_interval_steps = 200
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: num_save_intermediate_results = 1
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: train_dir = ../dump/train/
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: dev_dir = ../dump/valid/
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: use_norm = True
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: f0_stat = ../dump/stats_f0.npy
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: energy_stat = ../dump/stats_energy.npy
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: outdir = fastspeech2/exp/train.fastspeech2.v1/
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: config = ./examples/fastspeech2/conf/fastspeech2.v1.yaml
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: resume = 
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: verbose = 1
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: mixed_precision = True
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: pretrained = 
2020-10-01 17:19:51,852 (train_fastspeech2:300) INFO: version = 0.0
Traceback (most recent call last):
  File "examples/fastspeech2/train_fastspeech2.py", line 414, in <module>
    main()
  File "examples/fastspeech2/train_fastspeech2.py", line 327, in main
    mel_length_threshold=mel_length_threshold,
  File "./examples/fastspeech2/fastspeech2_dataset.py", line 94, in __init__
    assert len(mel_files) != 0, f"Not found any mels files in ${root_dir}."
AssertionError: Not found any mels files in $../dump/train/.

I do not understand at what stage I should have received mel. I ran the preprocess of my dataset, which was passed successfully. Everything was in line with the guide. Then, following the instructions for extracting durations using MFA, I got the durations. All steps have been successfully completed. But when I run fastspeech2 training this issue occurs. Pls help a newbie:))

**Comment by zhanghaobucunzai** [comment]
请问，该问题是怎么解决的，我也遇到了？
