### ISSUE TITLE
Runtime error during training

### ISSUE THREAD

**Issue by luis-vera** [TensorSpeech/TensorFlowTTS#290]
Hi again.

I am in training stage with TensorflowTTS and I have found the following Runtime errors (I used ljspeech as a dataset):

**Using fastspeech** 

Traceback (most recent call last):
  File "examples\fastspeech\train_fastspeech.py", line 386, in <module>
    main()
  File "examples\fastspeech\train_fastspeech.py", line 291, in main
    train_dataset = CharactorDurationMelDataset(
  File ".\examples\fastspeech\fastspeech_dataset.py", line 64, in __init__
    assert (
AssertionError: Number of charactor, mel and duration files are different                 (12445 vs 12445 vs 0).

**Using tacotron**

Traceback (most recent call last):
  File "examples\tacotron2\train_tacotron2.py", line 486, in <module>
    main()
  File "examples\tacotron2\train_tacotron2.py", line 474, in main
    trainer.fit(
  File "C:\Python38\lib\site-packages\tensorflow_tts\trainers\base_trainer.py", line 852, in fit
    self.run()
  File "C:\Python38\lib\site-packages\tensorflow_tts\trainers\base_trainer.py", line 101, in run
    self._train_epoch()
  File "C:\Python38\lib\site-packages\tensorflow_tts\trainers\base_trainer.py", line 123, in _train_epoch
    self._train_step(batch)
  File "examples\tacotron2\train_tacotron2.py", line 109, in _train_step
    self.one_step_forward(batch)
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 545, in call
    outputs = execute.execute(
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[32,174,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
         [[{{node tacotron2/decoder/while/body/_1/tacotron2/decoder/while/decoder_cell/mul_1}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference__one_step_forward_23585]

Function call stack:
_one_step_forward

[train]:   0%|                                                                     | 0/200000 [41:56<?, ?it/s]

Please if you could help to solve it. Thanks

**Comment by machineko** [comment]
`AssertionError: Number of charactor, mel and duration files are different (12445 vs 12445 vs 0).`

You didn't extract durations in preprocessing step

**Comment by luis-vera** [comment]
OK I understand but I need to know where I include the "extract durations" because I typed the commands according Readme file in preprocessing. In my case I typed the following:

tensorflow-tts-preprocess --rootdir LJSpeech-1.1 --outdir dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech

tensorflow-tts-normalize --rootdir dump_ljspeech --outdir dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech

**Comment by machineko** [comment]
Just follow tutorial [fs-example](https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/fastspeech)

Here 

> If you already have preprocessed version of your target dataset, you don't need to use this example dataloader, you just need refer my dataloader and modify generator function to adapt with your case. Normally, a generator function should return [charactor_ids, duration, mel]. Pls see tacotron2-example to know how to extract durations [Extract Duration](https://github.com/dathudeptrai/TensorflowTTS/tree/master/examples/tacotron2#step-4-extract-duration-from-alignments-for-fastspeech)

**Comment by luis-vera** [comment]
Hi again. I tried with:

python examples/tacotron2/extract_duration.py --rootdir dump_ljspeech/valid/ --outdir dump_ljspeech/valid/durations/ --checkpoint examples/tacotron2/exp/train.tacotron2.v1/checkpoints/model-65000.h5 --use-norm 1 --config examples/tacotron2/conf/tacotron2.v1.yaml --batch-size 32 --win-front 3 --win-back 3

but I found an error because the directory "checkpoints" is empty so it's not possible to find model-65000.h5 

Thanks a lot

**Comment by machineko** [comment]
You have to download pretrained taco2 model just follow example tutorial :)

**Comment by luis-vera** [comment]
Hi, thanks a lot for your cooperation. I downloaded the model h5 and I tried again:

Traceback (most recent call last):
  File "examples/tacotron2/extract_duration.py", line 237, in <module>
    main()
  File "examples/tacotron2/extract_duration.py", line 161, in main
    mel_outputs, post_mel_outputs, stop_outputs, alignment_historys = tacotron2(
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 545, in call
    outputs = execute.execute(
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:    Trying to access element 148 in a list with 148 elements.
         [[{{node while/body/_1/while/TensorArrayV2Read_1/TensorListGetItem}}]]
         [[tacotron2/encoder/bilstm/backward_lstm/PartitionedCall]] [Op:__inference_function_8717]

Function call stack:
function -> function -> function

**Comment by dathudeptrai** [comment]
> Hi, thanks a lot for your cooperation. I downloaded the model h5 and I tried again:
> 
> Traceback (most recent call last):
> File "examples/tacotron2/extract_duration.py", line 237, in 
> main()
> File "examples/tacotron2/extract_duration.py", line 161, in main
> mel_outputs, post_mel_outputs, stop_outputs, alignment_historys = tacotron2(
> File "C:\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in **call**
> result = self._call(*args, **kwds)
> File "C:\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 846, in _call
> return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds) # pylint: disable=protected-access
> File "C:\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1843, in _filtered_call
> return self._call_flat(
> File "C:\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1923, in _call_flat
> return self._build_call_outputs(self._inference_function.call(
> File "C:\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 545, in call
> outputs = execute.execute(
> File "C:\Python38\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
> tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Trying to access element 148 in a list with 148 elements.
> [[{{node while/body/_1/while/TensorArrayV2Read_1/TensorListGetItem}}]]
> [[tacotron2/encoder/bilstm/backward_lstm/PartitionedCall]] [Op:__inference_function_8717]
> 
> Function call stack:
> function -> function -> function

can you install a newest tensorflow 2.3.1 and tensorflow_addons 0.11.2 and try again ?

**Comment by luis-vera** [comment]
Hi. Yes, I have it installed in my PC

>>> import tensorflow as tf
>>> print(tf.__version__)
2.3.1
>>> import tensorflow_addons
>>> print(tensorflow_addons.__version__)
0.11.2

**Comment by machineko** [comment]
You can try TF 2.1 and some older TF addons also diffrent python version (3.6 is the official version for TensorFlow docker images).

**Comment by dathudeptrai** [comment]
@luis-vera can you add this code https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/tacotron2/train_tacotron2.py#L18-L20 in the head of the extract_duration.py ?

**Comment by luis-vera** [comment]
I added the code in extract_duration.py and the error was this:

Traceback (most recent call last):
  File "examples/tacotron2/extract_duration.py", line 242, in <module>
    main()
  File "examples/tacotron2/extract_duration.py", line 166, in main
    mel_outputs, post_mel_outputs, stop_outputs, alignment_historys = tacotron2(
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 545, in call
    outputs = execute.execute(
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:    Trying to access element 148 in a list with 148 elements.
         [[{{node while/body/_1/while/TensorArrayV2Read_1/TensorListGetItem}}]]
         [[tacotron2/encoder/bilstm/backward_lstm/PartitionedCall]] [Op:__inference_function_8717]

**Comment by trinitylundgren** [comment]
Hi @dathudeptrai - we're running into the same issue as above (the most recent error). This occurred while following along with the tutorial and trying to extract durations. As in the above, the error is: 

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Trying to access element 148 in a list with 148 elements.`

Any suggestions on how to fix?

@luis-vera, any update on your issue? Were you able to resolve this?

**Comment by StarWang** [comment]
Hi @trinitylundgren did you get any luck on this issue? I got similar error as you do
