### ISSUE TITLE
Error during evaluation step

### ISSUE THREAD

**Issue by qianhui-wan** [TensorSpeech/TensorFlowTTS#294]
Hi, I'm training a tacotron2 model and had this error at the evaluation step during training

```
Traceback (most recent call last):
  File "train_tacotron2.py", line 478, in <module>
    main()
  File "train_tacotron2.py", line 470, in main
    resume=args.resume,
  File "/home/python_user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 852, in fit
    self.run()
  File "/home/python_user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 101, in run
    self._train_epoch()
  File "/home/python_user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 127, in _train_epoch
    self._check_eval_interval()
  File "/home/python_user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 164, in _check_eval_interval
    self._eval_epoch()
  File "/home/python_user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 743, in _eval_epoch
    self.one_step_evaluate(batch)
  File "/home/python_user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/python_user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 814, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/python_user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/python_user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/python_user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/python_user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/python_user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [16,237,3010] vs. [16,237,2000]
	 [[node mul (defined at train_tacotron2.py:172) ]] [Op:__inference__one_step_evaluate_937725]

Errors may have originated from an input operation.
Input Source operations connected to node mul:
 batch (defined at /home/python_user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py:743)	
 tacotron2/transpose (defined at /home/python_user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tensorflow_tts/models/tacotron2.py:882)

Function call stack:
_one_step_evaluate
```

Is this related to the mel length of valid set that is over 2000? But I thought the 2000 limitation applies to train set only?

**Comment by dathudeptrai** [comment]
@qianhui-wan 2k is maximum mel length in both training and valid. 3010 is so long, you need split/cut it into multiple chunks, a max mel length in training should be around 800-900, for validation it can be <= 1500

**Comment by Dominuke** [comment]
Noob question but is it possible to change the 2000 limitation? I have been trying to find where the limit is.

**Comment by dathudeptrai** [comment]
> Noob question but is it possible to change the 2000 limitation? I have been trying to find where the limit is.

https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/models/tacotron2.py#L806. The maximum step to train tacotron2 should be < 1k.

**Comment by Dominuke** [comment]
@dathudeptrai thank you for the solution, I found after preprocessing with LibriTTS there are many exceeding this limit. I will see what happens if i just push on through
