### ISSUE TITLE
fix_mismatch.py has ZeroDivisionError if mfa with longer duration is 0

### ISSUE THREAD

**Issue by OscarVanL** [TensorSpeech/TensorFlowTTS#306]
Running fix_mismatch.py results in a ZeroDivisionError if the `mfa_longer` list has 0 elements.
```
python examples/mfa_extraction/fix_mismatch.py \
>   --base_path ./dump_briefhistory \
>   --trimmed_dur_path ./briefhistory/trimmed-durations \
>   --dur_path ./briefhistory/durations
```

```
INFO: FIXING train set ...

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 770.29it/s]
Traceback (most recent call last):
  File "examples/mfa_extraction/fix_mismatch.py", line 121, in <module>
    fix()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "examples/mfa_extraction/fix_mismatch.py", line 107, in fix
    f"{t} stats: number of mfa with longer duration: {len(mfa_longer)}, total diff: {sum(mfa_longer)}"
ZeroDivisionError: division by zero
```

This logging line is responsible, when dividing by `len(mfa_longer)`:

```
logging.info(
       f"{t} stats: number of mfa with longer duration: {len(mfa_longer)}, total diff: {sum(mfa_longer)}"
       f", mean diff: {sum(mfa_longer)/len(mfa_longer)}"
)
```

The next logging section directly below already has a workaround for this problem, so this just needs to be replicated for the above line...

```
logging.info(
        f"{t} stats: number of mfa with shorter duration: {len(mfa_shorter)}, total diff: {sum(mfa_shorter)}"
        f", mean diff: {sum(mfa_shorter)/len(mfa_shorter) if len(mfa_shorter) > 0 else 0}"
)
```

**Comment by OscarVanL** [comment]
My PR was merged so this is fixed :)
