### ISSUE TITLE
AttributeError: 'PerReplica' object has no attribute 'numpy' when on multi GPU training

### ISSUE THREAD

**Issue by ZhaoZeqing** [TensorSpeech/TensorFlowTTS#309]
I'm trying to train Tacotron2 on multi GPU with P100, then got this error. It's ok with 2080Ti.

Traceback (most recent call last):
  File "examples/tacotron2/train_tacotron2.py", line 488, in <module>
    main()
  File "examples/tacotron2/train_tacotron2.py", line 480, in main
    resume=args.resume,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 852, in fit
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 101, in run
    self._train_epoch()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 127, in _train_epoch
    self._check_eval_interval()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 164, in _check_eval_interval
    self._eval_epoch()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 747, in _eval_epoch
    self.generate_and_save_intermediate_result(batch)
  File "examples/tacotron2/train_tacotron2.py", line 217, in generate_and_save_intermediate_result
    utt_ids = batch["utt_ids"].numpy()
AttributeError: 'PerReplica' object has no attribute 'numpy'

**Comment by dathudeptrai** [comment]
i know this bug :))) let me fix it :))).
