### ISSUE TITLE
Train tactron2 baker error

### ISSUE THREAD

**Issue by jinfagang** [TensorSpeech/TensorFlowTTS#311]
Can anyone could take a look:

```
[train]:   0%|                                                                                                            | 0/200000 [00:00<?, ?it/s]2020-10-16 22:18:54.780040: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: cond/branch_executed/_8
2020-10-16 22:19:04.721700: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 6653 of 9498
2020-10-16 22:19:07.178058: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:221] Shuffle buffer filled.
Traceback (most recent call last):
  File "examples/tacotron2/train_tacotron2.py", line 488, in <module>
    main()
  File "examples/tacotron2/train_tacotron2.py", line 476, in main
    trainer.fit(
  File "/media/jintian/samsung/source/ai/swarm/exp/TensorFlowTTS/tensorflow_tts/trainers/base_trainer.py", line 870, in fit
    self.run()
  File "/media/jintian/samsung/source/ai/swarm/exp/TensorFlowTTS/tensorflow_tts/trainers/base_trainer.py", line 101, in run
    self._train_epoch()
  File "/media/jintian/samsung/source/ai/swarm/exp/TensorFlowTTS/tensorflow_tts/trainers/base_trainer.py", line 123, in _train_epoch
    self._train_step(batch)
  File "examples/tacotron2/train_tacotron2.py", line 109, in _train_step
    self.one_step_forward(batch)
  File "/home/jintian/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/jintian/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/jintian/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/jintian/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "/home/jintian/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/jintian/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545, in call
    outputs = execute.execute(
  File "/home/jintian/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[31,5] = 206 is not in [0, 149)
	 [[node tacotron2/encoder/embeddings/Gather (defined at /media/jintian/samsung/source/ai/swarm/exp/TensorFlowTTS/tensorflow_tts/models/tacotron2.py:166) ]] [Op:__inference__one_step_forward_23585]

Errors may have originated from an input operation.
Input Source operations connected to node tacotron2/encoder/embeddings/Gather:
 batch_1 (defined at examples/tacotron2/train_tacotron2.py:109)

Function call stack:
_one_step_forward

[train]:   0%|    
```

**Comment by dathudeptrai** [comment]
seem the vocab_size is wrong, 149 is ljspeech vocab size.

**Comment by jinfagang** [comment]
@dathudeptrai Thanks for your reply! I am using baker's config for train, can u help me? I don't know which where should I edit?
