### ISSUE TITLE
Paddings must be non-negative

### ISSUE THREAD

**Issue by jackiegeek** [TensorSpeech/TensorFlowTTS#328]
When I use sample rate 8000, hop_size = 100, upsample scare = [5, 5], when start evaluation, it raise Error:  Paddings must be non-negative: 0 -7480  ( when I use the same data  with config: sample rate 8000, hop_size = 200, upsample scare = [2, 5, 5], it works fine)

<details>
 <summary><strong>Traceback</strong> (click to expand)</summary>

```
[train]:   0%|                           | 2000/4000000 [12:02<357:23:28,  3.11it/s]2020-10-25 08:46:09,704 (base_trainer:566) INFO: (Step: 2000) train_adversarial_loss
 = 0.0000.                                                                                                                                                              
2020-10-25 08:46:09,705 (base_trainer:566) INFO: (Step: 2000) train_subband_spectral_convergence_loss = 0.9278.                                                         
2020-10-25 08:46:09,705 (base_trainer:566) INFO: (Step: 2000) train_subband_log_magnitude_loss = 1.2382.                                                                
2020-10-25 08:46:09,706 (base_trainer:566) INFO: (Step: 2000) train_fullband_spectral_convergence_loss = 0.8971.                                                        
2020-10-25 08:46:09,706 (base_trainer:566) INFO: (Step: 2000) train_fullband_log_magnitude_loss = 1.3189.                                                               
2020-10-25 08:46:09,707 (base_trainer:566) INFO: (Step: 2000) train_gen_loss = 2.1909.                                                                                  
2020-10-25 08:46:09,707 (base_trainer:566) INFO: (Step: 2000) train_real_loss = 0.0000.                                                                                 
2020-10-25 08:46:09,708 (base_trainer:566) INFO: (Step: 2000) train_fake_loss = 0.0000.                                                                                 
2020-10-25 08:46:09,709 (base_trainer:566) INFO: (Step: 2000) train_dis_loss = 0.0000.                                                                                  
2020-10-25 08:46:09,723 (base_trainer:418) INFO: (Steps: 2000) Start evaluation.                                                                                        
[eval]: 0it [00:04, ?it/s] 
Traceback (most recent call last):                                                                                                                                      
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 2102, in execution_mode                                                        
    yield                                                                                                                                                               
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 758, in _next_internal                                                 
    output_shapes=self._flat_output_shapes)                                                                                                                             
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2610, in iterator_get_next                                               
    _ops.raise_from_not_ok_status(e, name)                                                                                                                              
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status                                              
    six.raise_from(core._status_to_exception(e.code, message), None)                                                                                                    
  File "<string>", line 3, in raise_from                                                                                                                                
tensorflow.python.framework.errors_impl.InvalidArgumentError: Paddings must be non-negative: 0 -7480                                                                    
         [[{{node cond_4/else/_38/cond_4/Pad}}]]                                                                                                                        
         [[MultiDeviceIteratorGetNextFromShard]]                                                                                                                        
         [[RemoteCall]] [Op:IteratorGetNext]  
```
</details>

**Comment by dathudeptrai** [comment]
@jackiegeek can you check (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/multiband_melgan/conf/multiband_melgan.v1.yaml#L71-L72)

**Comment by jackiegeek** [comment]
thx!  I forget to change batch_max_steps_valid: 81920, my mistake..

**Comment by jackiegeek** [comment]
I change to 
```
batch_max_steps: 8000
batch_max_steps_valid: 80000
```
but still get `Paddings must be non-negative` error

**Comment by dathudeptrai** [comment]
> 80000

can you try `batch_max_steps_valid`: 8000 as `batch_max_steps` ?

**Comment by jackiegeek** [comment]
works! thx!
