### ISSUE TITLE
tensorflow-tts-preprocess the baker dataset but had raise value AssertionError

### ISSUE THREAD

**Issue by Adazzh** [TensorSpeech/TensorFlowTTS#353]
when i preprocess audio features,h=there are some err,but i don't know why.
tensorflow-tts-preprocess --rootdir /home/data/tts/BZNSYP --outdir ./BZNSYP --config preprocess/baker_preprocess.yaml --dataset baker
2020-11-05 10:36:05.235793: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-11-05 10:36:17,289 (preprocess:368) INFO: Selected 'baker' processor.
Skip this: 002365 这图#2难不成#2是#1Ｐ过的#4？ ['zhe4', 'tu2', 'nan2', 'bu4', 'cheng2', 'shi4', 'P', 'IY1', 'guo4', 'de5']
Skip this: 002762 我是#2善良#1活泼#3、好奇心#1旺盛的#2Ｂ型血#4。 ['wo3', 'shi4', 'shan4', 'liang2', 'huo2', 'po1', 'hao4', 'qi2', 'xin1', 'wang4', 'sheng4', 'de5', 'bi4', 'xing2', 'xie3']
2020-11-05 10:36:18,061 (preprocess:407) INFO: Training items: 9498
2020-11-05 10:36:18,073 (preprocess:408) INFO: Validation items: 500
[Preprocessing train]:   0%|                                                                                                   | 0/9498 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/data3/SpeechAnaconda/anaconda3/bin/tensorflow-tts-preprocess", line 8, in <module>
    sys.exit(preprocess())
  File "/home/data3/SpeechAnaconda/anaconda3/lib/python3.7/site-packages/tensorflow_tts/bin/preprocess.py", line 441, in preprocess
    for result, mel, energy, f0, features in train_map:
  File "/home/data3/SpeechAnaconda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 354, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/data3/SpeechAnaconda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
AssertionError

**Comment by PeijiYang** [comment]
I got the same error, how to repair it ?

**Comment by nmfisher** [comment]
The error from `pool.py` is misleading (and annoying), the actual error probably stems from a sample rate mismatch.

The Baker processor has a hardcoded 24000Hz sample rate:
https://github.com/TensorSpeech/TensorFlowTTS/blob/29595017ab1b2a3bdef444b2195648383fa5ed05/tensorflow_tts/processor/baker.py#L546

which will throw an error inside `gen_audio_features` (meaning the generator passed to `pool` will be empty).

As a temporary fix, change the sample rate in `baker.py` (though ideally this should be picked up from the YAML).
