### ISSUE TITLE
Incompatible shapes: [2,40,2061] vs. [2,40,2000] +Errors may have originated from an input operation.

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [TensorSpeech/TensorFlowTTS#381]
I am using batch size 2 in `tacotron2.v1.yaml` with a custom 16000 Hz, mono, 10h total `myDataset`.
I prepared it and normalized it.
I started

`python examples/tacotron2/train_tacotron2.py  --train-dir ./dump_myDataset/train/ --dev-dir ./dump_myDataset/valid/ --outdir ./examples/tacotron2/exp/train.tacotron2.v1/ --config ./examples/tacotron2/conf/tacotron2.v1.yaml --use-norm 1 --mixed_precision 0 --resume ""`

After some time I got
```
...
[eval]: 357it [07:26,  1.06it/s]
[eval]: 358it [07:27,  1.01s/it]
[eval]: 359it [07:28,  1.02it/s]
[eval]: 360it [07:29,  1.14it/s]
[eval]: 361it [07:31,  1.13s/it]
[eval]: 362it [07:31,  1.25s/it]
2020-11-21 04:27:14,185 (base_trainer:768) INFO: (Steps: 1000) Finished evaluation (362 steps per epoch).
2020-11-21 04:27:14,185 (base_trainer:775) INFO: (Steps: 1000) eval_stop_token_loss = 0.0214.
2020-11-21 04:27:14,185 (base_trainer:775) INFO: (Steps: 1000) eval_mel_loss_before = 0.3333.
2020-11-21 04:27:14,185 (base_trainer:775) INFO: (Steps: 1000) eval_mel_loss_after = 0.2959.
2020-11-21 04:27:14,185 (base_trainer:775) INFO: (Steps: 1000) eval_guided_attention_loss = 0.0087.
2020-11-21 04:27:15,737 (base_trainer:170) INFO: Successfully saved checkpoint @ 1000 steps.
[train]:   1%|▎                                                            | 1149/200000 [1:52:23<227:28:46,  4.12s/it]Traceback (most recent call last):
  File "examples/tacotron2/train_tacotron2.py", line 488, in <module>
    main()
  File "examples/tacotron2/train_tacotron2.py", line 480, in main
    resume=args.resume,
  File "E:\Anaconda\envs\myEnv\lib\site-packages\tensorflow_tts\trainers\base_trainer.py", line 870, in fit
    self.run()
  File "E:\Anaconda\envs\myEnv\lib\site-packages\tensorflow_tts\trainers\base_trainer.py", line 101, in run
    self._train_epoch()
  File "E:\Anaconda\envs\myEnv\lib\site-packages\tensorflow_tts\trainers\base_trainer.py", line 123, in _train_epoch
    self._train_step(batch)
  File "examples/tacotron2/train_tacotron2.py", line 109, in _train_step
    self.one_step_forward(batch)
  File "E:\Anaconda\envs\myEnv\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "E:\Anaconda\envs\myEnv\lib\site-packages\tensorflow\python\eager\def_function.py", line 807, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "E:\Anaconda\envs\myEnv\lib\site-packages\tensorflow\python\eager\function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "E:\Anaconda\envs\myEnv\lib\site-packages\tensorflow\python\eager\function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "E:\Anaconda\envs\myEnv\lib\site-packages\tensorflow\python\eager\function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "E:\Anaconda\envs\myEnv\lib\site-packages\tensorflow\python\eager\function.py", line 550, in call
    ctx=ctx)
  File "E:\Anaconda\envs\myEnv\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [2,40,2061] vs. [2,40,2000]
         [[node mul (defined at examples/tacotron2/train_tacotron2.py:168) ]] [Op:__inference__one_step_forward_42063]

Errors may have originated from an input operation.
Input Source operations connected to node mul:
 tacotron2/transpose (defined at E:\Anaconda\envs\myEnv\lib\site-packages\tensorflow_tts\models\tacotron2.py:882)

 batch (defined at examples/tacotron2/train_tacotron2.py:109)

Function call stack:
_one_step_forward

[train]:   1%|▎                                                            | 1149/200000 [1:52:55<325:42:51,  5.90s/it]

```

At `examples\tacotron2\exp\train.tacotron2.v1\checkpoints` I have 4 files,

1. `checkpoint`
2. `ckpt-1000.data-00000-of-00001`
3. `ckpt-1000.index`
4. `model-1000.h5`

`model-1000.h5` is at about 126MB, whereas the rest is all 1KB.

How to solve this?

**Comment by dathudeptrai** [comment]
@ErfolgreichCharismatisch 

pls add below code to (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/tacotron2/tacotron_dataset.py#L197):

```
        datasets = datasets.filter(
            lambda x: x["mel_lengths"] <=800
        )
```
