### ISSUE TITLE
when extracting duration, there is one error: "ValueError: Shapes (149, 512) and (219, 512) are incompatible"

### ISSUE THREAD

**Issue by zcy618** [TensorSpeech/TensorFlowTTS#386]
Dear friends:
when I extracting duration in tacotron2 step 4, I met one issue:
2020-11-23 19:47:38.283307: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7420 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:04:00.0, compute capability: 6.1)
2020-11-23 19:47:38.912491: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-11-23 19:47:39.672173: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
Traceback (most recent call last):
  File "examples/tacotron2/extract_duration.py", line 237, in <module>
    main()
  File "examples/tacotron2/extract_duration.py", line 147, in main
    tacotron2.load_weights(args.checkpoint)
  File "/home/chenyuz/Desktop/TensorFlowTTS/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2211, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/home/chenyuz/Desktop/TensorFlowTTS/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 708, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/chenyuz/Desktop/TensorFlowTTS/venv/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/chenyuz/Desktop/TensorFlowTTS/venv/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3576, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype(x)))
  File "/home/chenyuz/Desktop/TensorFlowTTS/venv/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 858, in assign
    self._shape.assert_is_compatible_with(value_tensor.shape)
  File "/home/chenyuz/Desktop/TensorFlowTTS/venv/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1134, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (149, 512) and (219, 512) are incompatible

I am using command:
CUDA_VISIBLE_DEVICES=0 python examples/tacotron2/extract_duration.py   --rootdir ./Baker_feats/train/   --outdir ./Baker_feats/train/durations/   --checkpoint ./Baker_feats/train.tacotron2.v1/checkpoints/model-2000.h5   --use-norm 1   --config ./examples/tacotron2/conf/tacotron2.v1.yaml   --batch-size 32 --win-front 3 --win-back 3

could I know what may I miss please?
Thanks.

**Comment by dathudeptrai** [comment]
@zcy618 ur config is wrong, it should be : `--config ./examples/tacotron2/conf/tacotron2.baker.v1.yaml`

**Comment by zcy618** [comment]
> @zcy618 ur config is wrong, it should be : `--config ./examples/tacotron2/conf/tacotron2.baker.v1.yaml`

😅
