### ISSUE TITLE
tacotron2 extract duration failure

### ISSUE THREAD

**Issue by Zegalryang** [TensorSpeech/TensorFlowTTS#404]
in commit 0a95e31, 
I tried to extract duration using tacotron2
(use kss dataset)

but, error occurred

Traceback (most recent call last):
  File "examples/tacotron2/extract_duration.py", line 237, in <module>
    main()
  File "examples/tacotron2/extract_duration.py", line 141, in main
    tacotron2 = TFTacotron2(
  File "/TensorFlowTTS/tensorflow_tts/models/tacotron2.py", line 746, in __init__
    super().__init__(self, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 261, in __init__
    generic_utils.validate_kwargs(kwargs, {'trainable', 'dtype', 'dynamic',
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 778, in validate_kwargs
    raise TypeError(error_message, kwarg)
TypeError: ('Keyword argument not understood:', 'training')

what should I do?

**Comment by dathudeptrai** [comment]
@Zegalryang remove this line of code (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/tacotron2/extract_duration.py#L143)
