### ISSUE TITLE
Error in Tacotron2 when doing evaluation: Incompatible shapes: [16,267,635] vs. [16,267,61]

### ISSUE THREAD

**Issue by ZhaoZeqing** [TensorSpeech/TensorFlowTTS#413]
I trained Tacotron2 model with this error when doing evaluation, and I tried this [solution ](https://github.com/TensorSpeech/TensorFlowTTS/issues/381) but not worked.

Model: "tacotron2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
encoder (TFTacotronEncoder)  multiple                  8176640   
_________________________________________________________________
decoder_cell (TFTacotronDeco multiple                  18246402  
_________________________________________________________________
post_net (TFTacotronPostnet) multiple                  5460480   
_________________________________________________________________
residual_projection (Dense)  multiple                  41040     
=================================================================
Total params: 31,924,562
Trainable params: 31,914,322
Non-trainable params: 10,240
_________________________________________________________________
[train]:   0%|                                                                          | 0/200000 [00:00<?, ?it/s]2020-12-05 18:11:49.182967: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: cond/branch_executed/_8
2020-12-05 18:11:59.081151: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 3691 of 12179
2020-12-05 18:12:09.091942: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 7426 of 12179
2020-12-05 18:12:19.080499: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 11137 of 12179
2020-12-05 18:12:21.787995: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:221] Shuffle buffer filled.
[train]:   0%|                                                             | 2/200000 [00:51<1968:46:36, 35.44s/it]2020-12-05 18:12:40,982 (base_trainer:978) INFO: (Step: 2) train_stop_token_loss = 0.7280.
2020-12-05 18:12:40,983 (base_trainer:978) INFO: (Step: 2) train_mel_loss_before = 0.3992.
2020-12-05 18:12:40,983 (base_trainer:978) INFO: (Step: 2) train_mel_loss_after = 1.2044.
2020-12-05 18:12:40,984 (base_trainer:978) INFO: (Step: 2) train_guided_attention_loss = 0.0048.
2020-12-05 18:12:41,353 (base_trainer:172) INFO: Successfully saved checkpoint @ 2 steps.
[train]:   0%|                                                             | 4/200000 [00:57<1040:21:29, 18.73s/it]2020-12-05 18:12:46,349 (base_trainer:978) INFO: (Step: 4) train_stop_token_loss = 0.7272.
2020-12-05 18:12:46,350 (base_trainer:978) INFO: (Step: 4) train_mel_loss_before = 0.4021.
2020-12-05 18:12:46,351 (base_trainer:978) INFO: (Step: 4) train_mel_loss_after = 1.2046.
2020-12-05 18:12:46,351 (base_trainer:978) INFO: (Step: 4) train_guided_attention_loss = 0.0052.
2020-12-05 18:12:46,731 (base_trainer:172) INFO: Successfully saved checkpoint @ 4 steps.
[train]:   0%|                                                              | 5/200000 [01:00<773:27:17, 13.92s/it]2020-12-05 18:12:49,050 (base_trainer:883) INFO: (Steps: 5) Start evaluation.
                          2020-12-05 18:12:49.220598: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] 
Skipping loop optimization for Merge node with control input: cond/branch_executed/_8
[eval]: 0it [00:04, ?it/s]
Traceback (most recent call last):
  File "examples/tacotron2/train_tacotron2.py", line 530, in <module>
    main()
  File "examples/tacotron2/train_tacotron2.py", line 522, in main
    resume=args.resume,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 999, in fit
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 103, in run
    self._train_epoch()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 129, in _train_epoch
    self._check_eval_interval()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 166, in _check_eval_interval
    self._eval_epoch()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 890, in _eval_epoch
    self.one_step_evaluate(batch)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Incompatible shapes: [16,267,635] vs. [16,267,61]
         [[node mul (defined at examples/tacotron2/train_tacotron2.py:171) ]]
         [[tacotron2/decoder/while/body/_1/tacotron2/decoder/while/decoder_cell/assert_positive/assert_less/Assert/Assert/_59]]
  (1) Invalid argument:  Incompatible shapes: [16,267,635] vs. [16,267,61]
         [[node mul (defined at examples/tacotron2/train_tacotron2.py:171) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference__one_step_evaluate_27903]

Errors may have originated from an input operation.
Input Source operations connected to node mul:
 tacotron2/transpose (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_tts/models/tacotron2.py:878)
 batch (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py:890)

Input Source operations connected to node mul:
 tacotron2/transpose (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_tts/models/tacotron2.py:878)
 batch (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py:890)

Function call stack:
_one_step_evaluate -> _one_step_evaluate

[train]:   0%|                                                              | 5/200000 [01:04<721:43:46, 12.99s/it]

**Comment by dathudeptrai** [comment]
@ZhaoZeqing fixed.

**Comment by ZhaoZeqing** [comment]
Thanks!
