### ISSUE TITLE
OOM Error when evaluation(generate_and_save_intermediate_result) in Tacotron2

### ISSUE THREAD

**Issue by ZhaoZeqing** [TensorSpeech/TensorFlowTTS#416]
I used one V100 training Tacotron2 and my batch size is 16, the longest mel spectrogram length in my data is 799, but when doing evaluation, OOM error occurred:

2020-12-06 22:14:19.846616: W tensorflow/core/common_runtime/bfc_allocator.cc:439] _____________________***********************_**********_________________************_____**_____****
2020-12-06 22:14:19.846663: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at conv_ops.cc:539 : Resource exhausted: OOM when allocating tensor with shape[16,512,1,547973] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
[eval]: 0it [11:51, ?it/s]
Traceback (most recent call last):
  File "examples/tacotron2/train_tacotron2.py", line 537, in <module>
  File "examples/tacotron2/train_tacotron2.py", line 529, in main
    )
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 999, in fit
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 103, in run
    self._train_epoch()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 129, in _train_epoch
    self._check_eval_interval()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 166, in _check_eval_interval
    self._eval_epoch()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 894, in _eval_epoch
    self.generate_and_save_intermediate_result(batch)
  File "examples/tacotron2/train_tacotron2.py", line 203, in generate_and_save_intermediate_result
    (
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 814, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[16,512,1,547973] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node tacotron2/post_net/tf_tacotron_conv_batch_norm_5/conv_._0/conv1d (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_tts/models/tacotron2.py:108) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference__one_step_predict_53675]

Function call stack:
_one_step_predict

[train]:   0%|▎                                                   | 1000/200000 [54:47<181:43:46,  3.29s/it]

**Comment by dathudeptrai** [comment]
@ZhaoZeqing to be sure pls add this code below these line (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/tacotron2/tacotron_dataset.py#L195-L197):

```
        datasets = datasets.filter(
            lambda x: x["mel_lengths"] <=800
        )
```

**Comment by ZhaoZeqing** [comment]
@dathudeptrai I tried it but not worked. I'll pull the newest code. Thanks!

**Comment by ZhaoZeqing** [comment]
@dathudeptrai I pulled the newest code and trained Tacotron2 with LJSpeech on P100, my batch size is 32, the OOM error occurred randomly when doing evaluation, but not each evaluation.

**Comment by dathudeptrai** [comment]
> 32

is that ok when training ?. If yes, please use small batch_size when evaluation. (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/tacotron2/train_tacotron2.py#L434)

**Comment by ZhaoZeqing** [comment]
@dathudeptrai batch size 32 is ok when training LJSpeech on one P100, so evaluation's batch_size is 32 too. If I need use small batch_size when evaluation ?

**Comment by dathudeptrai** [comment]
> @dathudeptrai batch size 32 is ok when training LJSpeech on one P100, so evaluation's batch_size is 32 too. If I need use small batch_size when evaluation? I tried batch size 16, but OOM error still occurred.

hmm, i do not know why it can be train with bsize 32 but inference can't. Maybe you just need ignore evaluation step and use tensorboard to monitor the training progress :)).

**Comment by ZhaoZeqing** [comment]
@dathudeptrai I tried add this code at this [line](https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/tacotron2/train_tacotron2.py#L126)

`def _one_step_predict_per_replica(self, batch):
        outputs = self._model(**batch, training=True)
        return outputs`

It's ok now, but why training=False will cause this error?

**Comment by dathudeptrai** [comment]
> _one_step_predict_per_replica

ah, I forgot this. Yes, you should pass training = True for tacotron2 since it used teacher forcing when evaluating. When training=false, the model doesn't use teacher forcing so in the early of training progress, the model won't know when to stop decode so it caused OOM.

**Comment by ZhaoZeqing** [comment]
@dathudeptrai Thanks for your quickly reply :)
