### ISSUE TITLE
Train multispeaker  got Err!

### ISSUE THREAD

**Issue by zhangsanfeng86** [TensorSpeech/TensorFlowTTS#419]
set  "speaker = 3" in config.py
change fastspeech2_dataset.py as follow:

![image](https://user-images.githubusercontent.com/73547638/101469705-09ec2480-3980-11eb-90d3-709483aab6b5.png)

but got Err,as follow:
![image](https://user-images.githubusercontent.com/73547638/101469850-343de200-3980-11eb-8f3c-6b55f91f21ec.png)

**Comment by zhangsanfeng86** [comment]
2020-12-08 08:53:51.921671: W tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1908] No (suitable) GPUs detected, skipping auto_mixed_precision graph optimizer
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 1986, in execution_mode
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 655, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2363, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: [_Derived_]{{function_node __inference__load_data_104}} {{function_node __inference__load_data_104}} 0-th value returned by pyfunc_8 is int64, but expects int32
         [[{{node PyFunc_5}}]]
         [[StatefulPartitionedCall]]
         [[MultiDeviceIteratorGetNextFromShard]]
         [[RemoteCall]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TensorFlowTTS/examples/fastspeech2/train_fastspeech2.py", line 417, in <module>
    main()
  File "TensorFlowTTS/examples/fastspeech2/train_fastspeech2.py", line 409, in main
    resume=args.resume,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 852, in fit
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 101, in run
    self._train_epoch()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 121, in _train_epoch
    for train_steps_per_epoch, batch in enumerate(self.train_data_loader, 1):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/input_lib.py", line 296, in __next__
    return self.get_next()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/input_lib.py", line 316, in get_next
    self._iterators[i].get_next_as_list_static_shapes(new_name))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/input_lib.py", line 1112, in get_next_as_list_static_shapes
    return self._iterator.get_next()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py", line 581, in get_next
    result.append(self._device_iterators[i].get_next())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 741, in get_next
    return self._next_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 661, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 1989, in execution_mode
    executor_new.wait()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: [_Derived_]{{function_node __inference__load_data_104}} {{function_node __inference__load_data_104}} 0-th value returned by pyfunc_8 is int64, but expects int32
         [[{{node PyFunc_5}}]]
         [[StatefulPartitionedCall]]
         [[MultiDeviceIteratorGetNextFromShard]]
         [[RemoteCall]]
2020-12-08 08:53:52.462672: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]
[train]:   0%|                                                                                                                                                                 | 0/200000 [00:00<?, ?it/s]
root@fe7bdc8ff38d:/p#

**Comment by mingkzhou** [comment]
Have you solved the problem?I have the same problem.
