### ISSUE TITLE
MelGan: TypeError: unsupported operand type(s) for *: 'int' and 'dict'

### ISSUE THREAD

**Issue by t-dan** [TensorSpeech/TensorFlowTTS#432]
Hello,
I have tried to train melgan model from scratch (on LJS dataset), but it failed with the `TypeError: unsupported operand type(s) for *: 'int' and 'dict'` error after shuffle is done.

Is there something I did wrong? The codes are the same as in git ...

The whole error stack is:
```
2020-12-17 13:27:31.449514: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:221] Shuffle buffer filled.
Traceback (most recent call last):
  File "examples/melgan/train_melgan.py", line 528, in <module>
    main()
  File "examples/melgan/train_melgan.py", line 520, in main
    resume=args.resume,
  File "/.../tensorflow_tts/trainers/base_trainer.py", line 680, in fit
    def __init__(
  File "/.../tensorflow_tts/trainers/base_trainer.py", line 103, in run
    self._train_epoch()
  File "/.../tensorflow_tts/trainers/base_trainer.py", line 131, in _train_epoch
    
  File "/.../tensorflow_tts/trainers/base_trainer.py", line 297, in _train_step
    
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

/.../tensorflow_tts/trainers/base_trainer.py:299 _one_step_forward  *
         per_replica_losses = self._strategy.run(
/.../tensorflow_tts/trainers/base_trainer.py:431 _one_step_forward_per_replica  *         
        (
/.../tensorflow_tts/trainers/base_trainer.py:348 _calculate_generator_gradient_per_batch  *
        per_replica_gen_losses = tf.nn.compute_average_loss(

TypeError: unsupported operand type(s) for *: 'int' and 'dict'

[train]:   0%|                                                                                                                                                          | 0/4000000 [10:43<?, ?it/s]
```

Running it as:
`python3 examples/melgan/train_melgan.py --train-dir ./datasets/data_LJS/train --dev-dir ./datasets/data_LJS/valid  --outdir ./outputs/melgan_data_LJS/exp/train.melgan.v1/ --config ./examples/melgan/conf/melgan.v1.yaml --use-norm 1 --generator_mi`

And the preprocesing was called as:
`bin/tensorflow-tts-preprocess --rootdir ./datasets/data_LJS/ --outdir ./datasets/data_LJS/ --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech
bin/tensorflow-tts-normalize  --rootdir ./datasets/data_LJS/ --outdir ./datasets/data_LJS/ --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech`

**Comment by dathudeptrai** [comment]
@t-dan can you try to preprocess with the difference `rootdir` and `outdir` as the README ? . I just re-ran melgan training and everything was file.

**Comment by t-dan** [comment]
Will do and send a report. However, it seems strange to me, since the preprocess steps only create new data, not touching the wavs and cvs file, don't they?

**Comment by dathudeptrai** [comment]
@t-dan let try mb-melgan also :D

**Comment by t-dan** [comment]
OK, putting the preprocess data into separate directories, melgan started to work.... Don't understand why, but thank you.
