### ISSUE TITLE
Muliti GPU tkinter doesnot work? need mtTkinter? Please have a look, thanks a lot.

### ISSUE THREAD

**Issue by panyongfeng** [TensorSpeech/TensorFlowTTS#460]
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f638333b0e0>
Traceback (most recent call last):
  File "/home/yons/miniconda3/envs/tf23/lib/python3.7/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f638333b0e0>
Traceback (most recent call last):
  File "/home/yons/miniconda3/envs/tf23/lib/python3.7/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f638333b0e0>
Traceback (most recent call last):
  File "/home/yons/miniconda3/envs/tf23/lib/python3.7/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f638333b0e0>
Traceback (most recent call last):
  File "/home/yons/miniconda3/envs/tf23/lib/python3.7/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop

**Comment by panyongfeng** [comment]
CUDA_VISIBLE_DEVICES=0,1

**Comment by dathudeptrai** [comment]
@panyongfeng can you give me a command line to reproduce this bug ?.

**Comment by dathudeptrai** [comment]
maybe you can refer (https://github.com/r9y9/deepvoice3_pytorch/issues/5)

**Comment by panyongfeng** [comment]
Dear:
here is the cmdline:(it is completely follow the LJspeech tutorial)
CUDA_VISIBLE_DEVICES=0,1 python examples/tacotron2/train_tacotron2.py   --train-dir ../dump_ljspeech/train/   --dev-dir ../dump_ljspeech/valid/   --outdir ./examples/tacotron2/exp/train.tacotron2.v1/   --config ./examples/tacotron2/conf/tacotron2.v1.yaml   --use-norm 1   --mixed_precision 0   --resume ""

If I use CUDA_VISIBLE_DEVICES=0 then it is fine to run. if CUDA_VISIBLE_DEVICES=0,1 it will crush at step 500, like this:
2021-01-15 09:19:51,489 (base_trainer:978) INFO: (Step: 400) train_guided_attention_loss = 0.0053.
[train]:   0%|▎                                                                                                                                                    | 500/200000 [28:35<185:01:30,  3.34s/it]2021-01-15 09:25:24,310 (base_trainer:883) INFO: (Steps: 500) Start evaluation.
                          WARNING:tensorflow:From /home/yons/miniconda3/envs/tf23/lib/python3.7/site-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py:601: get_next_as_optional (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Iterator.get_next_as_optional()` instead.
2021-01-15 09:25:24,411 (deprecation:323) WARNING: From /home/yons/miniconda3/envs/tf23/lib/python3.7/site-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py:601: get_next_as_optional (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Iterator.get_next_as_optional()` instead.
2021-01-15 09:25:24.468999: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: cond/branch_executed/_8
                              Exception ignored in: <function Image.__del__ at 0x7f638333b0e0>
Traceback (most recent call last):
  File "/home/yons/miniconda3/envs/tf23/lib/python3.7/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f638333b0e0>

**Comment by dathudeptrai** [comment]
seem the bug is related to matplotlib.

**Comment by panyongfeng** [comment]
Thanks, I removed all matplotlib related code in train_tacotron.py, now it works.
