### ISSUE TITLE
Fine tuned Tacotron2 error on a multi-speaker base model

### ISSUE THREAD

**Issue by ZhaoZeqing** [TensorSpeech/TensorFlowTTS#485]
Hi~ I used a multi-speaker dataset training a base model then fine tuned on a target speaker dataset, I set n_speakers value to 107. The base model training was ok but got this error when fine tuned on the target speaker data:

```bash
021-01-29 23:58:50,618 (train_tacotron2:501) INFO: Successfully loaded pretrained weight from examples/tacotron2_avg/exp/train.tacotron2.v1.avg.16k.pure_phone.107/checkpoints/model-160000.h5.
[train]:   0%|                                                                                 | 0/200000 [00:00<?, ?it/s]2021-01-29 23:58:50.817422: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: cond/branch_executed/_8
Traceback (most recent call last):
  File "examples/tacotron2_avg/train_tacotron2.py", line 548, in <module>
    main()
  File "examples/tacotron2_avg/train_tacotron2.py", line 540, in main
    resume=args.resume,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 999, in fit
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 103, in run
    self._train_epoch()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 125, in _train_epoch
    self._train_step(batch)
  File "examples/tacotron2_avg/train_tacotron2.py", line 108, in _train_step
    self.one_step_forward(batch)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.CancelledError:    [_Derived_]Loop execution was cancelled.
         [[{{node while_19/LoopCond/_54}}]]
         [[tacotron2/encoder/bilstm/backward_lstm/PartitionedCall]] [Op:__inference__one_step_forward_24584]

Function call stack:
_one_step_forward -> _one_step_forward -> _one_step_forward

[train]:   0%|                                                                                 | 0/200000 [00:24<?, ?it/s]
```

**Comment by dathudeptrai** [comment]
@ZhaoZeqing still happened ?

**Comment by ZhaoZeqing** [comment]
@dathudeptrai Yes, it still happened.

**Comment by dathudeptrai** [comment]
can you make it reproducible on colab ? then i can debug for you :).

**Comment by ZhaoZeqing** [comment]
@dathudeptrai OK, I'll try it, thanks!

**Comment by ZhaoZeqing** [comment]
@dathudeptrai  TF2.3.1, cuda 11, V100  or multi-GPU still have some problems, but it's ok now with TF2.3, cuda 10.1 and one P100 
 :)

**Comment by dathudeptrai** [comment]
@ZhaoZeqing maybe because CUDA version =))

**Comment by PeijiYang** [comment]
@ZhaoZeqing When you finetune the multi-speaker base model, the n speaker value set 107 or 1？

**Comment by ZhaoZeqing** [comment]
> @ZhaoZeqing When you finetune the multi-speaker base model, the n speaker value set 107 or 1？

I used 107
