### ISSUE TITLE
Error while Extracting Duration

### ISSUE THREAD

**Issue by AdityaJain1030** [TensorSpeech/TensorFlowTTS#497]
Hey guys! Ive been trying to figure out how to finetune fastspeech, and had an issue with extracting the durations. My code is as follows: 

```
!CUDA_VISIBLE_DEVICES=0 python examples/tacotron2/extract_duration.py \
  --rootdir /content/dump/valid/ \
  --outdir /content/dump/valid/durations/ \
  --checkpoint /content/tacotron2-120k.h5 \
  --use-norm 1 \
  --config /content/tacotron2_config.yml \
  --batch-size 32 \
  --win-front 3 \
  --win-back 3
```

This returns the error 

```
Traceback (most recent call last):
  File "examples/tacotron2/extract_duration.py", line 236, in <module>
    main()
  File "examples/tacotron2/extract_duration.py", line 129, in main
    dataset=config["tacotron2_params"]["dataset"],
KeyError: 'dataset'
``` 

I installed the tacotron model with 
```
!gdown --id {"12jvEO1VqFo1ocrgY9GUHF_kVcLn3QaGW"} -O /content/tacotron2-120k.h5
!gdown --id {"1OI86hkN1YCpHBsIKnkELNbSho5Pj-pPY"} -O /content/tacotron2_config.yml
```

Any idea what causes this error? Help would be greatly appreciated.

**Comment by dathudeptrai** [comment]
@AdityaJain1030 did you preprocess dataset, what is the dataset you used ?. You should use the config in main repo here (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/tacotron2/conf/tacotron2.v1.yaml)

**Comment by AdityaJain1030** [comment]
Yep, I preprocessed the dataset first, with 
```
!tensorflow-tts-preprocess --rootdir /content/drive/MyDrive/TrumpSpeakDataset/ --outdir /content/dump_ljspeech --config /content/TensorFlowTTS/preprocess/ljspeech_preprocess.yaml --dataset ljspeech

!tensorflow-tts-normalize --rootdir /content/dump_ljspeech --outdir /content/dump_ljspeech --config /content/TensorFlowTTS/preprocess/ljspeech_preprocess.yaml --dataset ljspeech
```
Im currently changing the config to the one you linked, hopefully this makes a difference 🙂
