### ISSUE TITLE
local variable 'train_steps_per_epoch' referenced before assignment while trying to train fastspeech2

### ISSUE THREAD

**Issue by AdityaJain1030** [TensorSpeech/TensorFlowTTS#498]
I preprocessed a custom dataset for finetuning with fastspeech2. However, after running the command
```
!CUDA_VISIBLE_DEVICES=0 python examples/fastspeech2/train_fastspeech2.py \
  --train-dir /content/dump_ljspeech/train \
  --dev-dir /content/dump_ljspeech/valid/ \
  --outdir /content/TensorFlowTTS/examples/fastspeech2/exp/train.fastspeech2.v1/ \
  --config /content/TensorFlowTTS/examples/fastspeech2/conf/fastspeech2.v1.yaml \
  --use-norm 1 \
  --f0-stat /content/dump_ljspeech/stats_f0.npy \
  --energy-stat /content/dump_ljspeech/stats_energy.npy \
  --mixed_precision 1 \
  --resume "" \
  --pretrained /content/TTTS/fastspeech2-150k.h5
```
I get the error
```
Traceback (most recent call last):
  File "examples/fastspeech2/train_fastspeech2.py", line 417, in <module>
    main()
  File "examples/fastspeech2/train_fastspeech2.py", line 409, in main
    resume=args.resume,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 1010, in fit
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 104, in run
    self._train_epoch()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 139, in _train_epoch
    self.train_steps_per_epoch = train_steps_per_epoch
UnboundLocalError: local variable 'train_steps_per_epoch' referenced before assignment
[train]:   0% 0/200000 [00:00<?, ?it/s]
```

Any help with this issue would be greatly appreciated.

**Comment by AdityaJain1030** [comment]
Found the issue. My fine-tuning dataset ended up being smaller than my batch size 😁. Closing the Issue now

**Comment by PeijiYang** [comment]
hello, how to change the batch size for Tacotron2 trainging?

**Comment by PeijiYang** [comment]
> hello, how to change the batch size for Tacotron2 trainging?

hhhhh, I found it in config file.
