### ISSUE TITLE
FastSpeech2 - duration computation fails

### ISSUE THREAD

**Issue by t-dan** [TensorSpeech/TensorFlowTTS#554]
Hello,
I am trying to get FastSpeech2 working on LJS dataset. What I need is to extract duration files, using `examples/tacotron2/extract_duration.py` script.

However, when trying to run the script if fails with the error shown further. When I use the same model file (_checkpoints/model-200000.h5_) together with Tacotron2 to create speech (with melgan,mb-melgan,...), it works without problems.

Can I ask for a hint what may be wrong?

Thank you very much,
Dan T.

`+ python3 examples/tacotron2/extract_duration.py --rootdir ./datasets/data_LJS.preprocess/valid/ --outdir ./datasets/data_LJS.preprocess/valid/durations/ --checkpoint ./outputs/tacotron2_data_LJS.preprocess/exp/train.tacotron2.v1/checkpoints/model-200000.h5 --use-norm 1 --config ./outputs/tacotron2_data_LJS.preprocess/exp/train.tacotron2.v1/config.yml --batch-size 32 --win-front 3 --win-back 3`

```
2021-04-27 10:59:47.109421: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-04-27 10:59:50.605586: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs
2021-04-27 10:59:50.605629: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2021-04-27 10:59:50.605650: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (nympha.zcu.cz): /proc/driver/nvidia/version does not exist
2021-04-27 10:59:50.614993: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2199980000 Hz
2021-04-27 10:59:50.615535: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x58cef30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-27 10:59:50.615566: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[Extract Duration]: 0it [00:00, ?it/s]2021-04-27 10:59:54.106708: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: cond/branch_executed/_8
[Extract Duration]: 0it [00:06, ?it/s]
Traceback (most recent call last):
  File "examples/tacotron2/extract_duration.py", line 237, in <module>
    main()
  File "examples/tacotron2/extract_duration.py", line 166, in main
    training=True,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.CancelledError:    [_Derived_]Loop execution was cancelled.
         [[{{node while/LoopCond/_30}}]]
         [[tacotron2/encoder/bilstm/backward_lstm/PartitionedCall]] [Op:__inference_function_8697]

Function call stack:
function -> function -> function

```

**Comment by dathudeptrai** [comment]
@t-dan can you remove all data preprocessed folder and do preprocessing again :))), not sure what is the problem.

**Comment by ihshareef** [comment]
The issue is here:
`Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1:`
You need to fix your CUDA installation.
