### ISSUE TITLE
error building on arm64

### ISSUE THREAD

**Issue by roboticsai** [TensorSpeech/TensorFlowTTS#576]
I'm trying to build the TensorFlowTTS on raspberry pi 4B from source. I have succfully installed the Tensorflowtts but when i try to import the tensorflow_tts modules i'm getting error like:
```
>>> from tensorflow_tts.processor.ljspeech import LJSPEECH_SYMBOLS
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 44, in <module>
    from ._check_build import check_build  # noqa
ImportError: /home/ubuntu/.local/lib/python3.8/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tensorflow_tts/processor/__init__.py", line 3, in <module>
    from tensorflow_tts.processor.ljspeech import LJSpeechProcessor
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tensorflow_tts/processor/ljspeech.py", line 24, in <module>
    from tensorflow_tts.utils import cleaners
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tensorflow_tts/utils/__init__.py", line 12, in <module>
    from tensorflow_tts.utils.griffin_lim import TFGriffinLim, griffin_lim_lb
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tensorflow_tts/utils/griffin_lim.py", line 19, in <module>
    import librosa
  File "/home/ubuntu/.local/lib/python3.8/site-packages/librosa/__init__.py", line 213, in <module>
    from . import decompose
  File "/home/ubuntu/.local/lib/python3.8/site-packages/librosa/decompose.py", line 19, in <module>
    import sklearn.decomposition
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/__init__.py", line 81, in <module>
    from . import __check_build  # noqa: F401
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 46, in <module>
    raise_build_error(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 31, in raise_build_error
    raise ImportError("""%s
ImportError: /home/ubuntu/.local/lib/python3.8/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block
___________________________________________________________________________
Contents of /home/ubuntu/.local/lib/python3.8/site-packages/sklearn/__check_build:
__init__.py               setup.py                  _check_build.cpython-38-aarch64-linux-gnu.so
__pycache__
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.
```

Environment:
OS: ubuntu server 20.04
hardware: Raspberry pi 4B, 8 gb ram, arm64
Tensorflow version: Tensorflow 2.4.1.

**Comment by dathudeptrai** [comment]
@roboticsai seems a problem is about sklearn not from our side? . Pls try to re-install sklearn to newest version or build it from source.

**Comment by StuartIanNaylor** [comment]
Its prob dependencies of sklearn usually I run in a virtenv but to save me the hassle of working out what is needed  sudo apt-get install python3-sklearn brings in dependency needs then in my virtenv pip install and for me it works.

That is not specific for TfTTS its just something that happens with a pip install of sklearn on debian(s)

**Comment by roboticsai** [comment]
After installing scikit-learn from source this issue is solved. 
https://scikit-learn.org/stable/developers/advanced_installation.html

**Comment by TinoGuo** [comment]
Hi @roboticsai how do resolve the build error? I cloned the repo from the git and followed the step in https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/cpptflite, it throws me the error when try to execute `make`

```bash
/usr/bin/ld: CMakeFiles/demo.dir/src/MelGenerateTF.cpp.o: in function `MelGenerateTF::infer(std::vector<int, std::allocator<int> >)':
MelGenerateTF.cpp:(.text+0x1dc): undefined reference to `tflite::Interpreter::ResizeInputTensor(int, std::vector<int, std::allocator<int> > const&)'
/usr/bin/ld: MelGenerateTF.cpp:(.text+0x1f4): undefined reference to `tflite::Interpreter::AllocateTensors()'
/usr/bin/ld: MelGenerateTF.cpp:(.text+0x3b0): undefined reference to `tflite::Interpreter::Invoke()'
/usr/bin/ld: CMakeFiles/demo.dir/src/TfliteBase.cpp.o: in function `TfliteBase::~TfliteBase()':
TfliteBase.cpp:(.text+0x108): undefined reference to `tflite::Interpreter::~Interpreter()'
/usr/bin/ld: CMakeFiles/demo.dir/src/TfliteBase.cpp.o: in function `TfliteBase::interpreterBuild(char const*)':
TfliteBase.cpp:(.text+0x1b4): undefined reference to `tflite::InterpreterBuilder::InterpreterBuilder(tflite::FlatBufferModel const&, tflite::OpResolver const&)'
/usr/bin/ld: TfliteBase.cpp:(.text+0x1c0): undefined reference to `tflite::InterpreterBuilder::operator()(std::unique_ptr<tflite::Interpreter, std::default_delete<tflite::Interpreter> >*)'
/usr/bin/ld: TfliteBase.cpp:(.text+0x1d0): undefined reference to `tflite::InterpreterBuilder::~InterpreterBuilder()'
/usr/bin/ld: TfliteBase.cpp:(.text+0x244): undefined reference to `tflite::InterpreterBuilder::~InterpreterBuilder()'
/usr/bin/ld: CMakeFiles/demo.dir/src/TfliteBase.cpp.o: in function `TfliteBase::TfliteBase(char const*)':
TfliteBase.cpp:(.text+0x2c0): undefined reference to `tflite::Interpreter::~Interpreter()'
/usr/bin/ld: CMakeFiles/demo.dir/src/VocoderTF.cpp.o: in function `VocoderTF::infer(MelGenData)':
VocoderTF.cpp:(.text+0x30): undefined reference to `tflite::Interpreter::ResizeInputTensor(int, std::vector<int, std::allocator<int> > const&)'
/usr/bin/ld: VocoderTF.cpp:(.text+0x38): undefined reference to `tflite::Interpreter::AllocateTensors()'
/usr/bin/ld: VocoderTF.cpp:(.text+0x9c): undefined reference to `tflite::Interpreter::Invoke()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/demo.dir/build.make:175: demo] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/demo.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

thanks in advance!
