### ISSUE TITLE
Tacotron2 : Unresolved object in checkpoint

### ISSUE THREAD

**Issue by samuel-lunii** [TensorSpeech/TensorFlowTTS#590]
Hi :) 
I try to restore a checkpoint saved during Tacotron2 training. It used to work, but I have this error since I pulled the newest code : 

```
Traceback (most recent call last):
   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
     "__main__", mod_spec)
   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "/opt/ml/code/train_tacotron2.py", line 559, in <module>
     main()
   File "/opt/ml/code/train_tacotron2.py", line 551, in main
     resume=args.resume,
   File "/opt/ml/code/tensorflow_tts/trainers/base_trainer.py", line 1008, in fit
     self.load_checkpoint(resume)
   File "/opt/ml/code/tensorflow_tts/trainers/base_trainer.py", line 976, in load_checkpoint
     self.saved_path + "model-{}.h5".format(self.steps)
   File "/opt/ml/code/tensorflow_tts/utils/utils.py", line 102, in load_weights
     tf.io.gfile.copy(filepath, temp_file.name, overwrite=True)
   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 513, in copy_v2
     compat.as_bytes(src), compat.as_bytes(dst), overwrite)
 tensorflow.python.framework.errors_impl.AbortedError: All 10 retry attempts failed. The last failure: Unknown: : No response body.
 WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
 WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
 WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
 WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
```

Thanks for your help ! :) 🙏

**Comment by samuel-lunii** [comment]
I figured it out :) 
it does not come from a change in the code. The thing is that I was using a different path for `--outdir` and `--resume`. However, the [load_checkpoint() method in Seq2SeqBasedTrainer](https://github.com/TensorSpeech/TensorFlowTTS/blob/fbb0655e0ec7403e442baf7d2ce7c3ed1aa4cfed/tensorflow_tts/trainers/base_trainer.py#L976) takes the `saved_path` to load checkpoint, and not the one sent by `--resume`. I did not meet this problem before because I was using the same directory for both. 

Is it supposed to be that way or is it a mistake ?

**Comment by dathudeptrai** [comment]
@samuel-lunii see here (https://github.com/TensorSpeech/TensorFlowTTS/blob/fbb0655e0ec7403e442baf7d2ce7c3ed1aa4cfed/tensorflow_tts/trainers/base_trainer.py#L966). The `pretrained_path` used for restore `steps`, `epochs`, `optimizer` and `saved-path` used for load `.h5` file.
