### ISSUE TITLE
extract_duration.py error : Trying to access element 133 in a list with 133 elements.

### ISSUE THREAD

**Issue by samuel-lunii** [TensorSpeech/TensorFlowTTS#593]
Hi ! 
I'm trying to extract durations in order to train FS2. 
I tried with LJSpeech : 

```
TensorFlowTTS % CUDA_VISIBLE_DEVICES=0 python examples/tacotron2/extract_duration.py \
  --rootdir ./dump_ljspeech/valid/ \
  --outdir ./dump_ljspeech/valid/durations/ \
  --checkpoint /Users/samuel/Lunii/devPython/TensorFlowTTS/examples/tacotron2/checkpoints/LJ/model-132000.h5  \
  --use-norm 1 \
  --config ./examples/tacotron2/conf/tacotron2.v1.yaml \
  --batch-size 32 \
  --win-front 3 \
  --win-back 3
```

and got this error : 

```
Traceback (most recent call last):
  File "examples/tacotron2/extract_duration.py", line 272, in <module>
    main()
  File "examples/tacotron2/extract_duration.py", line 200, in main
    training=True,
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:    Trying to access element 133 in a list with 133 elements.
	 [[{{node while/body/_1/while/TensorArrayV2Read_1/TensorListGetItem}}]]
	 [[tacotron2/encoder/bilstm/forward_lstm/PartitionedCall]] [Op:__inference_function_8718]

Function call stack:
function -> function -> function
```

I tried all combinations of python (3.6, 3.7) and tensorflow (2.2.0, 2.3.1) versions, without any success :( 
Any clue ?

**Comment by dathudeptrai** [comment]
@samuel-lunii i think this is a bug of tensorflow, you need to reinstall it or upgrade to newest version or just remove the sample that make this bug.

**Comment by samuel-lunii** [comment]
@dathudeptrai Thanks :) 
I installed the latest version of tensorflow but the bug was still there.
I surrounded [this part of `extract_durations.py`](https://github.com/TensorSpeech/TensorFlowTTS/blob/978f397c244a4987e2aa11e5db8d1e5902332826/examples/tacotron2/extract_duration.py#L159-L232) with `try: except:`, set the batch size to 1, and every sample produces an error. 

Most of the time, the error is : 

```
Traceback (most recent call last):
  File "examples/tacotron2/extract_duration.py", line 276, in <module>
    main()
  File "examples/tacotron2/extract_duration.py", line 201, in main
    training=True,
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 957, in _call
    filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1961, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:    Trying to access element 105 in a list with 105 elements.
	 [[{{node while/body/_1/while/TensorArrayV2Read_1/TensorListGetItem}}]]
	 [[tacotron2/encoder/bilstm/backward_lstm/PartitionedCall]] [Op:__inference_function_8521]

Function call stack:
function -> function -> function
```

And sometimes, randomly, with the same sample, the error is : 

```
Traceback (most recent call last):
  File "examples/tacotron2/extract_duration.py", line 276, in <module>
    main()
  File "examples/tacotron2/extract_duration.py", line 201, in main
    training=True,
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 957, in _call
    filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1961, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)
  File "/Users/samuel/opt/anaconda3/envs/tensorflowTTS/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.CancelledError:    [_Derived_]Loop execution was cancelled.
	 [[{{node while/LoopCond/_30}}]]
	 [[tacotron2/encoder/bilstm/backward_lstm/PartitionedCall]] [Op:__inference_function_8521]

Function call stack:
function -> function -> function
```

**Comment by ihshareef** [comment]
Check if your CUDA/cuDNN installation is in order. I tried this out on Google Colab, and I got the same error which was resolved when I activated a GPU.

**Comment by samuel-lunii** [comment]
@ihshareef thank you !
You are right : I ran the code on a macbook pro, which has no NVIDIA GPU. 
The code runs on a VM correctly equipped :)
