### ISSUE TITLE
How to get Thorsten model as tflite file

### ISSUE THREAD

**Issue by TuniSenpao** [TensorSpeech/TensorFlowTTS#600]
Hey all,
I try to implement the TensorFlowTTS in my android app. But as far as I understand I need the Thorsten model as tflite file for it. So I tried to convert it with the given notebook but it doesn't worked for me. Maybe someone can help me with this problem and tell me how this works?
Thanks

**Comment by dathudeptrai** [comment]
@TuniSenpao what is ur bug ?

**Comment by TuniSenpao** [comment]
Well it seems like I could get the tflite file for the tacotron2 and melgan model with the help of the "TensorFlowTTS_Tacotron2_with_TFLite" notebook. But when I try to use the tacotron2.tflite file in the android app I get:
`java.lang.NullPointerException: Attempt to invoke virtual method 'void org.tensorflow.lite.Interpreter.resizeInput(int, int[])' on a null object reference
at com.tensorspeech.tensorflowtts.module.FastSpeech2.getMelSpectrogram(FastSpeech2.java:54)
        at com.tensorspeech.tensorflowtts.tts.InputWorker$InputText.proceed(InputWorker.java:86)
        at com.tensorspeech.tensorflowtts.tts.InputWorker$InputText.access$700(InputWorker.java:66)
        at com.tensorspeech.tensorflowtts.tts.InputWorker.lambda$new$0$InputWorker(InputWorker.java:43)
        at com.tensorspeech.tensorflowtts.tts.-$$Lambda$InputWorker$j9Bs3AGMTu4L2S_Dz69XKl4TEps.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)`

I thought I can just exchange the models but maybe this isn't possible

**Comment by FatimaZulfiqar** [comment]
Hi I am unable to convert tacotron2 and melgan model with the help of the "TensorFlowTTS_Tacotron2_with_TFLite" notebook. I am facing issues while importing a library. Can you please help me?
