### ISSUE TITLE
Error when installing TensorFlowTTS through pip

### ISSUE THREAD

**Issue by Edward205** [TensorSpeech/TensorFlowTTS#615]
I tried searching on google but couldn't find anything. If need anymore detailes ask me. Here is the error:
```
[edward@edward-manjaro tensorflow tts]$ pip3 install TensorFlowTTS
Defaulting to user installation because normal site-packages is not writeable
Collecting TensorFlowTTS
  Using cached TensorFlowTTS-1.6.1-py3-none-any.whl (126 kB)
Requirement already satisfied: tqdm>=4.26.1 in /home/edward/.local/lib/python3.9/site-packages (from TensorFlowTTS) (4.61.1)
Requirement already satisfied: setuptools>=38.5.1 in /usr/lib/python3.9/site-packages (from TensorFlowTTS) (57.0.0)
  Using cached TensorFlowTTS-1.6-py3-none-any.whl (126 kB)
Requirement already satisfied: tqdm>=4.26.1 in /home/edward/.local/lib/python3.9/site-packages (from TensorFlowTTS) (4.61.1)
Requirement already satisfied: setuptools>=38.5.1 in /usr/lib/python3.9/site-packages (from TensorFlowTTS) (57.0.0)
  Using cached TensorFlowTTS-1.1-py3-none-any.whl (121 kB)
Requirement already satisfied: tqdm>=4.26.1 in /home/edward/.local/lib/python3.9/site-packages (from TensorFlowTTS) (4.61.1)
Requirement already satisfied: setuptools>=38.5.1 in /usr/lib/python3.9/site-packages (from TensorFlowTTS) (57.0.0)
  Using cached TensorFlowTTS-0.11-py3-none-any.whl (118 kB)
Requirement already satisfied: tqdm>=4.26.1 in /home/edward/.local/lib/python3.9/site-packages (from TensorFlowTTS) (4.61.1)
Requirement already satisfied: setuptools>=38.5.1 in /usr/lib/python3.9/site-packages (from TensorFlowTTS) (57.0.0)
Requirement already satisfied: PyYAML>=3.12 in /usr/lib/python3.9/site-packages (from TensorFlowTTS) (5.4.1)
Requirement already satisfied: unidecode>=1.1.1 in /home/edward/.local/lib/python3.9/site-packages (from TensorFlowTTS) (1.2.0)
Collecting click
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Collecting dataclasses
  Using cached dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting g2p-en
  Using cached g2p_en-2.1.0-py3-none-any.whl (3.1 MB)
Requirement already satisfied: numpy>=1.13.1 in /home/edward/.local/lib/python3.9/site-packages (from g2p-en->TensorFlowTTS) (1.19.5)
Collecting distance>=0.1.3
  Using cached Distance-0.1.3.tar.gz (180 kB)
Collecting g2pM
  Using cached g2pM-0.1.2.5-py3-none-any.whl (1.7 MB)
Collecting h5py>=2.10.0
  Using cached h5py-3.3.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (4.5 MB)
Requirement already satisfied: numpy>=1.13.1 in /home/edward/.local/lib/python3.9/site-packages (from g2p-en->TensorFlowTTS) (1.19.5)
Collecting inflect>=4.1.0
  Using cached inflect-5.3.0-py3-none-any.whl (32 kB)
Collecting jamo>=0.4.1
  Using cached jamo-0.4.1-py3-none-any.whl (9.5 kB)
Collecting librosa>=0.7.0
  Using cached librosa-0.8.1-py3-none-any.whl (203 kB)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3.9/site-packages (from librosa>=0.7.0->TensorFlowTTS) (20.9)
Requirement already satisfied: numpy>=1.13.1 in /home/edward/.local/lib/python3.9/site-packages (from g2p-en->TensorFlowTTS) (1.19.5)
Collecting audioread>=2.0.0
  Using cached audioread-2.1.9.tar.gz (377 kB)
Collecting decorator>=3.0.0
  Using cached decorator-5.0.9-py3-none-any.whl (8.9 kB)
Collecting joblib>=0.14
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Collecting matplotlib>=3.1.0
  Using cached matplotlib-3.4.2-cp39-cp39-manylinux1_x86_64.whl (10.3 MB)
Requirement already satisfied: numpy>=1.13.1 in /home/edward/.local/lib/python3.9/site-packages (from g2p-en->TensorFlowTTS) (1.19.5)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3.9/site-packages (from matplotlib>=3.1.0->TensorFlowTTS) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3.9/site-packages (from matplotlib>=3.1.0->TensorFlowTTS) (8.2.0)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Requirement already satisfied: six in /home/edward/.local/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=3.1.0->TensorFlowTTS) (1.15.0)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.1-cp39-cp39-manylinux1_x86_64.whl (1.2 MB)
Collecting nltk>=3.2.4
  Using cached nltk-3.6.2-py3-none-any.whl (1.5 MB)
Requirement already satisfied: tqdm>=4.26.1 in /home/edward/.local/lib/python3.9/site-packages (from TensorFlowTTS) (4.61.1)
Collecting numba<=0.48
  Using cached numba-0.48.0.tar.gz (2.0 MB)
Requirement already satisfied: numpy>=1.13.1 in /home/edward/.local/lib/python3.9/site-packages (from g2p-en->TensorFlowTTS) (1.19.5)
Requirement already satisfied: setuptools>=38.5.1 in /usr/lib/python3.9/site-packages (from TensorFlowTTS) (57.0.0)
Collecting llvmlite<0.32.0,>=0.31.0dev0
  Using cached llvmlite-0.31.0.tar.gz (110 kB)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3.9/site-packages (from matplotlib>=3.1.0->TensorFlowTTS) (2.4.7)
Collecting pooch>=1.0
  Using cached pooch-1.4.0-py3-none-any.whl (51 kB)
Requirement already satisfied: requests in /usr/lib/python3.9/site-packages (from pooch>=1.0->librosa>=0.7.0->TensorFlowTTS) (2.25.1)
Requirement already satisfied: appdirs in /usr/lib/python3.9/site-packages (from pooch>=1.0->librosa>=0.7.0->TensorFlowTTS) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3.9/site-packages (from librosa>=0.7.0->TensorFlowTTS) (20.9)
Collecting pypinyin
  Using cached pypinyin-0.42.0-py2.py3-none-any.whl (1.3 MB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Requirement already satisfied: six in /home/edward/.local/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=3.1.0->TensorFlowTTS) (1.15.0)
Collecting pyworld>=0.2.10
  Using cached pyworld-0.3.0-cp39-cp39-linux_x86_64.whl
Requirement already satisfied: numpy>=1.13.1 in /home/edward/.local/lib/python3.9/site-packages (from g2p-en->TensorFlowTTS) (1.19.5)
Collecting cython>=0.24.0
  Using cached Cython-0.29.23-cp39-cp39-manylinux1_x86_64.whl (1.9 MB)
Collecting regex
  Using cached regex-2021.7.6-cp39-cp39-manylinux2014_x86_64.whl (733 kB)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.9/site-packages (from requests->pooch>=1.0->librosa>=0.7.0->TensorFlowTTS) (4.0.0)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.9/site-packages (from requests->pooch>=1.0->librosa>=0.7.0->TensorFlowTTS) (3.2)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.9/site-packages (from requests->pooch>=1.0->librosa>=0.7.0->TensorFlowTTS) (1.26.5)
Collecting resampy>=0.2.2
  Using cached resampy-0.2.2.tar.gz (323 kB)
Requirement already satisfied: numpy>=1.13.1 in /home/edward/.local/lib/python3.9/site-packages (from g2p-en->TensorFlowTTS) (1.19.5)
Requirement already satisfied: six in /home/edward/.local/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=3.1.0->TensorFlowTTS) (1.15.0)
Collecting scikit-learn>=0.22.0
  Using cached scikit_learn-0.24.2-cp39-cp39-manylinux2010_x86_64.whl (23.8 MB)
Requirement already satisfied: numpy>=1.13.1 in /home/edward/.local/lib/python3.9/site-packages (from g2p-en->TensorFlowTTS) (1.19.5)
Collecting scipy>=1.0.0
  Using cached scipy-1.7.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (28.4 MB)
Requirement already satisfied: numpy>=1.13.1 in /home/edward/.local/lib/python3.9/site-packages (from g2p-en->TensorFlowTTS) (1.19.5)
Collecting soundfile>=0.10.2
  Using cached SoundFile-0.10.3.post1-py2.py3-none-any.whl (21 kB)
Requirement already satisfied: cffi>=1.0 in /usr/lib/python3.9/site-packages (from soundfile>=0.10.2->TensorFlowTTS) (1.14.5)
Requirement already satisfied: pycparser in /usr/lib/python3.9/site-packages (from cffi>=1.0->soundfile>=0.10.2->TensorFlowTTS) (2.20)
Collecting tensorflow-addons>=0.10.0
  Using cached tensorflow_addons-0.13.0-cp39-cp39-manylinux2010_x86_64.whl (679 kB)
Collecting tensorflow-gpu>=2.3.1
  Using cached tensorflow_gpu-2.5.0-cp39-cp39-manylinux2010_x86_64.whl (454.4 MB)
Requirement already satisfied: numpy>=1.13.1 in /home/edward/.local/lib/python3.9/site-packages (from g2p-en->TensorFlowTTS) (1.19.5)
Requirement already satisfied: six in /home/edward/.local/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=3.1.0->TensorFlowTTS) (1.15.0)
Collecting absl-py~=0.10
  Using cached absl_py-0.13.0-py3-none-any.whl (132 kB)
Requirement already satisfied: six in /home/edward/.local/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=3.1.0->TensorFlowTTS) (1.15.0)
Collecting astunparse~=1.6.3
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: six in /home/edward/.local/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=3.1.0->TensorFlowTTS) (1.15.0)
Collecting flatbuffers~=1.12.0
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Collecting gast==0.4.0
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting google-pasta~=0.2
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Requirement already satisfied: six in /home/edward/.local/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=3.1.0->TensorFlowTTS) (1.15.0)
Collecting grpcio~=1.34.0
  Using cached grpcio-1.34.1-cp39-cp39-manylinux2014_x86_64.whl (4.0 MB)
Requirement already satisfied: six in /home/edward/.local/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=3.1.0->TensorFlowTTS) (1.15.0)
Collecting h5py>=2.10.0
  Using cached h5py-3.1.0-cp39-cp39-manylinux1_x86_64.whl (4.4 MB)
Requirement already satisfied: numpy>=1.13.1 in /home/edward/.local/lib/python3.9/site-packages (from g2p-en->TensorFlowTTS) (1.19.5)
Collecting keras-nightly~=2.5.0.dev
  Using cached keras_nightly-2.5.0.dev2021032900-py2.py3-none-any.whl (1.2 MB)
Collecting keras-preprocessing~=1.1.2
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Requirement already satisfied: six in /home/edward/.local/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=3.1.0->TensorFlowTTS) (1.15.0)
Requirement already satisfied: numpy>=1.13.1 in /home/edward/.local/lib/python3.9/site-packages (from g2p-en->TensorFlowTTS) (1.19.5)
Collecting opt-einsum~=3.3.0
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Requirement already satisfied: numpy>=1.13.1 in /home/edward/.local/lib/python3.9/site-packages (from g2p-en->TensorFlowTTS) (1.19.5)
Collecting protobuf>=3.9.2
  Using cached protobuf-3.17.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
Requirement already satisfied: six in /home/edward/.local/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=3.1.0->TensorFlowTTS) (1.15.0)
Collecting tensorboard~=2.5
  Using cached tensorboard-2.5.0-py3-none-any.whl (6.0 MB)
Requirement already satisfied: setuptools>=38.5.1 in /usr/lib/python3.9/site-packages (from TensorFlowTTS) (57.0.0)
Requirement already satisfied: requests in /usr/lib/python3.9/site-packages (from pooch>=1.0->librosa>=0.7.0->TensorFlowTTS) (2.25.1)
Requirement already satisfied: numpy>=1.13.1 in /home/edward/.local/lib/python3.9/site-packages (from g2p-en->TensorFlowTTS) (1.19.5)
Requirement already satisfied: markdown>=2.6.8 in /usr/lib/python3.9/site-packages (from tensorboard~=2.5->tensorflow-gpu>=2.3.1->TensorFlowTTS) (3.3.4)
Collecting google-auth<2,>=1.6.3
  Using cached google_auth-1.32.1-py2.py3-none-any.whl (147 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/edward/.local/lib/python3.9/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow-gpu>=2.3.1->TensorFlowTTS) (0.2.8)
Requirement already satisfied: setuptools>=38.5.1 in /usr/lib/python3.9/site-packages (from TensorFlowTTS) (57.0.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/edward/.local/lib/python3.9/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow-gpu>=2.3.1->TensorFlowTTS) (4.2.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/edward/.local/lib/python3.9/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow-gpu>=2.3.1->TensorFlowTTS) (4.7.2)
Requirement already satisfied: six in /home/edward/.local/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=3.1.0->TensorFlowTTS) (1.15.0)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.4-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/edward/.local/lib/python3.9/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.5->tensorflow-gpu>=2.3.1->TensorFlowTTS) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/edward/.local/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow-gpu>=2.3.1->TensorFlowTTS) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /home/edward/.local/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.5->tensorflow-gpu>=2.3.1->TensorFlowTTS) (3.1.1)
Requirement already satisfied: requests in /usr/lib/python3.9/site-packages (from pooch>=1.0->librosa>=0.7.0->TensorFlowTTS) (2.25.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/edward/.local/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow-gpu>=2.3.1->TensorFlowTTS) (0.4.8)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Using cached tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
Collecting tensorflow-estimator<2.6.0,>=2.5.0rc0
  Using cached tensorflow_estimator-2.5.0-py2.py3-none-any.whl (462 kB)
Collecting termcolor~=1.1.0
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
Collecting textgrid
  Using cached TextGrid-1.5-py3-none-any.whl (10.0 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting typeguard>=2.7
  Using cached typeguard-2.12.1-py3-none-any.whl (17 kB)
Collecting typing-extensions~=3.7.4
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-2.0.1-py3-none-any.whl (288 kB)
Collecting wheel~=0.35
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting wrapt~=1.12.1
  Using cached wrapt-1.12.1.tar.gz (27 kB)
Using legacy 'setup.py install' for distance, since package 'wheel' is not installed.
Using legacy 'setup.py install' for audioread, since package 'wheel' is not installed.
Using legacy 'setup.py install' for numba, since package 'wheel' is not installed.
Using legacy 'setup.py install' for llvmlite, since package 'wheel' is not installed.
Using legacy 'setup.py install' for resampy, since package 'wheel' is not installed.
Using legacy 'setup.py install' for termcolor, since package 'wheel' is not installed.
Using legacy 'setup.py install' for wrapt, since package 'wheel' is not installed.
Installing collected packages: llvmlite, google-auth, wheel, werkzeug, threadpoolctl, tensorboard-plugin-wit, tensorboard-data-server, scipy, regex, protobuf, numba, joblib, grpcio, google-auth-oauthlib, click, absl-py, wrapt, typing-extensions, typeguard, termcolor, tensorflow-estimator, tensorboard, soundfile, scikit-learn, resampy, python-dateutil, pooch, opt-einsum, nltk, kiwisolver, keras-preprocessing, keras-nightly, inflect, h5py, google-pasta, gast, flatbuffers, distance, decorator, cython, cycler, audioread, astunparse, textgrid, tensorflow-gpu, tensorflow-addons, pyworld, pypinyin, matplotlib, librosa, jamo, g2pM, g2p-en, dataclasses, TensorFlowTTS
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.36.0
    Uninstalling llvmlite-0.36.0:
      Successfully uninstalled llvmlite-0.36.0
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9g4cb8xt/llvmlite_1b7c8a50558d48279f7e97c35fd69f6a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9g4cb8xt/llvmlite_1b7c8a50558d48279f7e97c35fd69f6a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4y52nldf/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/edward/.local/include/python3.9/llvmlite                                                      
         cwd: /tmp/pip-install-9g4cb8xt/llvmlite_1b7c8a50558d48279f7e97c35fd69f6a/              
    Complete output (29 lines):                                                                 
    running install                                                                             
    running build                                                                               
    got version from file /tmp/pip-install-9g4cb8xt/llvmlite_1b7c8a50558d48279f7e97c35fd69f6a/llvmlite/_version.py {'version': '0.31.0', 'full': 'fe7d985f6421d87f613bd414479d29d912771562'}    
    running build_ext                                                                           
    /usr/bin/python /tmp/pip-install-9g4cb8xt/llvmlite_1b7c8a50558d48279f7e97c35fd69f6a/ffi/build.py                                                                                            
    LLVM version... Traceback (most recent call last):                                          
      File "/tmp/pip-install-9g4cb8xt/llvmlite_1b7c8a50558d48279f7e97c35fd69f6a/ffi/build.py", line 105, in main_posix                                                                          
        out = subprocess.check_output([llvm_config, '--version'])                               
      File "/usr/lib/python3.9/subprocess.py", line 424, in check_output                        
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,                        
      File "/usr/lib/python3.9/subprocess.py", line 505, in run                                 
        with Popen(*popenargs, **kwargs) as process:                                            
      File "/usr/lib/python3.9/subprocess.py", line 951, in __init__                            
        self._execute_child(args, executable, preexec_fn, close_fds,                            
      File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child                     
        raise child_exception_type(errno_num, err_msg, err_filename)                            
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'                       
                                                                                                
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-9g4cb8xt/llvmlite_1b7c8a50558d48279f7e97c35fd69f6a/ffi/build.py", line 168, in <module>
        main()
      File "/tmp/pip-install-9g4cb8xt/llvmlite_1b7c8a50558d48279f7e97c35fd69f6a/ffi/build.py", line 158, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-9g4cb8xt/llvmlite_1b7c8a50558d48279f7e97c35fd69f6a/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python' failed with exit code 1
    ----------------------------------------
  Rolling back uninstall of llvmlite
  Moving to /home/edward/.local/lib/python3.9/site-packages/llvmlite-0.36.0.dist-info/
   from /home/edward/.local/lib/python3.9/site-packages/~lvmlite-0.36.0.dist-info
  Moving to /home/edward/.local/lib/python3.9/site-packages/llvmlite/
   from /home/edward/.local/lib/python3.9/site-packages/~lvmlite
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9g4cb8xt/llvmlite_1b7c8a50558d48279f7e97c35fd69f6a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9g4cb8xt/llvmlite_1b7c8a50558d48279f7e97c35fd69f6a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4y52nldf/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/edward/.local/include/python3.9/llvmlite Check the logs for full command output.
[edward@edward-manjaro tensorflow tts]$ 
```

**Comment by Geigerkind** [comment]
I  managed to install it using the master and adjusting the setup params:
install": [
        "tensorflow-gpu>=2.3.1",
        "tensorflow-addons>=0.10.0",
        "setuptools>=38.5.1",
        "huggingface_hub==0.0.8",
        "librosa>=0.7.0",
        "soundfile>=0.10.2",
        "matplotlib>=3.1.0",
        "PyYAML>=3.12",
        "tqdm>=4.26.1",
        "h5py>=2.10.0",
        "unidecode>=1.1.1",
        "inflect>=4.1.0",
        "scikit-learn>=0.22.0",
        "pyworld>=0.2.10",
        "numba==0.53.1",  # Fix No module named "numba.decorators"
        "jamo>=0.4.1",
        "pypinyin",
        "g2pM",
        "textgrid",
        "click",
        "g2p_en",
        "dataclasses",
    ],

**Comment by Edward205** [comment]
@Geigerkind I did that and it worked. Thanks

**Comment by 19991004** [comment]
> @Geigerkind我做到了，它奏效了。谢谢

大佬，我是小白，我想问一下你安装这个TTS的时候是直接在cmd客户端python环境下用pip命令吗，我用了好多此都是无效命令
