### ISSUE TITLE
Question: How to record your own voice such that this framework works?

### ISSUE THREAD

**Issue by Geigerkind** [TensorSpeech/TensorFlowTTS#620]
Hi!
I tried to record my own voice using https://github.com/MycroftAI/mimic-recording-studio and my headset and microphone.

With either microphone I got the following error when attempting to preprocess some files:
```
/home/shino/.local/bin/tensorflow-tts-preprocess --rootdir ./datasets/shino --outdir ./dump_shino --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech
2021-07-12 18:19:44.738527: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-12 18:19:46,428 (preprocess:373) INFO: Selected 'ljspeech' processor.
2021-07-12 18:19:46,429 (preprocess:412) INFO: Training items: 53
2021-07-12 18:19:46,429 (preprocess:413) INFO: Validation items: 3
[Preprocessing train]:   0%|                                                                                                                                                                                     | 0/53 [00:00<?, ?it/s]multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/shino/.local/lib/python3.9/site-packages/tensorflow_tts/bin/preprocess.py", line 192, in gen_audio_features
    assert len(audio.shape) == 1, f"{utt_id} seems to be multi-channel signal."
AssertionError: 7c197c123ddcabc66b7d02ce484663d8 seems to be multi-channel signal.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shino/.local/bin/tensorflow-tts-preprocess", line 8, in <module>
    sys.exit(preprocess())
  File "/home/shino/.local/lib/python3.9/site-packages/tensorflow_tts/bin/preprocess.py", line 446, in preprocess
    for result, mel, energy, f0, features in train_map:
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
AssertionError: 7c197c123ddcabc66b7d02ce484663d8 seems to be multi-channel signal.
[Preprocessing train]:  36%|█████████████████████████████████████████████████████████████▎                                                                                                             | 19/53 [00:00<00:00, 276.02it/s]

```

So how exactly do I need to record my voice such that I can produce valid files?

Cheers!

**Comment by Geigerkind** [comment]
nvm. Used pydub to convert it to mono channel input.
