### ISSUE TITLE
File is not a zip file r1.6.1

### ISSUE THREAD

**Issue by Cosjimmy** [TensorSpeech/TensorFlowTTS#642]
I am using centOS7 cuda 10.1, python 3.7.4 and I cloned the project r1.6.1 and used baker dataset I ran the following script:

tensorflow-tts-preprocess --rootdir ./baker --outdir ./dump_baker --config preprocess/baker_preprocess.yaml --dataset baker

but  encountered the following issue:

2021-08-05 14:50:15.439306: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/data/apps/yqg/anaconda3/envs/tensorflowtts/bin/tensorflow-tts-preprocess", line 5, in <module>
    from tensorflow_tts.bin.preprocess import preprocess
  File "/data/apps/yqg/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow_tts/bin/preprocess.py", line 33, in <module>
    from tensorflow_tts.processor import LJSpeechProcessor
  File "/data/apps/yqg/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow_tts/processor/__init__.py", line 6, in <module>
    from tensorflow_tts.processor.libritts import LibriTTSProcessor
  File "/data/apps/yqg/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/tensorflow_tts/processor/libritts.py", line 24, in <module>
    from g2p_en import g2p as grapheme_to_phonem
  File "/data/apps/yqg/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/g2p_en/__init__.py", line 1, in <module>
    from .g2p import G2p
  File "/data/apps/yqg/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/g2p_en/g2p.py", line 22, in <module>
    nltk.data.find('taggers/averaged_perceptron_tagger.zip')
  File "/data/apps/yqg/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/nltk/data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "/data/apps/yqg/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/data/apps/yqg/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/nltk/data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/data/apps/yqg/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/data/apps/yqg/anaconda3/envs/tensorflowtts/lib/python3.7/site-packages/nltk/data.py", line 934, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/data/apps/yqg/anaconda3/envs/tensorflowtts/lib/python3.7/zipfile.py", line 1225, in __init__
    self._RealGetContents()
  File "/data/apps/yqg/anaconda3/envs/tensorflowtts/lib/python3.7/zipfile.py", line 1292, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Is there anyone has the same issue or if there is a way to fix this? Thanks!

**Comment by Cosjimmy** [comment]
Nevermind, I tried Ubuntu, and it works now
