### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: No algorithm worked! [Op:Conv2D]

### ISSUE THREAD

**Issue by jialesmu** [TensorSpeech/TensorFlowTTS#655]
OP_REQUIRES failed at conv_ops.cc:1094 : Not found: No algorithm worked!

Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    fastspeech2 = TFAutoModel.from_pretrained("tensorspeech/tts-fastspeech2-ljspeech-en")
  File "/home/TensorFlowTTS/tensorflow_tts/inference/auto_model.py", line 104, in from_pretrained
    model._build()
  File "/home/TensorFlowTTS/tensorflow_tts/inference/savable_models.py", line 77, in _build
    self([input_ids, speaker_ids, speed_ratios, f0_ratios, energy_ratios])
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1007, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/TensorFlowTTS/tensorflow_tts/inference/savable_models.py", line 67, in call
    return super()._inference(
  File "/home/TensorFlowTTS/tensorflow_tts/models/fastspeech2.py", line 224, in _inference
    encoder_output = self.encoder(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1007, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/agree/jz/TensorFlowTTS/tensorflow_tts/models/fastspeech.py", line 445, in call
    layer_outputs = layer_module(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1007, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/TensorFlowTTS/tensorflow_tts/models/fastspeech.py", line 407, in call
    intermediate_output = self.intermediate(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1007, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/TensorFlowTTS/tensorflow_tts/models/fastspeech.py", line 359, in call
    hidden_states = self.conv1d_1(hidden_states)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1007, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 248, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/nn_ops.py", line 1013, in convolution_v2
    return convolution_internal(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/nn_ops.py", line 1143, in convolution_internal
    return op(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/deprecation.py", line 605, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/deprecation.py", line 605, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/nn_ops.py", line 1885, in conv1d
    result = gen_nn_ops.conv2d(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 932, in conv2d
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: No algorithm worked! [Op:Conv2D]

yesterday it works fine, however, now its not work, i didnt change everything, what cause this problem?

**Comment by ZDisket** [comment]
@jialesmu Are you using GPU? If so, try 
```
import tensorflow as tf
physical_devices = tf.config.list_physical_devices('GPU') 
tf.config.experimental.set_memory_growth(physical_devices[0], True)
```

**Comment by jialesmu** [comment]
> @jialesmu Are you using GPU? If so, try
> 
> ```
> import tensorflow as tf
> physical_devices = tf.config.list_physical_devices('GPU') 
> tf.config.experimental.set_memory_growth(physical_devices[0], True)
> ```

it is not work this way, however, i fix this problem by reinstall the .h5 file and it solved.
it seems .h5 file damaged someway.
thanks for your help~
