### ISSUE TITLE
KeyError: '@Gallantry' while running preprocessing command

### ISSUE THREAD

**Issue by mlrober** [TensorSpeech/TensorFlowTTS#662]
Hi Team,

I have tried to replicate training fastspeech2 from scratch with libritts dataset.
I have followed the steps in the repo as follows:

Step1: Run the dataset on this Jupyter Notebook: https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/fastspeech2_libritts/libri_experiment/prepare_libri.ipynb
Step2: then i have cloned the repo and ran setup.py install
Step3: Created "Train.txt" file
Step4: Executed below command !tensorflow-tts-preprocess --rootdir ./libritts --outdir ./dump_lib --config ./TensorFlowTTS/preprocess/libritts_preprocess.yaml --dataset libritts

When i ran the above command i got following error:

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package cmudict to /root/nltk_data...
[nltk_data]   Package cmudict is already up-to-date!
2021-09-04 16:58:25,164 (preprocess:378) INFO: Selected 'libritts' processor.
2021-09-04 16:58:25,174 (preprocess:417) INFO: Training items: 1267
2021-09-04 16:58:25,174 (preprocess:418) INFO: Validation items: 67
[Preprocessing train]:   0% 0/1267 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/tensorflow-tts-preprocess", line 33, in <module>
    sys.exit(load_entry_point('TensorFlowTTS==0.0', 'console_scripts', 'tensorflow-tts-preprocess')())
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_tts/bin/preprocess.py", line 451, in preprocess
    for result, mel, energy, f0, features in train_map:
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 354, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 140, in _helper_reraises_exception
    raise ex
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 292, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 528, in _get_tasks
    x = tuple(itertools.islice(it, size))
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_tts/bin/preprocess.py", line 431, in iterator_data
    yield processor.get_one_sample(item)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_tts/processor/libritts.py", line 74, in get_one_sample
    text_ids = np.asarray(self.text_to_sequence(text), np.int32)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_tts/processor/libritts.py", line 98, in text_to_sequence
    return self.symbols_to_ids(self.clean_g2p(text.split(" ")))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_tts/processor/libritts.py", line 106, in symbols_to_ids
    return [self.symbol_to_id[s] for s in symbols_list]
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_tts/processor/libritts.py", line 106, in <listcomp>
    return [self.symbol_to_id[s] for s in symbols_list]
KeyError: '@Gallantry'

I have used google colab with gpu as runtime
Here's the link to Google Colab Notebook https://colab.research.google.com/drive/1TiEZTlG05MHkIna9P-BuYaNlK5YmyoJ7?usp=sharing

Kindly help me to progress on this issue

**Comment by mlrober** [comment]
Hi Team,

Is this bug is fixed?
