### ISSUE TITLE
InvalidArgumentError during training Tacotron2 on German multi-speaker dataset

### ISSUE THREAD

**Issue by Mareike-RTY** [TensorSpeech/TensorFlowTTS#687]
Hi, I am trying to train Tacotron2 on a multi-speaker German dataset (4 speakers, 13 hours of audio material for now). I preprocessed it with the `thorsten` processor and adjusted the config files according to [this](https://github.com/ZDisket/TensorflowTTS/commit/616a70cb3981771bdfcd44e8a1d7c5f5dd7d1fd5#diff-9a53aa155125bb4b5f51f8d85f2fe438ca461b7ec88dfa27acd04dfd8712e790) guide in terms of multi-speaker TTS.
After triggering training, it runs for 18 seconds, then I get the following error: ```tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:    Trying to access element 188 in a list with 188 elements.```
After multiple runs, the number of elements changes, e.g. 179 instead of 188.
I tried debugging but cannot reproduce this error, and I do not know what exactly to adjust in the respective config files or scripts.
Could someone please point me into the right direction, what might cause this error and how to possibly fix it?

Thank you very much for any help!

The relevant part of the logs:
```
2021-10-13 09:55:19.452580: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-10-13 09:55:19.452590: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2021-10-13 09:55:19.452600: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
Please install Tensorflow that supports GPU
2021-10-13 09:55:19.454477: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-10-13 09:55:19.454495: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      
Using Multi-Speaker
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: hop_size = 256
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: format = npy
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: model_type = tacotron2
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: tacotron2_params = {'dataset': 'ljspeech', 'embedding_hidden_size': 512, 'initializer_range': 0.02, 'embedding_dropout_prob': 0.1, 'n_speakers': 1, 'n_conv_encoder': 5, 'encoder_conv_filters': 512, 'encoder_conv_kernel_sizes': 5, 'encoder_conv_activation': 'relu', 'encoder_conv_dropout_rate': 0.5, 'encoder_lstm_units': 256, 'n_prenet_layers': 2, 'prenet_units': 256, 'prenet_activation': 'relu', 'prenet_dropout_rate': 0.5, 'n_lstm_decoder': 1, 'reduction_factor': 1, 'decoder_lstm_units': 1024, 'attention_dim': 128, 'attention_filters': 32, 'attention_kernel': 31, 'n_mels': 80, 'n_conv_postnet': 5, 'postnet_conv_filters': 512, 'postnet_conv_kernel_sizes': 5, 'postnet_dropout_rate': 0.1, 'attention_type': 'lsa'}
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: batch_size = 32
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: remove_short_samples = True
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: allow_cache = True
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: mel_length_threshold = 32
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: is_shuffle = True
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: use_fixed_shapes = True
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: optimizer_params = {'initial_learning_rate': 0.001, 'end_learning_rate': 1e-05, 'decay_steps': 150000, 'warmup_proportion': 0.02, 'weight_decay': 0.001}
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: gradient_accumulation_steps = 1
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: var_train_expr = None
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: train_max_steps = 200000
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: save_interval_steps = 2000
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: eval_interval_steps = 500
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: log_interval_steps = 200
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: start_schedule_teacher_forcing = 200001
2021-10-13 09:55:21,333 (train_tacotron2:455) INFO: start_ratio_value = 0.5
2021-10-13 09:55:21,334 (train_tacotron2:455) INFO: schedule_decay_steps = 50000
2021-10-13 09:55:21,334 (train_tacotron2:455) INFO: end_ratio_value = 0.0
2021-10-13 09:55:21,334 (train_tacotron2:455) INFO: num_save_intermediate_results = 1
2021-10-13 09:55:21,334 (train_tacotron2:455) INFO: train_dir = ./dump/train/
2021-10-13 09:55:21,334 (train_tacotron2:455) INFO: dev_dir = ./dump/valid/
2021-10-13 09:55:21,334 (train_tacotron2:455) INFO: use_norm = True
2021-10-13 09:55:21,334 (train_tacotron2:455) INFO: outdir = ./examples/tacotron2/exp/train.tacotron2.v1/
2021-10-13 09:55:21,334 (train_tacotron2:455) INFO: config = ./examples/tacotron2/conf/tacotron2.v1.yaml
2021-10-13 09:55:21,334 (train_tacotron2:455) INFO: resume = 
2021-10-13 09:55:21,334 (train_tacotron2:455) INFO: verbose = 1
2021-10-13 09:55:21,334 (train_tacotron2:455) INFO: mixed_precision = False
2021-10-13 09:55:21,334 (train_tacotron2:455) INFO: pretrained = 
2021-10-13 09:55:21,334 (train_tacotron2:455) INFO: version = 1.6.1
2021-10-13 09:55:21,334 (train_tacotron2:455) INFO: max_mel_length = 1443
2021-10-13 09:55:21,334 (train_tacotron2:455) INFO: max_char_length = 274
Using Multi-Speaker
Model: "tacotron2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
encoder (TFTacotronEncoder)  multiple                  8218624   
_________________________________________________________________
decoder_cell (TFTacotronDeco multiple                  18246402  
_________________________________________________________________
post_net (TFTacotronPostnet) multiple                  5460480   
_________________________________________________________________
residual_projection (Dense)  multiple                  41040     
=================================================================
Total params: 31,966,546
Trainable params: 31,956,306
Non-trainable params: 10,240
_________________________________________________________________
[train]:   0%|                                                                         | 0/200000 [00:00<?, ?it/s]2021-10-13 09:55:23.445255: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: cond/branch_executed/_8
Traceback (most recent call last):
  File "examples/tacotron2/train_tacotron2.py", line 548, in <module>
    main()
  File "examples/tacotron2/train_tacotron2.py", line 536, in main
    trainer.fit(
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow_tts/trainers/base_trainer.py", line 1010, in fit
    self.run()
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow_tts/trainers/base_trainer.py", line 104, in run
    self._train_epoch()
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow_tts/trainers/base_trainer.py", line 126, in _train_epoch
    self._train_step(batch)
  File "examples/tacotron2/train_tacotron2.py", line 127, in _train_step
    self.one_step_forward(batch)
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545, in call
    outputs = execute.execute(
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:    Trying to access element 188 in a list with 188 elements.
	 [[{{node while_19/body/_1/while/TensorArrayV2Read_1/TensorListGetItem}}]]
	 [[tacotron2/encoder/bilstm/forward_lstm/PartitionedCall]] [Op:__inference__one_step_forward_23979]

Function call stack:
_one_step_forward -> _one_step_forward -> _one_step_forward

[train]:   0%|                                                                         | 0/200000 [00:18<?, ?it/s]
```

**Comment by Aksh97** [comment]
Hi, any solution for this?
