### ISSUE TITLE
 decode_tacotron2.py Problem

### ISSUE THREAD

**Issue by LLianJJun** [TensorSpeech/TensorflowTTS#70]
Hi~
After training tacotron2 with my data, the following problems occur during decoding.

Does anyone know the answer to this problem?

```
CUDA_VISIBLE_DEVICES=3 python ./decode_tacotron2.py   --rootdir ./dump/valid/   --outdir ./prediction/tacotron2-75k/ 
--checkpoint ./examples/tacotron2/exp/train.tacotron2.v1/checkpoints/model-75000.h5 
--config ./examples/tacotron2/conf/tacotron2.v1.yaml   --batch-size 32
```

```
2020-06-30 13:31:07.511973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-30 13:31:07.512004: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2020-06-30 13:31:07.512024: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2020-06-30 13:31:07.516529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21397 MB memory) -> physical GPU (device: 0, name: Tesla P40, pci bus id: 0000:08:00.0, compute capability: 6.1)
2020-06-30 13:31:28.713565: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-30 13:31:28.964408: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
[Decoding]: 0it [00:00, ?it/s]2020-06-30 13:31:34.449436: W tensorflow/core/kernels/data/cache_dataset_ops.cc:794] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
[Decoding]: 0it [00:03, ?it/s]
Traceback (most recent call last):
  File "./decode_tacotron2.py", line 135, in <module>
    main()
  File "./decode_tacotron2.py", line 116, in main
    speaker_ids=tf.zeros(shape=[tf.shape(charactor)[0]]),
  File "/data/nlp/ihkim/miniconda2/envs/data_TensorflowTTS/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/data/nlp/ihkim/miniconda2/envs/data_TensorflowTTS/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 648, in _call
    *args, **kwds)
  File "/data/nlp/ihkim/miniconda2/envs/data_TensorflowTTS/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2238, in canonicalize_function_inputs
    self._flat_input_signature)
  File "/data/nlp/ihkim/miniconda2/envs/data_TensorflowTTS/lib/python3.6/site-
packages/tensorflow/python/eager/function.py", line 2305, in _convert_inputs_to_signature
    format_error_message(inputs, input_signature))
ValueError: Python inputs incompatible with input_signature:
  inputs: (
    tf.Tensor(
[[ 0 13 27 ...  0  0  0]
 [ 0 20 27 ...  0  0  0]
 [ 0  8 26 ...  0  0  0]
 ...
 [ 0  2 29 ...  0  0  0]
 [ 0 11 34 ...  0  0  0]
 [ 0  9 21 ...  0  0  0]], shape=(32, 134), dtype=int32),
    tf.Tensor(
[ 29  25  17  26  23  52  11  21  22  37 102  76  54  45 130  59  39  36
  20  47  31  43  45 134 101  53  80  73 112 114  16 114], shape=(32,), dtype=int32),
    tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.], shape=(32,), dtype=float32))
  input_signature: (
    TensorSpec(shape=(None, None), dtype=tf.int32, name=None),
    TensorSpec(shape=(None,), dtype=tf.int32, name=None),
    TensorSpec(shape=(None,), dtype=tf.int32, name=None))
```

**Comment by dathudeptrai** [comment]
@LLianJJun i will check it after lunch :))

**Comment by dathudeptrai** [comment]
@LLianJJun ok i fixed it, the problem is that speaker_id need dtype=tf.int32 to be able feed to tacotron.inference. :D
