### ISSUE TITLE
"Invalid argument:  required broadcastable shapes" when trying to train FS2

### ISSUE THREAD

**Issue by godspirit00** [TensorSpeech/TensorFlowTTS#732]
I was trying to train Fastspeech 2 on the [Nancy Corpus](https://www.cstr.ed.ac.uk/projects/blizzard/2011/lessac_blizzard2011/). I extracted the durations with MFA, and did preprocessing as described in the README. But when I start training, I met the following error:
```
2022-01-06 15:31:18.739332: W tensorflow/core/framework/op_kernel.cc:1680] Invalid argument: required broadcastable shapes
Traceback (most recent call last):
  File "examples/fastspeech2/train_fastspeech2.py", line 417, in <module>
    main()
  File "examples/fastspeech2/train_fastspeech2.py", line 405, in main
    trainer.fit(
  File "/home/tony/Documents/TensorFlowTTS/tensorflow_tts/trainers/base_trainer.py", line 1010, in fit
    self.run()
  File "/home/tony/Documents/TensorFlowTTS/tensorflow_tts/trainers/base_trainer.py", line 104, in run
    self._train_epoch()
  File "/home/tony/Documents/TensorFlowTTS/tensorflow_tts/trainers/base_trainer.py", line 126, in _train_epoch
    self._train_step(batch)
  File "/home/tony/Documents/TensorFlowTTS/tensorflow_tts/trainers/base_trainer.py", line 782, in _train_step
    self.one_step_forward(batch)
  File "/home/tony/.virtualenvs/tftts/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/home/tony/.virtualenvs/tftts/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/tony/.virtualenvs/tftts/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3039, in __call__
    return graph_function._call_flat(
  File "/home/tony/.virtualenvs/tftts/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/tony/.virtualenvs/tftts/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/home/tony/.virtualenvs/tftts/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  required broadcastable shapes
	 [[node tf_fast_speech2/add_1 (defined at /home/tony/Documents/TensorFlowTTS/tensorflow_tts/models/fastspeech2.py:185) ]]
	 [[tf_fast_speech2/length_regulator/while/loop_body_control/_117/_109]]
  (1) Invalid argument:  required broadcastable shapes
	 [[node tf_fast_speech2/add_1 (defined at /home/tony/Documents/TensorFlowTTS/tensorflow_tts/models/fastspeech2.py:185) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference__one_step_forward_27336]

Errors may have originated from an input operation.
Input Source operations connected to node tf_fast_speech2/add_1:
 tf_fast_speech2/encoder/layer_._2/mul (defined at /home/tony/Documents/TensorFlowTTS/tensorflow_tts/models/fastspeech.py:413)

Input Source operations connected to node tf_fast_speech2/add_1:
 tf_fast_speech2/encoder/layer_._2/mul (defined at /home/tony/Documents/TensorFlowTTS/tensorflow_tts/models/fastspeech.py:413)

Function call stack:
_one_step_forward -> _one_step_forward
```

This is exactly the same issue as #672 . That issue was labeled as "Bug" and it looks like it was not solved? 

So what can I do to get the training started?    

Thanks a lot!

**Comment by dathudeptrai** [comment]
This bug comes from data, not a model itself. I think you need to check what samples cause this problem by the code below:

```
for data in tqdm(train_dataloader):
    o = fastspeech(**data, training=True)
``` 

Note that you need to set batch_size = 1 so you can easily check what is a real problem with those samples :D

**Comment by Tian14267** [comment]
@godspirit00 
Hellow, Did you solve this problem ? 
I get same error ,but I don't know how to solve it.

**Comment by godspirit00** [comment]
@Tian14267 not yet. I'm still waiting for @dathudeptrai 's reply.

**Comment by wxyhv** [comment]
Have you solved this problem?
