### ISSUE TITLE
Running into issues with different dataset

### ISSUE THREAD

**Issue by jun-danieloh** [TensorSpeech/TensorflowTTS#77]
I am trying to train tacotron2 with my own dataset. Pre-processing is well completed and I am running into this issue when I try to run training. Can you help or give me an insight to fix this issue below? It looks to me that there are long sequence of sentences in my dataset which doesn't exist in LJSpeech dataset. I really appreciate if you can give me any hints on this.

```
2020-07-01 11:51:51.583087: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:233] Shuffle buffer fill
ed.                                                                                                      
2020-07-01 11:51:58.665870: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:563] function_optimiz
er failed: Invalid argument: Node 'tacotron2/StatefulPartitionedCall/encoder/bilstm/forward_lstm/Stateful
PartitionedCall_Func/tacotron2/StatefulPartitionedCall/output/_325': Connecting to invalid output 29 of s
ource node tacotron2/StatefulPartitionedCall/encoder/bilstm/forward_lstm/StatefulPartitionedCall which ha
s 29 outputs.                                                                                            
2020-07-01 11:51:58.942363: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:563] shape_optimizer 
failed: Out of range: src_output = 29, but num_outputs is only 29                                        
2020-07-01 11:51:59.117729: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:563] layout failed: O
ut of range: src_output = 29, but num_outputs is only 29                                                 
[train]:   0%|                                                 | 2/200000 [05:20<12392:19:13, 223.06s/it]
Traceback (most recent call last):                                                                       
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 1986, in executi
on_mode                                                                                                  
    yield                                                                                                
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 655, in 
_next_internal                                                                                           
    output_shapes=self._flat_output_shapes)   
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 236[0/339]
terator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6653, in raise_f
rom_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.DataLossError: Attempted to pad to a smaller size than the input
element. [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples_models/tacotron2/train_tacotron2.py", line 511, in <module>
    main()
  File "examples_models/tacotron2/train_tacotron2.py", line 504, in main
    resume=args.resume)
  File "examples_models/tacotron2/train_tacotron2.py", line 347, in fit
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 72, in run
    self._train_epoch()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/trainers/base_trainer.py", line 92, in _tra
in_epoch
    for train_steps_per_epoch, batch in enumerate(self.train_data_loader, 1):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 631, in
__next__
    return self.next()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 670, in
next
    return self._next_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 661, in
_next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 1989, in executi
on_mode
    executor_new.wait()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.DataLossError: Attempted to pad to a smaller size than the input
element.
[train]:   0%|                                                  | 2/200000 [05:21<8940:23:31, 160.93s/it]
```

**Comment by jun-danieloh** [comment]
MelGAN is running fine with my dataset as below.
```
2020-07-01 12:20:44.045416: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
[train]:   0%|                                                 | 200/4000000 [07:50<307:26:42,  3.61it/s]
2020-07-01 12:21:43,180 (train_melgan:285) INFO: (Step: 200) train_adversarial_loss = 0.4271.
2020-07-01 12:21:43,181 (train_melgan:285) INFO: (Step: 200) train_fm_loss = 0.0115.
2020-07-01 12:21:43,182 (train_melgan:285) INFO: (Step: 200) train_gen_loss = 0.4271.
2020-07-01 12:21:43,182 (train_melgan:285) INFO: (Step: 200) train_real_loss = 0.3065.
2020-07-01 12:21:43,183 (train_melgan:285) INFO: (Step: 200) train_fake_loss = 0.2251.
2020-07-01 12:21:43,183 (train_melgan:285) INFO: (Step: 200) train_dis_loss = 0.5316.
2020-07-01 12:21:43,184 (train_melgan:285) INFO: (Step: 200) train_mels_spectrogram_loss = 1.7616.
[train]:   0%|                                                 | 400/4000000 [08:45<303:16:26,  3.66it/s]
2020-07-01 12:22:38,062 (train_melgan:285) INFO: (Step: 400) train_adversarial_loss = 0.3807.
2020-07-01 12:22:38,063 (train_melgan:285) INFO: (Step: 400) train_fm_loss = 0.0122.
2020-07-01 12:22:38,063 (train_melgan:285) INFO: (Step: 400) train_gen_loss = 0.3807.
2020-07-01 12:22:38,064 (train_melgan:285) INFO: (Step: 400) train_real_loss = 0.2482.
2020-07-01 12:22:38,064 (train_melgan:285) INFO: (Step: 400) train_fake_loss = 0.2464.
2020-07-01 12:22:38,065 (train_melgan:285) INFO: (Step: 400) train_dis_loss = 0.4945.
2020-07-01 12:22:38,066 (train_melgan:285) INFO: (Step: 400) train_mels_spectrogram_loss = 1.5424.
[train]:   0%|                                                 | 600/4000000 [09:40<306:06:21,  3.63it/s]
```

**Comment by dathudeptrai** [comment]
@jun-danieloh hi, pls git pull again a project. I fixed the tacotron2_dataset to be able apply for other datasets, max_mel_length and max_char_length now calculate based on target dataset automatically and don't need to explicit so above bug should be disappear :D.

**Comment by jun-danieloh** [comment]
@dathudeptrai Which PR is it for this fix? I would like to see which codes have been changed.

**Comment by dathudeptrai** [comment]
https://github.com/TensorSpeech/TensorflowTTS/commit/cabca9f9d656928e580c156718a6f655e987766e

**Comment by jun-danieloh** [comment]
@dathudeptrai I went through you codes and found that the code that I am using has fixed max_char_length=190 and max_mel_length=870. Thanks!!
